# Contenu des éditions (textes validés dans les brouillons, chiffres sourcés)
E={}
E[5]=dict(n=5, slug="n5", week="Semaine du 28 septembre au 2 octobre 2026", short="28 sept.", theme="Budget, taux, inflation", read="4 min", note="",
 title="Le budget ne rassure pas, la France emprunte au plus cher depuis 2002.",
 chapo="Présenté jeudi, le projet de budget 2027 n'a pas apaisé les investisseurs. Dans la zone euro, les prix montent à un rythme inédit depuis trois ans.",
 photo="bercy", photo_alt="Le ministère de l'Économie et des Finances, à Bercy, au bord de la Seine au crépuscule", photo_cap="Le ministère de l'Économie et des Finances, à Bercy. Illustration générée par IA.",
 cap="Le projet de budget 2027 n'a pas convaincu les marchés : le taux auquel la France emprunte sur 10 ans a frôlé 5 %, un niveau jamais vu depuis 2002, et la Bourse de Paris a perdu plus de 2 % sur la semaine.",
 cap_hl="Le projet de budget 2027 n'a pas convaincu les marchés",
 reps=[("Taux de la France à 10 ans, jeudi 1er octobre","4,92 %","▲ Plus haut depuis juillet 2002","Indice officiel de la Banque de France (TEC 10) : 4,90 % les 1er et 2 octobre."),
       ("Inflation, zone euro, septembre","3,8 %","▲ Plus haut depuis septembre 2023","Contre 3,2 % en août. Les prix de l'énergie augmentent de 18,8 % sur un an."),
       ("CAC 40, semaine du 28 septembre au 2 octobre","−2,24 %","▼ À 7 897 points vendredi","Jeudi, l'indice a perdu 1,62 % en une séance.")],
 vents=["Jeudi 1er octobre, le gouvernement a présenté son projet de budget pour 2027 : un effort de 54 milliards d'euros pour ramener le déficit public de 5,4 % à 5 % du PIB. Le Haut Conseil des finances publiques, chargé d'évaluer ces prévisions, les juge « optimistes », et le vote du texte reste incertain dans une Assemblée sans majorité. Le doute s'est lu immédiatement dans le prix de la dette : sur la semaine, le taux français à 10 ans a gagné 0,13 point, quand celui de l'Allemagne en perdait 0,17. Les banques françaises, qui détiennent beaucoup d'obligations d'État, ont le plus reculé : Société Générale a cédé 5 % jeudi.",
        "L'inflation, elle, accélère. Selon l'estimation rapide d'Eurostat, elle atteint 3,8 % sur un an en septembre dans la zone euro, portée surtout par l'énergie. En France, l'Insee l'estime à 3,0 %, contre 2,4 % en août.",
        "Aux États-Unis, l'économie n'a créé que 29 000 emplois en septembre et le taux de chômage s'établit à 4,2 %. La Fed doit donc composer avec deux signaux opposés : une inflation encore élevée et un marché du travail qui ralentit."],
 vents_hl="Le doute s'est lu immédiatement dans le prix de la dette",
 chart=("taux_fr_de","Les taux français et allemands s'éloignent","Taux d'emprunt à 10 ans de la France et de l'Allemagne, à la clôture, du 25 septembre au 2 octobre 2026","Source : Investing.com, données de clôture, consultées le 06/10/2026. Écart calculé par Kompa. Graphique Kompa."),
 person=None,
 plus1=("Pourquoi « 2002 »","En juillet 2002, la France empruntait à 10 ans à 4,96 % en moyenne sur le mois. Le niveau est donc comparable à celui de cette semaine. Mais l'Allemagne payait alors presque autant : 4,87 %, soit un écart de 0,09 point seulement.|Cette semaine, l'écart a atteint environ 1,4 point. En 2002, les taux étaient élevés partout en Europe ; aujourd'hui, c'est surtout la France qui paie plus cher que ses voisins. C'est cette différence, plus que le niveau lui-même, que suivent les investisseurs. Source : OCDE, via la Réserve fédérale de Saint-Louis (FRED)."),
 rdv=[("7 oct.","Compte rendu de la réunion de la Fed des 15 et 16 septembre.","Source : Réserve fédérale."),("15 oct.","Chiffre définitif de l'inflation de septembre en France.","Source : Insee."),("16 oct.","Chiffre définitif de l'inflation de septembre en zone euro.","Source : Eurostat."),("29 oct.","Prochaine décision de la BCE sur ses taux.","Source : calendrier de la BCE.")],
 epargne="Cette semaine illustre l'intérêt de la diversification. Une seule action a pu perdre beaucoup en une journée ; un indice qui regroupe 40 entreprises a moins reculé ; et la dette allemande a évolué en sens inverse, recherchée quand l'inquiétude monte. Répartir son argent ne supprime pas le risque, mais évite de dépendre d'un seul épisode.",
 epargne_hl="la diversification",
 ex=[("Société Générale, jeudi 1er","−5 %","une seule action"),("CAC 40, jeudi 1er","−1,62 %","40 grandes entreprises"),("Taux allemand à 10 ans, sur la semaine","−0,17 point","le prix de ces obligations monte")],
 ex_note="Sources : BFM Bourse, 01/10 ; Investing.com, clôtures du 25/09 au 02/10. Exemple illustratif, pas une recommandation.",
 plus2=None,
 mot=("La valeur refuge","n. f.","Une valeur refuge est un placement vers lequel les investisseurs se tournent quand l'inquiétude monte, parce qu'il est jugé plus sûr : l'or, certaines monnaies ou la dette de l'Allemagne, par exemple. Cette semaine, pendant que le taux français montait, celui de l'Allemagne baissait, signe que les investisseurs achetaient de la dette allemande. Refuge ne veut pas dire sans risque : la valeur de ces placements peut aussi baisser."),
 point="Le budget n'a pas levé les doutes, l'inflation repart : l'écart entre la France et l'Allemagne se creuse.",
 next_="N°6, lundi 12 octobre",
 sources="Banque de France (TEC 10), 01-02/10 · Eurostat, 02/10 · Insee, 30/09 · Bureau of Labor Statistics, 02/10 · OCDE via FRED · Investing.com, 25/09-02/10 · Euronews, 01/10 et 02/10 · Journal du Net, 01/10 · BFM Bourse, 01/10 et 02/10 · ABC Bourse, 01/10")
E[4]=dict(n=4, slug="n4", week="Semaine du 21 au 25 septembre 2026", short="21 sept.", theme="Pétrole, activité, Bourse", read="4 min", note="",
 title="Le pétrole suit la diplomatie, la Bourse de Paris reprend son souffle.",
 chapo="Le baril fait le yo-yo au rythme des nouvelles du Moyen-Orient. L'Europe accélère, la France hésite, et le CAC 40 met fin à six semaines de baisse.",
 photo="raffinerie", photo_alt="Une raffinerie de pétrole illuminée au crépuscule", photo_cap="Une raffinerie de pétrole, au crépuscule.",
 cap="Le pétrole monte et descend au rythme de la diplomatie au Moyen-Orient. Malgré ces secousses, la Bourse de Paris signe sa première semaine de hausse depuis début août.",
 cap_hl="Le pétrole monte et descend au rythme de la diplomatie",
 reps=[("Brent, jeudi 24 septembre","106,60 $","▲ +3,41 % dans la journée","Plus haut depuis le 15 septembre, avant un repli vendredi."),
       ("CAC 40, semaine du 21 au 25 septembre","+0,16 %","▲ Première semaine de hausse depuis début août","Après six semaines de baisse d'affilée (−7,46 %)."),
       ("Activité, zone euro (PMI)","53,1","▲ Plus haut depuis 41 mois","Au-dessus de 50, l'activité progresse.")],
 vents=["Depuis le début du conflit au Moyen-Orient en février, le prix du pétrole réagit à chaque nouvelle diplomatique. Lundi, l'Assemblée générale de l'ONU à New York a fait espérer des échanges entre Washington et Téhéran : le baril est passé sous 100 dollars. Mercredi, un navire touché par un projectile dans le détroit d'Ormuz a ravivé l'inquiétude, et jeudi le Brent a clôturé à 106,60 dollars. Vendredi, une proposition iranienne pour rouvrir le détroit d'Ormuz sous sept jours l'a fait reculer.",
        "Côté activité, les chiffres divergent. Dans la zone euro, l'indice PMI, un sondage mensuel auprès des entreprises, atteint 53,1 en septembre, son plus haut niveau depuis 41 mois. En France, l'indicateur du climat des affaires de l'Insee recule de 2 points, à 96, sous sa moyenne de long terme de 100, surtout à cause du commerce de détail. Le tableau reste nuancé : l'indice PMI français repasse en croissance pour la première fois depuis dix mois.",
        "Aux États-Unis enfin, plusieurs responsables de la Fed ont souligné ces derniers jours la nécessité de nouvelles hausses de taux pour lutter contre l'inflation."],
 vents_hl="le prix du pétrole réagit à chaque nouvelle diplomatique",
 chart=("dumbbell","L'Europe accélère, la France hésite","Indice PMI composite de la zone euro et indicateur du climat des affaires de l'Insee, août et septembre 2026","Sources : S&P Global, 23/09 ; Insee, Informations rapides n° 231, 24/09. Graphique Kompa."),
 person=None,
 plus1=("Pourquoi « 41 mois »","L'indice PMI interroge chaque mois des directeurs d'achat sur l'activité de leur entreprise. Au-dessus de 50, l'activité progresse ; en dessous, elle recule. Le niveau de septembre est le plus élevé depuis avril 2023, soit 41 mois : l'activité du secteur privé de la zone euro n'avait pas été aussi dynamique depuis près de trois ans et demi, malgré la hausse des taux."),
 rdv=[("7 oct.","Compte rendu de la réunion de la Fed des 15 et 16 septembre.","Source : Réserve fédérale."),("28 oct.","Prochaine décision de la Fed sur ses taux.","Source : Réserve fédérale."),("29 oct.","Prochaine décision de la BCE sur ses taux.","Source : calendrier de la BCE.")],
 epargne="Quand le pétrole fait le yo-yo, les marchés suivent : la valeur d'un placement en actions, ou d'une assurance-vie en unités de compte, peut varier nettement d'un jour à l'autre. Sur l'ensemble de la semaine, le CAC 40 a pourtant fini presque stable. C'est tout l'intérêt de l'horizon de placement : une somme dont on n'aura pas besoin avant plusieurs années a le temps de traverser ces secousses, alors qu'une somme dont on pourrait avoir besoin rapidement y est bien plus exposée.",
 epargne_hl="l'horizon de placement",
 ex=[("Brent, lundi 21","99,99 $","sous la barre des 100 $"),("Brent, jeudi 24","106,60 $","≈ +6,6 % en trois séances"),("CAC 40, sur la semaine","+0,16 %","presque stable au final")],
 ex_note="Sources : BFM Bourse, 21/09 et 25/09 ; Prix du baril, 25/09. Calcul Kompa : 106,60 ÷ 99,99.",
 plus2=None,
 mot=("Le spread","n. m., anglicisme","Le spread désigne l'écart entre deux prix, deux taux d'intérêt ou deux rendements. On l'emploie souvent pour l'écart entre les taux auxquels deux États empruntent sur une même durée : en zone euro, on le mesure généralement par rapport à l'Allemagne, jugée l'emprunteur le plus solide. Plus il s'élargit, plus les investisseurs considèrent le pays comme risqué et réclament une rémunération supplémentaire pour lui prêter."),
 point="Le pétrole reste suspendu à la diplomatie, mais la Bourse de Paris a enfin repris son souffle.",
 next_="N°5, lundi 5 octobre",
 sources="BFM Bourse, 21 et 25/09 · L'Avenir (AFP), 21/09 · S&P Global, 23/09 · Trading Economics, 23/09 · Insee, 24/09 · Prix du baril, 25/09 · France Épargne (Reuters), 25/09 · Zonebourse, 25/09")
E[3]=dict(n=3, slug="n3", week="Semaine du 14 au 18 septembre 2026", short="14 sept.", theme="Taux, banques centrales", read="4 min", note="",
 title="La Fed relève à son tour ses taux, la dette française sous pression.",
 chapo="Après la BCE, la banque centrale américaine monte ses taux. En France, l'État paie nettement plus cher que l'Allemagne pour emprunter.",
 photo="bourse", photo_alt="Fronton du palais Brongniart, où l'on lit « Bourse »", photo_cap="Le palais Brongniart, ancien siège de la Bourse de Paris.",
 cap="Après la BCE, la banque centrale américaine monte ses taux. En France, l'État paie nettement plus cher que l'Allemagne pour emprunter.",
 cap_hl="Après la BCE, la banque centrale américaine monte ses taux.",
 reps=[("Taux de la Fed","3,75–4 %","▲ +0,25 point","Première hausse depuis 2023, décidée le 16 septembre."),
       ("Écart France − Allemagne à 10 ans","&gt; 1 point","● Seuil franchi","Une première depuis 2012, vendredi 18 septembre."),
       ("CAC 40, vendredi 18 septembre","8 065 pts","▼ −1,49 %","Environ −1,4 % sur l'ensemble de la semaine.")],
 vents=["Aux États-Unis aussi, l'inflation reste au-dessus de l'objectif. Une semaine après la BCE, la Fed resserre à son tour sa politique pour la freiner : c'est la première hausse décidée sous la présidence de Kevin Warsh. En zone euro, Eurostat a pour sa part légèrement révisé l'inflation d'août, à 3,2 %.",
        "En France, les investisseurs s'inquiètent en plus du niveau du déficit public et des débats sur le budget 2027 : ils demandent donc une rémunération plus élevée pour prêter à l'État."],
 vents_hl="la Fed resserre à son tour sa politique",
 chart=("fed","Le taux de la Fed remonte, après un an et demi de baisses","Taux directeur de la Réserve fédérale (borne haute de la fourchette), de janvier 2024 à septembre 2026","Sources : Réserve fédérale ; CNBC, 16/09/2026. Graphique Kompa."),
 person=("warsh","Portrait officiel de Kevin Warsh","Kevin Warsh, président de la Fed depuis le 22 mai 2026. Photo : Federal Reserve."),
 plus1=("Pourquoi « 2012 » est un repère","La dernière fois que l'écart entre les taux français et allemands dépassait 1 point, c'était en 2012, en pleine crise des dettes de la zone euro. Les investisseurs doutaient alors de la capacité de plusieurs États à rembourser. La tension était retombée après l'engagement de la BCE, en juillet 2012, à faire le nécessaire pour préserver l'euro.|Le contexte n'est pas le même aujourd'hui. Depuis juillet 2022, la BCE dispose d'un outil, l'IPT (instrument de protection de la transmission, ou TPI en anglais), conçu pour intervenir si l'écart de taux d'un pays s'emballait sans raison économique. Le chiffre de 2012 sert donc de thermomètre, pas de prévision."),
 rdv=[("23 sept.","Indice PMI de la zone euro : l'activité des entreprises en septembre.","Source : S&P Global."),("24 sept.","Climat des affaires en France.","Source : Insee."),("29 oct.","Prochaine décision de la BCE sur ses taux.","Source : calendrier de la BCE.")],
 epargne="Le taux auquel l'État emprunte sert de repère à beaucoup d'autres taux, dont ceux des crédits immobiliers. Quand il monte, les obligations déjà émises, moins bien rémunérées que les nouvelles, perdent de la valeur : c'est ce qui peut faire baisser un fonds obligataire, y compris dans une assurance-vie en unités de compte.",
 epargne_hl="perdent de la valeur",
 ex=[("Votre obligation","3 %","achetée avant la hausse"),("Les nouvelles","4 %","émises après la hausse"),("Résultat","Prix ↓","la vôtre vaut moins à la revente")],
 ex_note="Exemple illustratif, chiffres fictifs.",
 plus2=("Le calcul complet","calc_bond"),
 mot=("L'OAT","n. f., sigle","L'OAT (obligation assimilable du Trésor) est le titre de dette que l'État français émet pour emprunter sur les marchés. Son taux à 10 ans est le plus suivi : il indique combien la France paie pour emprunter sur cette durée."),
 point="Les banques centrales resserrent pour freiner l'inflation, et la France paie plus cher sa dette.",
 next_="N°4, lundi 28 septembre",
 sources="CNBC, 16/09 · Renseignement Économique, 17/09 · Option Finance (Eurostat), 17/09 · Zonebourse, 18/09 · XTB, 18/09 · BFM Bourse, 11/09 · Réserve fédérale, 22/05")
E[2]=dict(n=2, slug="n2", week="Semaine du 7 au 11 septembre 2026", short="7 sept.", theme="Banques centrales, pétrole", read="4 min", note="",
 title="La BCE relève ses taux, le pétrole repasse les 100 dollars.",
 chapo="Pour freiner l'inflation, la Banque centrale européenne monte ses taux pour la deuxième fois de l'année. Le baril franchit de nouveau un seuil symbolique.",
 photo="eurosign", photo_alt="Le symbole de l'euro illuminé, la nuit, à Francfort", photo_cap="Le symbole de l'euro, devant l'ancien siège de la BCE à Francfort.",
 cap="La BCE relève ses taux pour freiner une inflation poussée par l'énergie, pendant que le pétrole repasse au-dessus de 100 dollars.",
 cap_hl="La BCE relève ses taux pour freiner une inflation poussée par l'énergie",
 reps=[("Taux de dépôt de la BCE","2,50 %","▲ +0,25 point","Décidé le 10 septembre, applicable le 16."),
       ("Brent, mercredi 9 septembre","&gt; 100 $","● Seuil franchi","Une première depuis fin juillet."),
       ("CAC 40, vendredi 11 septembre","8 179,59 pts","▼ −1,2 % sur la semaine","Malgré un rebond de 0,78 % vendredi.")],
 vents=["L'inflation de la zone euro a atteint 3,3 % en août, surtout à cause de l'énergie. La mission de la BCE est de la ramener vers 2 % : relever ses taux rend le crédit plus cher, ce qui freine la demande et donc la hausse des prix.",
        "Selon ses nouvelles projections, l'inflation atteindrait en moyenne 3 % en 2026, puis 2,5 % en 2027 et 2,1 % en 2028. Le pétrole, lui, reste porté par le conflit au Moyen-Orient."],
 vents_hl="relever ses taux rend le crédit plus cher",
 chart=("bce","La BCE remonte ses taux, après un an et demi de baisses","Taux de la facilité de dépôt de la BCE, de janvier 2024 à septembre 2026","Sources : BCE, 10/09/2026 ; Toute l'Europe, 10/09/2026. Graphique Kompa."),
 person=None,
 plus1=("Pourquoi « deuxième hausse de l'année »","Après avoir baissé ses taux de 4 % à 2 % entre juin 2024 et juin 2025, la BCE les a laissés stables pendant un an. Elle a changé de cap en juin 2026, pour la première fois depuis 2023, face au retour de l'inflation. La hausse de septembre prolonge ce mouvement."),
 rdv=[("16 sept.","Décision de la Fed sur ses taux.","Source : Réserve fédérale."),("17 sept.","Chiffre définitif de l'inflation d'août en zone euro.","Source : Eurostat."),("29 oct.","Prochaine décision de la BCE sur ses taux.","Source : calendrier de la BCE.")],
 epargne="Une hausse des taux de la BCE se répercute progressivement, et pas mécaniquement, sur le coût des crédits immobiliers. Elle peut aussi, avec un décalage, améliorer la rémunération de certains placements dont le rendement suit les taux.",
 epargne_hl="se répercute progressivement",
 ex=[("Crédit de 200 000 € sur 20 ans","3,50 %","≈ 1 160 € par mois"),("Le même crédit","3,75 %","≈ 1 186 € par mois"),("Écart","≈ +26 €","par mois, pour +0,25 point")],
 ex_note="Exemple illustratif, hors assurance et frais. Calcul Kompa.",
 plus2=None,
 mot=("Le taux directeur","n. m.","Le taux directeur est le taux fixé par une banque centrale pour prêter aux banques ou rémunérer leurs dépôts. En le modifiant, elle influence tous les autres taux de l'économie : ceux des crédits comme ceux de l'épargne."),
 point="La BCE resserre pour freiner une inflation tirée par l'énergie, et le pétrole ne lui facilite pas la tâche.",
 next_="N°3, lundi 21 septembre",
 sources="BCE, 10/09 · Bulletin économique de la BCE (Banque de France) · Toute l'Europe, 10/09 · La Couronne, 10/09 · Économie Matin, 10/09 · BFM Bourse, 11/09")
E[1]=dict(n=1, slug="n1", week="Semaine du 1er au 4 septembre 2026", short="1er sept.", theme="Inflation, emploi", read="4 min", note="",
 title="L'inflation remonte en Europe, l'emploi américain surprend.",
 chapo="L'énergie pousse les prix de la zone euro à 3,3 % sur un an. Outre-Atlantique, les créations d'emplois dépassent largement les attentes.",
 photo="europiece", photo_alt="Gros plan sur une pièce de 2 euros", photo_cap="Une pièce de 2 euros.",
 cap="Les prix repartent à la hausse en Europe, tirés par l'énergie, pendant que l'économie américaine reste plus solide que prévu.",
 cap_hl="Les prix repartent à la hausse en Europe",
 reps=[("Inflation, zone euro, août","3,3 %","● Au-dessus de l'objectif de 2 %","Estimation rapide d'Eurostat du 1er septembre, révisée à 3,2 % le 17 septembre."),
       ("Emplois créés aux États-Unis, août","162 000","▲ Environ 55 000 attendus","Le chômage reste stable, à 4,1 %."),
       ("CAC 40, vendredi 4 septembre","≈ 8 280 pts","▼ −1,5 % sur la semaine","La Bourse accueille ces chiffres avec prudence.")],
 vents=["Depuis février, le conflit au Moyen-Orient perturbe l'approvisionnement en pétrole, ce qui renchérit l'énergie et pousse les prix à la hausse en Europe.",
        "Aux États-Unis, un marché de l'emploi solide est une bonne nouvelle pour l'économie, mais il laisse à la Fed davantage de marge pour relever ses taux : c'est pourquoi la Bourse l'a accueilli avec prudence."],
 vents_hl="renchérit l'énergie",
 chart=("inflation","L'énergie tire l'inflation vers le haut","Inflation de la zone euro sur un an, en août 2026 (estimation rapide), par composante","Sources : Eurostat, estimation rapide du 01/09/2026, via Euronews. Graphique Kompa."),
 person=None,
 plus1=("Le repère : 2022","La zone euro a déjà connu bien pire : en octobre 2022, après le début de la guerre en Ukraine, l'inflation avait atteint 10,6 %, un record depuis la création de l'indicateur en 1997. Elle était ensuite redescendue autour de 2 %. Le niveau d'août reste loin de ce pic, mais la tendance est de nouveau à la hausse, et l'énergie en est le principal moteur."),
 rdv=[("10 sept.","Décision de la BCE sur ses taux.","Source : calendrier de la BCE."),("16 sept.","Décision de la Fed sur ses taux.","Source : Réserve fédérale.")],
 epargne="L'inflation réduit ce que votre épargne permet d'acheter. Un placement qui rapporte moins que l'inflation fait perdre du pouvoir d'achat, même si son montant affiché augmente.",
 epargne_hl="fait perdre du pouvoir d'achat",
 ex=[("Votre placement rapporte","2 %","sur un an"),("Les prix augmentent de","3,3 %","sur un an"),("Pouvoir d'achat","≈ −1,3 %","même si le montant grandit")],
 ex_note="Exemple illustratif. Calcul Kompa : 1,02 ÷ 1,033.",
 plus2=None,
 mot=("L'inflation sous-jacente","n. f.","L'inflation sous-jacente mesure la hausse des prix hors énergie et alimentation, deux postes très volatils. Les banques centrales la suivent de près, car elle montre si la hausse des prix se diffuse durablement au reste de l'économie."),
 point="L'énergie relance l'inflation en Europe, et l'économie américaine tient bon.",
 next_="N°2, lundi 14 septembre",
 sources="Eurostat, 01/09 et 17/09 · Euronews, 01/09 · Bureau of Labor Statistics, 04/09 · Moneyvox, 04/09")
