import type { Bank } from "../types";
import { FICHE, AMF_VOTE_AG, BOFIP_TTF, BOFIP_TTF_LISTE, SP_PEA, ISHARES_SP500_FS, AMUNDI_CAC40_FS } from "../sources";

export const apple: Bank = {
  id: "apple-action",
  name: "Action Apple Inc. (AAPL)",
  sub: "US0378331005",
  short: "Action Apple",
  family: "Actions",
  share: "Mon action Apple, je la comprends",
  axes: ["Nature", "Revenus", "Coûts", "Enveloppe", "Risque"],
  src: {
    appbourse: { name: "Apple, relations investisseurs, cours de l'action", date: "consultée le 7 oct. 2026", url: "https://investor.apple.com/stock-price/default.aspx", refresh: "Revu à chaque test" },
    appdiv: { name: "Apple, relations investisseurs, historique des dividendes", date: "consultée le 7 oct. 2026", url: "https://investor.apple.com/dividend-history/default.aspx", refresh: "Revu à chaque annonce de dividende", watch: true },
    bofipl: BOFIP_TTF_LISTE,
    bofip: BOFIP_TTF,
    sp: SP_PEA,
    cspx: ISHARES_SP500_FS,
    fiche: FICHE,
  },
  questions: [
    { id: "p1", axis: "Nature", type: "choice",
      prompt: "En achetant une action Apple, vous détenez&nbsp;:",
      options: ["Une part d'un fonds investi dans la technologie", "Une toute petite part de l'entreprise Apple, cotée au Nasdaq, en dollars", "Un prêt fait à Apple", "Un avoir sur les produits Apple"], correct: 1,
      good: "Une part de l'entreprise Apple",
      explain: "Une action est une part du capital d'une entreprise. Celle d'Apple est cotée au Nasdaq, à New York, sous le code AAPL. Son prix est exprimé en dollars.",
      fact: { label: "Cotation de l'action", value: "Nasdaq, code AAPL", src: "appbourse" },
      ask: "Sur quelle place de bourse mon ordre d'achat sera-t-il exécuté, et à quelles heures&nbsp;?" },
    { id: "p2", axis: "Revenus", type: "choice",
      prompt: "À quel rythme Apple verse-t-elle un dividende à ses actionnaires&nbsp;?",
      options: ["Jamais", "Chaque trimestre", "Une fois par an", "Chaque mois"], correct: 1,
      good: "Chaque trimestre",
      explain: "Apple annonce un dividende environ tous les trois mois. Il est versé en dollars&nbsp;: son montant en euros dépend aussi du taux de change. Comme tout dividende, il n'est pas garanti.",
      fact: { label: "Fréquence du dividende", value: "Trimestrielle, en dollars", src: "appdiv" },
      ask: "Comment les dividendes d'actions américaines sont-ils imposés sur mon compte&nbsp;?" },
    { id: "p3", axis: "Coûts", type: "choice",
      prompt: "Vous achetez pour 10&nbsp;000&nbsp;€ d'actions Apple. La taxe française sur les transactions financières (0,4&nbsp;%) s'applique-t-elle&nbsp;?",
      options: ["Oui, 40&nbsp;€", "Non&nbsp;: elle ne vise que les grandes sociétés françaises", "Oui, 400&nbsp;€"], correct: 1,
      good: "Non",
      explain: "Cette taxe porte sur l'achat d'actions de sociétés françaises valant plus d'un milliard d'euros en bourse, listées chaque année par l'administration fiscale. Apple n'en fait pas partie. Les frais de votre courtier, eux, s'appliquent, et peuvent comprendre des frais de change.",
      fact: { label: "Taxe sur les transactions financières", value: "Ne concerne pas Apple, société américaine", src: "bofipl" },
      ask: "Quels frais me facturez-vous pour acheter une action américaine, change compris&nbsp;?" },
    { id: "p4", axis: "Enveloppe", type: "tf",
      prompt: "Une action Apple peut être logée dans un PEA.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "Le PEA accueille les actions de sociétés établies dans l'Union européenne ou l'Espace économique européen. Les actions de sociétés américaines n'y sont pas éligibles&nbsp;: Apple se détient en compte-titres.",
      fact: { label: "Éligibilité au PEA", value: "Non, société américaine", src: "sp" },
      ask: "Quels sont les frais et la fiscalité de mon compte-titres&nbsp;?" },
    { id: "p5", axis: "Risque", type: "choice",
      prompt: "Imaginons&nbsp;: le dollar perd 10&nbsp;% face à l'euro, et le cours d'Apple ne bouge pas en dollars. Votre action, comptée en euros&nbsp;:",
      options: ["Monte d'environ 10&nbsp;%", "Baisse d'environ 10&nbsp;%", "Ne bouge pas"], correct: 1,
      good: "Elle baisse d'environ 10&nbsp;%",
      explain: "L'action vaut le même nombre de dollars, mais chaque dollar vaut moins d'euros. Pour un épargnant en euros, le résultat dépend à la fois du cours d'Apple et du taux de change.",
      fact: { label: "Devise de cotation", value: "Dollar américain", src: "appbourse" },
      ask: "Comment le change est-il appliqué quand j'achète ou je vends cette action&nbsp;?" },
    { id: "p6", axis: "Risque", type: "slider",
      min: 0, max: 30, step: 0.5, start: 15, unit: "%", target: 7.06, tol: [1.5, 4], dec: 1, gapUnit: "point",
      real: "7,06&nbsp;%", realLabel: "Réalité (fiche iShares Core S&P 500, au 31 août 2026)",
      prompt: "Vous détenez peut-être déjà un ETF S&P 500. Selon vous, quelle part de cet ETF est investie dans Apple&nbsp;?",
      good: "7,06&nbsp;%",
      explain: "Apple est la deuxième ligne de l'ETF iShares Core S&P 500, derrière Nvidia. Avec un ETF S&P 500 ou World et des actions Apple en direct, vous êtes exposé deux fois à la même entreprise.",
      fact: { label: "Poids d'Apple dans l'ETF iShares Core S&P 500", value: "7,06&nbsp;%", src: "cspx" },
      ask: "Quelle est ma vraie exposition à Apple, en comptant mes fonds&nbsp;?" },
    { id: "p7", axis: "Risque", type: "doc",
      doc: { title: "Fiche Kompa", sub: "Extrait de la fiche du Décodeur", section: "Principaux risques", foot: "Phrases issues de la fiche Apple du Décodeur ou proches de celle-ci." },
      prompt: "Voici un extrait de la fiche. Touchez la phrase qui décrit un risque propre à Apple, plutôt qu'à toute la bourse.",
      sentences: [
        "Les actions peuvent baisser quand l'ensemble des marchés recule.",
        "Le cours dépend fortement des ventes de smartphones et du marché chinois.",
        "L'action est cotée au Nasdaq.",
        "Le dividende est versé chaque trimestre.",
      ], correct: 1, tag: "Un risque propre à l'entreprise",
      good: "Les smartphones et la Chine",
      explain: "La fiche cite la dépendance aux smartphones et à la Chine&nbsp;: un risque lié à l'entreprise, qui s'ajoute au risque général de la bourse. Un fonds très diversifié le dilue&nbsp;; une action seule le porte entièrement.",
      fact: { label: "Risque propre à l'entreprise", value: "Dépendance aux smartphones et au marché chinois", src: "fiche" },
      ask: "Quels événements récents ont fait bouger le cours d'Apple, et pourquoi&nbsp;?" },
  ],
  notes: [
    "La fiche du Décodeur indique un dividende « d'environ 1,08 $ par action et par an actuellement » et un rendement « d'environ 0,3 % » sans source ni date. Le dernier dividende listé par Apple au 7 oct. 2026 est de 0,27 $ (annoncé le 30 avril 2026).",
  ],
};

export const lvmh: Bank = {
  id: "lvmh-action",
  name: "Action LVMH Moët Hennessy Louis Vuitton",
  sub: "FR0000121014",
  short: "Action LVMH",
  family: "Actions",
  share: "Mon action LVMH, je la comprends",
  axes: ["Nature", "Revenus", "Coûts", "Risque", "Disponibilité"],
  src: {
    amfag: AMF_VOTE_AG,
    bofip: BOFIP_TTF,
    bofipl: BOFIP_TTF_LISTE,
    euronext: { name: "Euronext, fiche de l'action LVMH", date: "consultée le 6 oct. 2026", url: "https://live.euronext.com/fr/product/equities/FR0000121014-XPAR", refresh: "Revu à chaque test" },
    ish: { name: "iShares, page de l'ETF iShares Core MSCI World", date: "2 oct. 2026", url: "https://www.ishares.com/uk/individual/en/products/251882/ishares-msci-world-ucits-etf-acc-fund", refresh: "Revu à chaque mise à jour de la page" },
    fiche: FICHE,
  },
  questions: [
    { id: "l1", axis: "Nature", type: "choice",
      prompt: "En achetant une action LVMH, vous devenez&nbsp;:",
      options: ["Prêteur de LVMH, remboursé à une date fixée", "Copropriétaire d'une toute petite part de l'entreprise", "Client privilégié des marques du groupe", "Porteur d'un fonds investi dans le luxe"], correct: 1,
      good: "Copropriétaire d'une petite part de l'entreprise",
      explain: "Une action est une part du capital d'une entreprise. En tant qu'actionnaire, vous pouvez voter en assemblée générale, où les actionnaires décident notamment de ce que devient le résultat de l'année. Prêter à une entreprise, c'est acheter une obligation&nbsp;: un tout autre produit.",
      fact: { label: "Le rôle des actionnaires", value: "Ils votent en assemblée générale, notamment sur l'affectation du résultat", src: "amfag" },
      ask: "Comment puis-je voter à l'assemblée générale de LVMH avec mon compte&nbsp;?" },
    { id: "l2", axis: "Revenus", type: "tf",
      prompt: "LVMH a versé un dividende l'an dernier. Il sera donc forcément versé cette année.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "Le dividende n'est jamais garanti. Chaque année, les actionnaires réunis en assemblée générale décident de l'affectation du résultat. Le dividende peut être maintenu, augmenté, réduit ou supprimé.",
      fact: { label: "Décision sur le dividende", value: "Votée chaque année en assemblée générale", src: "amfag" },
      ask: "Quels dividendes LVMH a-t-elle effectivement versés ces dernières années, et à quelles dates&nbsp;?" },
    { id: "l3", axis: "Coûts", type: "choice",
      prompt: "Vous achetez pour 10&nbsp;000&nbsp;€ d'actions LVMH en bourse. En plus des frais de votre courtier, que payez-vous&nbsp;?",
      options: ["Rien de plus", "40&nbsp;€ de taxe sur les transactions financières", "200&nbsp;€ de TVA", "Des frais courants de 0,20&nbsp;% par an, comme un fonds"], correct: 1,
      good: "40&nbsp;€ de taxe sur les transactions financières",
      explain: "L'achat d'actions de grandes sociétés françaises (plus d'un milliard d'euros en bourse) supporte une taxe de 0,4&nbsp;% depuis le 1er avril 2025, soit 40&nbsp;€ pour 10&nbsp;000&nbsp;€. LVMH figure sur la liste publiée par l'administration fiscale pour 2026. Une action n'a pas de frais courants&nbsp;: ceux-là concernent les fonds.",
      fact: { label: "Taxe sur les transactions financières", value: "0,4&nbsp;% du montant acheté, LVMH concernée en 2026", src: "bofip", note: "Liste des sociétés concernées&nbsp;: BOFiP du 17 décembre 2025." },
      ask: "Quels frais me prélevez-vous à chaque achat et à chaque vente d'actions, taxe comprise&nbsp;?" },
    { id: "l4", axis: "Risque", type: "choice",
      prompt: "Détenir uniquement des actions LVMH, c'est miser sur&nbsp;:",
      options: ["Une seule entreprise, même si elle possède de nombreuses marques", "Tout le secteur mondial du luxe", "Les 40 entreprises du CAC 40", "Un panier d'environ 1&nbsp;250 entreprises, comme un ETF World"], correct: 0,
      good: "Une seule entreprise",
      explain: "LVMH regroupe de nombreuses maisons, mais c'est une seule société cotée&nbsp;: si elle déçoit, tout votre placement en dépend. Elle fait partie du CAC 40 sans le résumer. Pour comparer, l'ETF World du Décodeur détient 1&nbsp;250 lignes (iShares, au 2 octobre 2026).",
      fact: { label: "Cotation de l'action", value: "Une seule société, cotée sur Euronext Paris, membre du CAC 40", src: "euronext" },
      ask: "Quelle part de mon épargne totale repose sur une seule entreprise&nbsp;?" },
    { id: "l5", axis: "Risque", type: "doc",
      doc: { title: "Fiche Kompa", sub: "Extrait de la fiche du Décodeur", section: "Principaux risques", foot: "Phrases issues de la fiche LVMH du Décodeur ou proches de celle-ci." },
      prompt: "Voici un extrait de la fiche. Touchez la phrase qui décrit un risque propre à LVMH, plutôt qu'à toute la bourse.",
      sentences: [
        "Les actions peuvent baisser quand l'ensemble des marchés recule.",
        "Le cours est sensible à la demande en Chine et aux dépenses des clients aisés.",
        "L'action est cotée en continu à la Bourse de Paris.",
        "Le dividende est voté chaque année en assemblée générale.",
      ], correct: 1, tag: "Un risque propre à l'entreprise",
      good: "La demande en Chine et les clients aisés",
      explain: "La fiche cite la conjoncture chinoise et la consommation des clients aisés&nbsp;: un risque lié au secteur et à l'entreprise, qui s'ajoute au risque général de la bourse. Un fonds très diversifié le dilue&nbsp;; une action seule le porte entièrement.",
      fact: { label: "Risque propre à l'entreprise", value: "Sensibilité à la demande en Chine et aux clients aisés", src: "fiche" },
      ask: "Quels événements récents ont fait bouger le cours de LVMH, et pourquoi&nbsp;?" },
    { id: "l6", axis: "Disponibilité", type: "choice",
      prompt: "Vous voulez vendre vos actions LVMH. Quand pouvez-vous le faire&nbsp;?",
      options: ["Seulement à une date anniversaire", "Chaque jour de bourse, en continu, au prix du moment", "Une fois par mois, au prix fixé par LVMH", "Seulement après un délai de 5 ans"], correct: 1,
      good: "Chaque jour de bourse, au prix du moment",
      explain: "L'action est cotée en continu sur Euronext Paris&nbsp;: vous pouvez vendre pendant les heures de bourse, au prix proposé à cet instant. La vente est rapide, mais le prix n'est jamais connu à l'avance.",
      fact: { label: "Mode de cotation", value: "Cotation en continu sur Euronext Paris", src: "euronext" },
      ask: "Quels frais s'appliquent si je vends, et sous quel délai l'argent arrive-t-il sur mon compte&nbsp;?" },
    { id: "l7", axis: "Disponibilité", type: "tf",
      prompt: "Comme une obligation, une action LVMH a une date à laquelle on vous rembourse votre mise.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "Une action n'a ni échéance ni remboursement prévu. Vous la gardez aussi longtemps que vous le voulez, et ce que vous récupérez dépend du prix au moment où vous vendez, plus les dividendes éventuellement reçus.",
      fact: { label: "Échéance d'une action", value: "Aucune&nbsp;: on en sort en revendant en bourse", src: "fiche" },
      ask: "Si je garde mes actions longtemps, quels frais de tenue de compte s'appliquent chaque année&nbsp;?" },
  ],
  notes: [
    "La fiche du Décodeur annonce un dividende « estimé à environ 13,4 € par action pour 2026 » : c'est une estimation, donc une forme de prévision, sans source ni date. À remplacer par le dernier dividende versé, avec sa source.",
    "Taux de 0,4 % confirmé par le BOFiP du 28 mai 2025. Je n'ai pas pu ouvrir la version actuelle de l'article sur Légifrance : à revérifier juste avant la mise en ligne.",
  ],
};

export const totalenergies: Bank = {
  id: "totalenergies-action",
  name: "Action TotalEnergies SE",
  sub: "FR0000120271",
  short: "Action TotalEnergies",
  family: "Actions",
  share: "Mon action TotalEnergies, je la comprends",
  axes: ["Risque", "Revenus", "Coûts", "Enveloppe", "Nature"],
  src: {
    tte: { name: "TotalEnergies, communiqué sur le premier acompte sur dividende 2026", date: "29 avr. 2026", url: "https://totalenergies.com/system/files/documents/totalenergies_cp-dividende-1T26_2026_fr.pdf", refresh: "Revu à chaque annonce de dividende", watch: true },
    amfag: AMF_VOTE_AG,
    bofip: BOFIP_TTF,
    bofipl: BOFIP_TTF_LISTE,
    sp: SP_PEA,
    cac: AMUNDI_CAC40_FS,
    fiche: FICHE,
  },
  questions: [
    { id: "o1", axis: "Risque", type: "doc",
      doc: { title: "Fiche Kompa", sub: "Extrait de la fiche du Décodeur", section: "Principaux risques", foot: "Phrases issues de la fiche TotalEnergies du Décodeur ou proches de celle-ci." },
      prompt: "Voici un extrait de la fiche. Touchez la phrase qui décrit le principal risque propre à TotalEnergies.",
      sentences: [
        "Les actions peuvent baisser quand l'ensemble des marchés recule.",
        "Le cours dépend fortement des prix du pétrole et du gaz, très variables.",
        "L'action est cotée à la Bourse de Paris.",
        "Le dividende est versé en euros.",
      ], correct: 1, tag: "Un risque propre à l'entreprise",
      good: "Les prix du pétrole et du gaz",
      explain: "La fiche le souligne&nbsp;: le cours suit les prix de l'énergie, parfois brutaux. C'est un risque propre au secteur et à l'entreprise, qui s'ajoute au risque général de la bourse.",
      fact: { label: "Risque propre à l'entreprise", value: "Forte dépendance aux prix du pétrole et du gaz", src: "fiche" },
      ask: "Comment le cours de TotalEnergies a-t-il réagi aux dernières variations du prix du pétrole&nbsp;?" },
    { id: "o2", axis: "Revenus", type: "tf",
      prompt: "TotalEnergies verse un dividende élevé. Ce revenu est donc garanti pour les années à venir.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "Le premier acompte 2026 est en hausse (0,90&nbsp;€ par action, +5,9&nbsp;%), mais un dividende n'est jamais garanti&nbsp;: il est décidé par la société et ses actionnaires, et peut baisser si les résultats reculent.",
      fact: { label: "Premier acompte sur dividende 2026", value: "0,90&nbsp;€ par action, payé le 2 oct. 2026", src: "tte" },
      ask: "Quels dividendes TotalEnergies a-t-elle versés ces dernières années, et ont-ils déjà baissé&nbsp;?" },
    { id: "o3", axis: "Coûts", type: "choice",
      prompt: "Vous achetez pour 10&nbsp;000&nbsp;€ d'actions TotalEnergies. En plus des frais de votre courtier, la taxe sur les transactions financières représente&nbsp;:",
      options: ["Rien", "4&nbsp;€", "40&nbsp;€", "400&nbsp;€"], correct: 2,
      good: "40&nbsp;€",
      explain: "TotalEnergies figure sur la liste des sociétés françaises de plus d'un milliard d'euros soumises à la taxe en 2026. Son taux est de 0,4&nbsp;% depuis le 1er avril 2025&nbsp;: 40&nbsp;€ pour 10&nbsp;000&nbsp;€ achetés.",
      fact: { label: "Taxe sur les transactions financières", value: "0,4&nbsp;%, TotalEnergies concernée en 2026", src: "bofip", note: "Liste des sociétés concernées&nbsp;: BOFiP du 17 décembre 2025." },
      ask: "Quels frais me prélevez-vous à chaque achat et à chaque vente d'actions, taxe comprise&nbsp;?" },
    { id: "o4", axis: "Enveloppe", type: "tf",
      prompt: "Une action TotalEnergies peut être logée dans un PEA.",
      options: ["Vrai", "Faux"], correct: 0,
      good: "Vrai",
      explain: "TotalEnergies est une société européenne&nbsp;: ses actions sont éligibles au PEA, qui accueille les titres de sociétés établies dans l'Union européenne ou l'Espace économique européen.",
      fact: { label: "Éligibilité au PEA", value: "Oui, société établie dans l'Union européenne", src: "sp" },
      ask: "Quels sont les frais de mon PEA, et comment les dividendes y sont-ils traités&nbsp;?" },
    { id: "o5", axis: "Risque", type: "slider",
      min: 0, max: 30, step: 0.5, start: 20, unit: "%", target: 8.18, tol: [1.5, 4], dec: 1, gapUnit: "point",
      real: "8,18&nbsp;%", realLabel: "Réalité (reporting Amundi CAC 40, au 31 août 2026)",
      prompt: "Vous détenez peut-être déjà un ETF CAC 40. Selon vous, quelle part de cet ETF est investie dans TotalEnergies&nbsp;?",
      good: "8,18&nbsp;%",
      explain: "TotalEnergies est la deuxième ligne de l'ETF Amundi CAC 40, derrière Schneider Electric. Avec cet ETF et des actions TotalEnergies en direct, vous êtes exposé deux fois à la même entreprise.",
      fact: { label: "Poids de TotalEnergies dans l'ETF Amundi CAC 40", value: "8,18&nbsp;%", src: "cac" },
      ask: "Quelle est ma vraie exposition à TotalEnergies, en comptant mes fonds&nbsp;?" },
    { id: "o6", axis: "Nature", type: "choice",
      prompt: "Où l'action TotalEnergies est-elle cotée&nbsp;?",
      options: ["À Paris seulement", "À Paris et à New York", "À Londres", "À Francfort"], correct: 1,
      good: "À Paris et à New York",
      explain: "Le calendrier de dividende de TotalEnergies distingue deux places&nbsp;: Euronext (Paris) et le NYSE (New York). Même entreprise, deux cotations&nbsp;: le premier acompte 2026 est payé le 2 octobre à Paris, et le 21 octobre à New York.",
      fact: { label: "Places de cotation", value: "Euronext Paris et NYSE", src: "tte" },
      ask: "Sur quelle place mon ordre est-il exécuté, et dans quelle devise&nbsp;?" },
    { id: "o7", axis: "Revenus", type: "choice",
      prompt: "L'acompte de 0,90&nbsp;€ a été détaché le 30 septembre 2026 et payé le 2 octobre. Vous achetez l'action le 1er octobre. Touchez-vous cet acompte&nbsp;?",
      options: ["Oui", "Non&nbsp;: il fallait détenir l'action avant le 30 septembre, date de détachement", "Oui, mais seulement la moitié"], correct: 1,
      good: "Non",
      explain: "La date de détachement décide qui touche le dividende. À partir de ce jour, l'action s'échange sans ce dividende&nbsp;: un acheteur du 1er octobre ne le reçoit pas, même s'il est payé le lendemain.",
      fact: { label: "Calendrier du premier acompte 2026", value: "Détachement le 30 sept., paiement le 2 oct. 2026 (Euronext)", src: "tte" },
      ask: "Quelles sont les prochaines dates de détachement du dividende&nbsp;?" },
  ],
  notes: [
    "La fiche du Décodeur indique un dividende 2026 « estimé à environ 3,60 € par action, soit un rendement de l'ordre de 4,5 % à 5 % » : c'est une estimation (une forme de prévision), sans source. Le seul chiffre vérifié : premier acompte 2026 de 0,90 € (communiqué du 29 avril 2026).",
  ],
};

export const ACTIONS_BANKS: Bank[] = [apple, lvmh, totalenergies];
