import type { Bank, ChoiceQuestion, Source } from "../types";
import { FICHE, SP_PEA, ISHARES_SP500_FS, ISHARES_WORLD_FS } from "../sources";

// ---------- Questions communes, paramétrées avec les chiffres de chaque DIC ----------

const DIC_REFRESH = "Revu à chaque nouvelle version du DIC";

function tension(
  id: string,
  axis: string,
  src: string,
  montant: string,
  devise: string,
  pct: string,
  extra?: string
): ChoiceQuestion {
  return {
    id, axis, type: "choice",
    prompt: `Le DIC présente un «&nbsp;scénario de tension&nbsp;»&nbsp;: 10&nbsp;000 ${devise} investis deviendraient ${montant} ${devise} au bout d'un an. Ce chiffre, c'est&nbsp;:`,
    options: [
      "La perte maximale possible&nbsp;: on ne peut pas descendre plus bas",
      "Une prévision de l'émetteur pour l'année prochaine",
      "Une illustration de ce qui pourrait arriver dans des marchés extrêmes, sans plancher garanti",
      "La pire année réellement connue par le fonds",
    ],
    correct: 2,
    good: "Une illustration, sans plancher",
    explain: "C'est une illustration calculée pour des situations de marché extrêmes. Ce n'est pas un plancher&nbsp;: le DIC précise qu'il n'existe aucun rendement minimum garanti et qu'on peut perdre tout ou partie de sa mise. Ce n'est pas non plus une prévision, ni le résultat d'une année passée.",
    extra,
    fact: { label: "Scénario de tension à 1 an", value: `${montant} ${devise} pour 10&nbsp;000 ${devise} investis (${pct})`, src },
    ask: "Dans le scénario de tension du DIC, que représenterait la baisse sur le montant que j'ai moi-même investi&nbsp;?",
  };
}

function horizon(id: string, axis: string, src: string): ChoiceQuestion {
  return {
    id, axis, type: "choice",
    prompt: "Quelle est la période de détention recommandée indiquée pour ce fonds&nbsp;?",
    options: ["1 an", "3 ans", "5 ans", "10 ans"],
    correct: 2,
    good: "5 ans",
    explain: "C'est la durée sur laquelle l'émetteur a calculé l'indicateur de risque et les scénarios. Ce n'est pas une garantie&nbsp;: en sortant plus tôt, on peut récupérer moins que prévu.",
    fact: { label: "Période de détention recommandée", value: "5 ans", src },
    ask: "Si je dois récupérer cet argent avant 5 ans, comment ça se passe concrètement&nbsp;?",
  };
}

/** Frais courants traduits en euros sur 10 000 €. `opts` : quatre montants, `correct` : index du bon. */
function cost(
  id: string,
  axis: string,
  src: string,
  pct: string,
  euros: string,
  opts: string[],
  correct: number,
  extra?: string
): ChoiceQuestion {
  return {
    id, axis, type: "choice",
    prompt: `Les frais courants de ce fonds sont de ${pct}&nbsp;% par an. Sur 10&nbsp;000&nbsp;€ investis, cela représente environ&nbsp;:`,
    options: opts.map((o) => `${o} par an`),
    correct,
    good: `${euros} par an`,
    explain: `${pct}&nbsp;% de 10&nbsp;000&nbsp;€, cela fait ${euros}. Ces frais ne vous sont jamais facturés à part&nbsp;: ils sont prélevés directement dans la valeur du fonds, chaque année, que le fonds monte ou baisse.`,
    extra,
    fact: { label: "Frais courants du fonds", value: `${pct}&nbsp;% par an`, src },
    ask: "Combien me coûte au total cet ETF chaque année, frais du fonds, frais de courtage et droits de garde compris&nbsp;?",
  };
}

function changeUsd(id: string, axis: string, src: string, factValue: string, extra?: string): ChoiceQuestion {
  return {
    id, axis, type: "choice",
    prompt: "Imaginons&nbsp;: le dollar perd 10&nbsp;% face à l'euro, et les actions du fonds ne bougent pas. Votre part, comptée en euros&nbsp;:",
    options: ["Monte d'environ 10&nbsp;%", "Baisse d'environ 10&nbsp;%", "Ne bouge pas, puisque les actions n'ont pas bougé"],
    correct: 1,
    good: "Elle baisse d'environ 10&nbsp;%",
    explain: "Les actions valent le même nombre de dollars, mais chaque dollar vaut moins d'euros une fois converti. C'est le risque de change&nbsp;: le DIC le signale, et la note de risque de 1 à 7 ne l'intègre pas. Si le dollar monte, l'effet joue dans l'autre sens.",
    extra,
    fact: { label: "Risque de change", value: factValue, src },
    ask: "Comment les variations du dollar face à l'euro se répercutent-elles sur la valeur de mes parts&nbsp;?",
  };
}

function peaUs(id: string, axis: string): ChoiceQuestion {
  return {
    id, axis, type: "choice",
    prompt: "Peut-on loger ce fonds dans un PEA (plan d'épargne en actions)&nbsp;?",
    options: [
      "Oui, comme n'importe quel ETF",
      "Non&nbsp;: il investit en actions américaines, alors que le PEA est réservé aux actions européennes et aux fonds investis à plus de 75&nbsp;% en actions européennes",
      "Oui, mais seulement au bout de 5 ans",
    ],
    correct: 1,
    good: "Non",
    explain: "Le PEA accueille les actions de sociétés de l'Union européenne ou de l'Espace économique européen, et les fonds investis à plus de 75&nbsp;% dans ces actions. Les actions américaines ne sont pas éligibles. Ce fonds se loge donc dans un compte-titres, ou dans une assurance-vie si le contrat le propose.",
    fact: { label: "Éligibilité au PEA", value: "Actions de sociétés américaines non éligibles au PEA", src: "sp" },
    ask: "Dans quelle enveloppe puis-je détenir ce fonds, et avec quels frais&nbsp;?",
  };
}

function dic(issuer: string, part: string, date: string, url: string): Source {
  return { name: `${issuer}, DIC du fonds (${part})`, date, url, refresh: DIC_REFRESH };
}

// ---------- Les 15 ETF du Décodeur ----------

export const world: Bank = {
  id: "world",
  name: "iShares Core MSCI World UCITS ETF",
  sub: "IE00B4L5Y983",
  short: "iShares Core MSCI World",
  family: "ETF et indices",
  share: "Mon ETF World, je le comprends",
  axes: ["Nature", "Coûts", "Risque", "Concentration", "Horizon"],
  src: {
    dic: dic("BlackRock", "part USD capitalisante", "3 sept. 2026", "https://www.blackrock.com/fr/particuliers/literature/kiid/eu-priips-ishares-core-msci-world-ucits-etf-ie00b4l5y983-fr.pdf"),
    msci: { name: "MSCI, fiche de l'indice MSCI World", date: "30 sept. 2026", url: "https://www.msci.com/documents/10199/255599/msci-world-index.pdf", refresh: "Revu à chaque nouvelle fiche de l'indice", watch: true },
    ish: { name: "iShares, page du fonds", date: "2 oct. 2026", url: "https://www.ishares.com/uk/individual/en/products/251882/ishares-msci-world-ucits-etf-acc-fund", refresh: "Revu à chaque mise à jour de la page" },
    fs: ISHARES_WORLD_FS,
  },
  questions: [
    { id: "q1", axis: "Concentration", type: "slider",
      min: 0, max: 100, step: 1, start: 50, unit: "%", target: 72.94, tol: [8, 15], dec: 1, gapUnit: "point",
      real: "72,94&nbsp;%", realLabel: "Réalité (indice MSCI World, au 30 sept. 2026)",
      prompt: "Ce fonds s'appelle «&nbsp;World&nbsp;». À votre avis, quelle part de son indice est investie dans des entreprises américaines&nbsp;?",
      good: "72,94&nbsp;% aux États-Unis",
      explain: "Près de trois euros sur quatre suivent des entreprises américaines. Le Japon pèse 5,91&nbsp;%, le Royaume-Uni 3,41&nbsp;%, la France 2,24&nbsp;%. La raison est mécanique&nbsp;: l'indice pondère chaque entreprise selon sa valeur en bourse, et les plus grosses sont américaines.",
      extra: "Le fonds détient 1&nbsp;250 lignes (iShares, au 2 octobre 2026), mais ses 10 premières pèsent à elles seules 26,47&nbsp;% (fiche iShares, au 31 août 2026).",
      fact: { label: "Part des États-Unis dans l'indice MSCI World", value: "72,94&nbsp;%", src: "msci", note: "Chiffre de l'indice que le fonds réplique. La composition exacte du fonds peut en différer légèrement." },
      ask: "Quelle part de mon épargne totale est exposée aux États-Unis, tous placements confondus&nbsp;?" },
    { id: "q2", axis: "Coûts", type: "choice",
      prompt: "Les frais courants de ce fonds sont de 0,20&nbsp;% par an. Sur 10&nbsp;000&nbsp;€ investis, cela représente environ&nbsp;:",
      options: ["2&nbsp;€ par an", "20&nbsp;€ par an", "200&nbsp;€ par an", "2&nbsp;000&nbsp;€ par an"], correct: 1,
      good: "20&nbsp;€ par an",
      explain: "0,20&nbsp;%, c'est 20 centimes pour 100&nbsp;€, donc 20&nbsp;€ pour 10&nbsp;000&nbsp;€. Le DIC donne le même ordre de grandeur&nbsp;: 20 USD de coûts la première année pour 10&nbsp;000 USD investis. Ces frais ne vous sont jamais facturés à part&nbsp;: ils sont prélevés directement dans la valeur du fonds.",
      fact: { label: "Frais de gestion et autres frais administratifs", value: "0,20&nbsp;% par an", src: "dic" },
      ask: "Combien me coûte au total cet ETF chaque année, frais du fonds, frais de courtage et droits de garde compris&nbsp;?" },
    { id: "q3", axis: "Nature", type: "choice",
      prompt: "Les entreprises détenues par le fonds versent des dividendes. Qu'est-ce qui vous en revient&nbsp;?",
      options: ["Ils arrivent sur votre compte chaque trimestre", "Ils sont réinvestis automatiquement dans le fonds", "Ils restent chez BlackRock, la société de gestion", "Rien, ces entreprises ne versent pas de dividendes"], correct: 1,
      good: "Ils sont réinvestis dans le fonds",
      explain: "Votre part est dite «&nbsp;capitalisante&nbsp;» (Acc, pour <i>accumulating</i>)&nbsp;: le DIC précise que les revenus sont inclus dans la valeur des parts. Vous ne recevez rien sur votre compte, mais la valeur de chaque part en tient compte.",
      fact: { label: "Traitement des revenus", value: "Capitalisation&nbsp;: revenus inclus dans la valeur des parts", src: "dic" },
      ask: "Comment les revenus de ce fonds sont-ils traités dans l'enveloppe où je le détiens&nbsp;?" },
    { id: "q4", axis: "Risque", type: "doc",
      doc: { title: "Document d'informations clés", sub: "Extrait reformulé · DIC daté du 3 septembre 2026", section: "Quels sont les risques et qu'est-ce que cela pourrait me rapporter&nbsp;?", foot: "Reformulation fidèle de la section «&nbsp;Indicateur de risque&nbsp;» du DIC." },
      prompt: "Voici un extrait reformulé du DIC. Touchez la phrase qui signale un risque que la note de 1 à 7 ne prend pas en compte.",
      sentences: [
        "Le produit est classé dans la classe de risque 4 sur une échelle allant de 1 à 7, ce qui correspond à un risque moyen.",
        "Ce classement n'est pas une garantie et peut évoluer avec le temps.",
        "Les parts sont libellées en dollar américain&nbsp;: votre gain final dépendra aussi du taux de change, un risque que l'indicateur ci-dessus ne prend pas en compte.",
        "L'indicateur suppose que vous conservez le produit pendant 5 ans. Le risque réel peut être différent si vous sortez plus tôt.",
      ], correct: 2, tag: "Le risque oublié par la note",
      good: "Le risque de change",
      explain: "Le fonds est en dollar américain. Si le dollar baisse face à l'euro, vos parts valent moins en euros, même si les actions n'ont pas bougé, et inversement. Le DIC le signale, mais la note de 4 sur 7 ne l'intègre pas.",
      fact: { label: "Indicateur synthétique de risque", value: "4 sur 7, hors risque de change", src: "dic" },
      ask: "Comment les variations du dollar face à l'euro se répercutent-elles sur la valeur de mes parts&nbsp;?" },
    { id: "q5", axis: "Coûts", type: "tf",
      prompt: "Le DIC indique qu'aucun frais d'entrée n'est demandé. Donc acheter cet ETF ne vous coûte rien au moment de l'achat.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "Le «&nbsp;pas de frais d'entrée&nbsp;» concerne le fonds lui-même. Un renvoi du DIC précise que cela ne s'applique pas à ceux qui achètent en bourse&nbsp;: votre courtier prélève ses propres frais, qui dépendent de lui et non du fonds.",
      fact: { label: "Frais d'entrée et de sortie du fonds", value: "Aucun côté fonds, frais du courtier en plus", src: "dic" },
      ask: "Quels frais prélevez-vous à chaque achat et à chaque vente de cet ETF&nbsp;?" },
    { id: "q6", axis: "Risque", type: "choice",
      prompt: "Le DIC présente un «&nbsp;scénario de tension&nbsp;»&nbsp;: 10&nbsp;000 USD investis deviendraient 7&nbsp;490 USD au bout d'un an. Ce chiffre, c'est&nbsp;:",
      options: ["La perte maximale possible&nbsp;: on ne peut pas descendre plus bas", "Une prévision de BlackRock pour l'année prochaine", "Une illustration de ce qui pourrait arriver dans des marchés extrêmes, sans plancher garanti", "Le résultat réel du fonds en 2022"], correct: 2,
      good: "Une illustration, sans plancher",
      explain: "C'est une illustration calculée pour des situations de marché extrêmes. Ce n'est pas un plancher&nbsp;: le DIC précise qu'il n'existe aucun rendement minimum garanti et qu'on peut perdre tout ou partie de sa mise. Ce n'est pas une prévision non plus. Et ce n'est pas 2022&nbsp;: cette année-là, la part a fait −18,03&nbsp;% en dollars (fiche iShares au 31 août 2026). Les performances passées ne préjugent pas des performances futures.",
      fact: { label: "Scénario de tension à 1 an", value: "7&nbsp;490 USD pour 10&nbsp;000 USD investis (−25,1&nbsp;%)", src: "dic" },
      ask: "Dans le scénario de tension du DIC, que représenterait la baisse sur le montant que j'ai moi-même investi&nbsp;?" },
    { id: "q7", axis: "Horizon", type: "choice",
      prompt: "Quelle est la période de détention recommandée indiquée dans le DIC&nbsp;?",
      options: ["1 an", "3 ans", "5 ans", "10 ans"], correct: 2,
      good: "5 ans",
      explain: "C'est la durée sur laquelle l'émetteur a calculé l'indicateur de risque et les scénarios. Le DIC rappelle que c'est une estimation, pas une garantie, et qu'en sortant plus tôt on peut récupérer moins.",
      fact: { label: "Période de détention recommandée", value: "5 ans", src: "dic" },
      ask: "Si je dois récupérer cet argent avant 5 ans, comment ça se passe concrètement&nbsp;?" },
  ],
  notes: ["Version validée le 6 octobre 2026, reprise à l'identique."],
};

export const sp500: Bank = {
  id: "sp500",
  name: "iShares Core S&P 500 UCITS ETF",
  sub: "IE00B5BMR087",
  short: "iShares Core S&P 500",
  family: "ETF et indices",
  share: "Mon ETF S&P 500, je le comprends",
  axes: ["Nature", "Coûts", "Risque", "Concentration", "Enveloppe"],
  src: {
    dic: dic("BlackRock", "part USD capitalisante", "3 sept. 2026", "https://www.blackrock.com/fr/intermediaries/literature/kiid/eu-priips-ishares-core-sp-500-ucits-etf-usd-acc-ie00b5bmr087-fr.pdf"),
    fs: ISHARES_SP500_FS,
    ish: { name: "iShares, page du fonds", date: "5 oct. 2026", url: "https://www.ishares.com/uk/individual/en/products/253743/ishares-sp-500-b-ucits-etf-acc-fund", refresh: "Revu à chaque mise à jour de la page", watch: true },
    sp: SP_PEA,
  },
  questions: [
    { id: "s1", axis: "Concentration", type: "slider",
      min: 0, max: 100, step: 1, start: 15, unit: "%", target: 37.75, tol: [5, 12], dec: 1, gapUnit: "point",
      real: "37,75&nbsp;%", realLabel: "Réalité (fiche iShares, au 31 août 2026)",
      prompt: "Le fonds détient environ 500 entreprises. Selon vous, quelle part du fonds représentent ses 10 premières lignes&nbsp;?",
      good: "37,75&nbsp;%",
      explain: "Plus d'un euro sur trois repose sur dix entreprises. Nvidia, Apple et Microsoft pèsent à elles seules plus de 20&nbsp;%. L'indice pondère chaque entreprise selon sa valeur en bourse&nbsp;: les plus grosses prennent beaucoup de place.",
      fact: { label: "Poids des 10 premières lignes", value: "37,75&nbsp;%", src: "fs" },
      ask: "Quelle part de mon épargne repose, au total, sur les dix plus grandes entreprises américaines&nbsp;?" },
    cost("s2", "Coûts", "dic", "0,07", "7&nbsp;€", ["0,70&nbsp;€", "7&nbsp;€", "70&nbsp;€", "700&nbsp;€"], 1,
      "C'est l'un des ETF les moins chers du Décodeur. Le DIC indique aussi des coûts de transaction de 0,00&nbsp;%."),
    { id: "s3", axis: "Nature", type: "choice",
      prompt: "Le S&P 500 réunit 500 entreprises. Le fonds détient pourtant 505 lignes. Pourquoi&nbsp;?",
      options: ["Le gérant ajoute cinq entreprises de son choix", "Certaines entreprises y figurent avec deux catégories d'actions, comme Alphabet", "Le fonds détient aussi cinq obligations", "C'est une erreur de la fiche"], correct: 1,
      good: "Deux catégories d'actions pour certaines entreprises",
      explain: "Une même entreprise peut avoir plusieurs catégories d'actions cotées. Alphabet (Google) apparaît ainsi deux fois parmi les dix premières lignes du fonds, avec ses actions de classe A et de classe C. Le fonds ne choisit pas&nbsp;: il réplique l'indice.",
      fact: { label: "Nombre de lignes du fonds", value: "505", src: "ish" },
      ask: "Ce fonds réplique-t-il l'indice en détenant toutes ses actions&nbsp;?" },
    { id: "s4", axis: "Concentration", type: "choice",
      prompt: "Quel secteur pèse le plus dans le fonds&nbsp;?",
      options: ["La santé", "Les technologies de l'information", "La finance", "L'énergie"], correct: 1,
      good: "Les technologies de l'information, près de 40&nbsp;%",
      explain: "Les technologies de l'information représentent 39,98&nbsp;% du fonds, loin devant la finance (11,29&nbsp;%). Un fonds de 500 entreprises peut donc rester très dépendant d'un seul secteur.",
      fact: { label: "Poids du secteur technologique", value: "39,98&nbsp;% (au 2 oct. 2026)", src: "ish" },
      ask: "Quelle part de mon épargne totale dépend du secteur technologique&nbsp;?" },
    peaUs("s5", "Enveloppe"),
    tension("s6", "Risque", "dic", "7&nbsp;040", "USD", "−29,6&nbsp;%"),
    changeUsd("s7", "Risque", "dic", "Part en dollars&nbsp;: le DIC signale le risque de change"),
  ],
  notes: [
    "La fiche du Décodeur indique un secteur technologique « environ 38 % » : il est de 39,98 % au 2 octobre 2026 (iShares). À mettre à jour.",
  ],
};

export const nasdaq: Bank = {
  id: "nasdaq",
  name: "Amundi Nasdaq-100 Swap UCITS ETF EUR Acc",
  sub: "LU1681038243",
  short: "Amundi Nasdaq-100",
  family: "ETF et indices",
  share: "Mon ETF Nasdaq-100, je le comprends",
  axes: ["Nature", "Coûts", "Risque", "Concentration", "Enveloppe"],
  src: {
    fs: { name: "Amundi, reporting mensuel du fonds", date: "30 sept. 2026", url: "https://www.amundietf.fr/pdfDocuments/monthly-factsheet/LU1681038243/FRA/FRA/INSTITUTIONNEL/ETF", refresh: "Revu à chaque nouveau reporting", watch: true },
    pea: { name: "Amundi, reporting de l'ETF Amundi PEA Nasdaq-100", date: "31 août 2026", url: "https://www.amundietf.fr/pdfDocuments/monthly-factsheet/FR0011871110/FRA/FRA/RETAIL/ETF", refresh: "Revu à chaque nouveau reporting" },
    world: { name: "BlackRock, DIC de l'ETF iShares Core MSCI World", date: "3 sept. 2026", url: "https://www.blackrock.com/fr/particuliers/literature/kiid/eu-priips-ishares-core-msci-world-ucits-etf-ie00b4l5y983-fr.pdf", refresh: DIC_REFRESH },
  },
  questions: [
    { id: "n1", axis: "Concentration", type: "slider",
      min: 0, max: 100, step: 1, start: 30, unit: "%", target: 59.65, tol: [5, 12], dec: 1, gapUnit: "point",
      real: "59,65&nbsp;%", realLabel: "Réalité (reporting Amundi, au 30 sept. 2026)",
      prompt: "Quelle part du fonds est investie dans le secteur technologique&nbsp;?",
      good: "59,65&nbsp;%",
      explain: "Six euros sur dix sont placés dans la technologie. Le Nasdaq-100 réunit une centaine de très grandes entreprises, mais le fonds reste un pari concentré sur un secteur, pas une exposition large au marché américain.",
      fact: { label: "Poids du secteur technologique", value: "59,65&nbsp;%", src: "fs" },
      ask: "Quelle part de mon épargne totale dépend du secteur technologique&nbsp;?" },
    { id: "n2", axis: "Nature", type: "choice",
      prompt: "Ce fonds réplique le Nasdaq-100 de façon «&nbsp;synthétique&nbsp;». Cela veut dire&nbsp;:",
      options: ["Il détient exactement les 100 actions de l'indice", "Il obtient la performance de l'indice grâce à un contrat d'échange (swap) avec une banque, sans forcément détenir ces actions", "Il investit dans des cryptomonnaies", "Il ne suit pas vraiment l'indice"], correct: 1,
      good: "Un contrat d'échange avec une banque",
      explain: "Le fonds détient un panier de titres et échange sa performance contre celle du Nasdaq-100 auprès d'une banque, par un contrat appelé swap. Si cette banque ne tenait pas ses engagements, le fonds pourrait subir une perte&nbsp;: c'est le risque de contrepartie, encadré par la réglementation européenne.",
      fact: { label: "Méthode de réplication", value: "Indirecte, par contrat d'échange sur rendement total (swap)", src: "fs" },
      ask: "Avec quelle banque le fonds a-t-il conclu son contrat d'échange, et quelle part de l'actif cela représente-t-il&nbsp;?" },
    { id: "n3", axis: "Concentration", type: "choice",
      prompt: "Le fonds suit 101 valeurs. Ensemble, ses 10 premières lignes pèsent environ&nbsp;:",
      options: ["10&nbsp;%", "25&nbsp;%", "Près de la moitié du fonds", "90&nbsp;%"], correct: 2,
      good: "Près de la moitié, 46,73&nbsp;%",
      explain: "Nvidia (8,34&nbsp;%), Apple (7,32&nbsp;%) et Microsoft (5,75&nbsp;%) ouvrent la liste. À elles dix, les premières lignes pèsent 46,73&nbsp;%&nbsp;: le sort du fonds dépend beaucoup de quelques géants.",
      fact: { label: "Poids des 10 premières lignes", value: "46,73&nbsp;%", src: "fs" },
      ask: "Si je détiens aussi un ETF S&P 500 ou World, combien de fois suis-je exposé aux mêmes géants&nbsp;?" },
    cost("n4", "Coûts", "fs", "0,23", "23&nbsp;€", ["2,30&nbsp;€", "23&nbsp;€", "230&nbsp;€", "2&nbsp;300&nbsp;€"], 1),
    { id: "n5", axis: "Enveloppe", type: "choice",
      prompt: "Ce fonds-ci (LU1681038243) peut-il être logé dans un PEA&nbsp;?",
      options: ["Oui", "Non&nbsp;: il se détient en compte-titres ou en assurance-vie", "Oui, mais seulement après 5 ans"], correct: 1,
      good: "Non",
      explain: "Le reporting d'Amundi l'indique&nbsp;: ce fonds n'est pas éligible au PEA. Amundi propose une autre version, Amundi PEA Nasdaq-100 (FR0011871110), qui l'est&nbsp;: elle investit au moins 75&nbsp;% de ses actifs en actions de sociétés européennes et échange leur performance contre celle du Nasdaq-100. C'est un autre produit, avec d'autres frais (0,30&nbsp;% par an).",
      fact: { label: "Éligibilité au PEA", value: "Non éligible (compte-titres, assurance-vie)", src: "fs" },
      ask: "Dans quelle enveloppe ce fonds est-il le plus adapté à ma situation, et quelles versions existent&nbsp;?" },
    { id: "n6", axis: "Risque", type: "tf",
      prompt: "La part est libellée en euros. Elle vous met donc à l'abri des variations du dollar.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "La devise de la part dit seulement dans quelle monnaie elle s'achète. Les entreprises du Nasdaq-100 sont américaines et cotées en dollars&nbsp;: si le dollar baisse face à l'euro, la part baisse aussi. Rien dans son nom n'indique une couverture de change (la mention «&nbsp;Hedged&nbsp;»).",
      fact: { label: "Devise de la part", value: "Euro, sans mention de couverture de change", src: "fs" },
      ask: "Cette part est-elle couverte contre le risque de change&nbsp;?" },
    { id: "n7", axis: "Risque", type: "choice",
      prompt: "Le reporting classe ce fonds 5 sur une échelle de risque de 1 à 7. Un ETF MSCI World est classé 4. Ce que ça signifie&nbsp;:",
      options: ["Selon cet indicateur, le Nasdaq-100 est plus risqué", "Il est moins risqué", "Ils sont aussi risqués l'un que l'autre", "Cela ne veut rien dire"], correct: 0,
      good: "Plus risqué selon cet indicateur",
      explain: "Plus la note est haute, plus la valeur du placement peut varier fortement, à la hausse comme à la baisse. La concentration sur un secteur et sur quelques entreprises explique en partie l'écart. La note n'est pas une garantie et peut évoluer.",
      fact: { label: "Indicateur de risque", value: "5 sur 7 (MSCI World&nbsp;: 4 sur 7)", src: "fs" },
      ask: "Comment ce fonds s'est-il comporté lors des fortes baisses du secteur technologique&nbsp;?" },
  ],
  notes: [
    "Le nom exact du fonds est désormais « Amundi Nasdaq-100 Swap UCITS ETF EUR Acc » (reporting au 30 sept. 2026) : la fiche du Décodeur indique « Amundi Nasdaq-100 UCITS ETF ».",
  ],
};

export const em: Bank = {
  id: "em",
  name: "iShares Core MSCI EM IMI UCITS ETF",
  sub: "IE00BKM4GZ66",
  short: "iShares Core MSCI EM IMI",
  family: "ETF et indices",
  share: "Mon ETF pays émergents, je le comprends",
  axes: ["Nature", "Coûts", "Risque", "Concentration", "Horizon"],
  src: {
    dic: dic("BlackRock", "part USD capitalisante", "3 sept. 2026", "https://www.blackrock.com/fr/particuliers/literature/kiid/eu-priips-ishares-core-msci-em-imi-ucits-etf-usd-acc-ie00bkm4gz66-fr.pdf"),
    msci: { name: "MSCI, fiche de l'indice MSCI Emerging Markets IMI", date: "30 sept. 2026", url: "https://www.msci.com/documents/10199/255599/msci-emerging-markets-imi-usd-gross.pdf", refresh: "Revu à chaque nouvelle fiche de l'indice", watch: true },
    fiche: FICHE,
  },
  questions: [
    { id: "e1", axis: "Concentration", type: "choice",
      prompt: "Quel pays pèse le plus dans l'indice de ce fonds&nbsp;?",
      options: ["La Chine", "L'Inde", "Taïwan", "Le Brésil"], correct: 2,
      good: "Taïwan, 28,8&nbsp;%",
      explain: "Taïwan arrive en tête avec 28,8&nbsp;%, devant la Corée du Sud (20,65&nbsp;%), la Chine (18,51&nbsp;%) et l'Inde (11,87&nbsp;%). Ces quatre pays pèsent ensemble près de 80&nbsp;% de l'indice.",
      fact: { label: "Premier pays de l'indice", value: "Taïwan, 28,8&nbsp;%", src: "msci" },
      ask: "Quelle part de mon épargne est exposée à un seul pays émergent&nbsp;?" },
    { id: "e2", axis: "Concentration", type: "slider",
      min: 0, max: 40, step: 0.5, start: 30, unit: "%", target: 13.76, tol: [2, 5], dec: 1, gapUnit: "point", fem: false,
      real: "13,76&nbsp;%", realLabel: "Réalité (indice MSCI EM IMI, au 30 sept. 2026)",
      prompt: "L'indice compte près de 3&nbsp;000 entreprises. Selon vous, combien pèse à elle seule la première, le fabricant taïwanais de puces TSMC&nbsp;?",
      good: "13,76&nbsp;%",
      explain: "Une seule entreprise pèse près d'un septième de l'indice. Samsung Electronics suit avec 6,65&nbsp;%, puis SK Hynix avec 5,19&nbsp;%&nbsp;: trois fabricants de composants électroniques réunissent plus d'un quart de l'ensemble.",
      fact: { label: "Poids de TSMC dans l'indice", value: "13,76&nbsp;%", src: "msci" },
      ask: "Combien de fois suis-je exposé à TSMC si je détiens aussi un ETF mondial&nbsp;?" },
    { id: "e3", axis: "Nature", type: "choice",
      prompt: "«&nbsp;IMI&nbsp;», dans le nom de l'indice, signifie qu'il inclut&nbsp;:",
      options: ["Les grandes, les moyennes et aussi les petites entreprises", "Uniquement des entreprises chinoises", "Des obligations en plus des actions", "Des matières premières"], correct: 0,
      good: "Les petites entreprises aussi",
      explain: "IMI veut dire <i>Investable Market Index</i>. L'indice couvre les grandes, moyennes et petites capitalisations de 24 pays émergents, soit environ 99&nbsp;% de la valeur en bourse disponible dans chacun.",
      fact: { label: "Couverture de l'indice", value: "Grandes, moyennes et petites entreprises de 24 pays émergents", src: "msci" },
      ask: "Quelle différence entre ce fonds et un ETF MSCI Emerging Markets sans « IMI »&nbsp;?" },
    { id: "e4", axis: "Coûts", type: "choice",
      prompt: "Le DIC indique 0,18&nbsp;% de frais de gestion et 0,04&nbsp;% de coûts de transaction. Pour 10&nbsp;000 USD, les coûts totaux de la première année sont de&nbsp;:",
      options: ["4 USD", "18 USD", "22 USD", "220 USD"], correct: 2,
      good: "22 USD",
      explain: "Les frais de gestion (0,18&nbsp;%) ne sont pas les seuls coûts&nbsp;: acheter et vendre les actions de l'indice en coûte aussi (0,04&nbsp;%). Le DIC additionne les deux&nbsp;: 22 USD pour 10&nbsp;000 USD la première année.",
      fact: { label: "Coûts totaux à 1 an", value: "22 USD pour 10&nbsp;000 USD (0,18&nbsp;% + 0,04&nbsp;%)", src: "dic" },
      ask: "Quels coûts s'ajoutent aux frais de gestion affichés&nbsp;?" },
    tension("e5", "Risque", "dic", "6&nbsp;990", "USD", "−30,1&nbsp;%"),
    horizon("e6", "Horizon", "dic"),
    { id: "e7", axis: "Risque", type: "choice",
      prompt: "Le fonds est en dollars, mais ses entreprises sont cotées en dollars taïwanais, wons, yuans, roupies... Pour vous, épargnant en euros&nbsp;:",
      options: ["Un seul risque de change, celui du dollar", "Un risque de change sur plusieurs devises à la fois", "Aucun risque de change"], correct: 1,
      good: "Plusieurs devises à la fois",
      explain: "La valeur des actions dépend de leur monnaie locale, convertie ensuite en dollars puis en euros. Chaque devise peut monter ou baisser face à l'euro. Le DIC signale le risque de change&nbsp;; la fiche du Décodeur précise qu'il porte sur plusieurs devises.",
      fact: { label: "Risque de change", value: "Plusieurs devises émergentes, en plus du dollar", src: "fiche" },
      ask: "Comment les variations des monnaies émergentes ont-elles pesé sur ce fonds ces dernières années&nbsp;?" },
  ],
  notes: [
    "La fiche du Décodeur donne Chine 22 %, Inde 21 %, Taïwan 19 % : au 30 sept. 2026, l'indice compte Taïwan 28,8 %, Corée du Sud 20,65 %, Chine 18,51 %, Inde 11,87 % (MSCI). Les trois premiers pays ont changé. À mettre à jour.",
  ],
};

export const cac40: Bank = {
  id: "cac40",
  name: "Amundi CAC 40 UCITS ETF Dist",
  sub: "FR0007052782",
  short: "Amundi CAC 40",
  family: "ETF et indices",
  share: "Mon ETF CAC 40, je le comprends",
  axes: ["Concentration", "Nature", "Coûts", "Enveloppe", "Risque"],
  src: {
    dic: dic("Amundi", "Amundi CAC 40 UCITS ETF Dist", "5 juin 2026", "https://www.amundietf.fr/pdfDocuments/kid-priips/FR0007052782/FRA/FRA"),
    fs: { name: "Amundi, reporting mensuel du fonds", date: "31 août 2026", url: "https://www.amundietf.fr/pdfDocuments/monthly-factsheet/FR0007052782/FRA/FRA/RETAIL/ETF", refresh: "Revu à chaque nouveau reporting", watch: true },
  },
  questions: [
    { id: "c1", axis: "Concentration", type: "slider",
      min: 0, max: 100, step: 1, start: 25, unit: "%", target: 61.61, tol: [5, 12], dec: 1, gapUnit: "point",
      real: "61,61&nbsp;%", realLabel: "Réalité (reporting Amundi, au 31 août 2026)",
      prompt: "Le CAC 40 réunit 40 entreprises. Selon vous, quelle part du fonds représentent les 10 premières&nbsp;?",
      good: "61,61&nbsp;%",
      explain: "Dix entreprises sur quarante pèsent plus de 60&nbsp;% du fonds. Les trente autres se partagent le reste. Un ETF CAC 40 dépend donc fortement d'une poignée de grandes entreprises françaises.",
      fact: { label: "Poids des 10 premières lignes", value: "61,61&nbsp;%", src: "fs" },
      ask: "Quelle part de mon épargne repose sur ces dix entreprises, tous placements confondus&nbsp;?" },
    { id: "c2", axis: "Concentration", type: "choice",
      prompt: "Quelle entreprise est la première ligne du fonds&nbsp;?",
      options: ["LVMH", "TotalEnergies", "Schneider Electric", "L'Oréal"], correct: 2,
      good: "Schneider Electric, 9,30&nbsp;%",
      explain: "Schneider Electric arrive en tête (9,30&nbsp;%), devant TotalEnergies (8,18&nbsp;%) et Airbus (6,44&nbsp;%). LVMH est quatrième (6,12&nbsp;%). Le classement change avec les cours de bourse.",
      fact: { label: "Première ligne du fonds", value: "Schneider Electric, 9,30&nbsp;%", src: "fs" },
      ask: "Si je détiens aussi certaines de ces actions en direct, quelle est ma vraie exposition à chacune&nbsp;?" },
    { id: "c3", axis: "Nature", type: "choice",
      prompt: "Que deviennent les dividendes versés par les 40 entreprises&nbsp;?",
      options: ["Ils sont forcément réinvestis dans le fonds", "Ils peuvent être réinvestis ou distribués&nbsp;: c'est la société d'investissement du fonds qui décide", "Ils restent chez Amundi", "Ces entreprises n'en versent pas"], correct: 1,
      good: "Réinvestis ou distribués, selon la décision du fonds",
      explain: "Le DIC précise que les revenus et plus-values pourront être capitalisés ou distribués par décision de la SICAV. Le nom de la part se termine d'ailleurs par «&nbsp;Dist&nbsp;». Vérifiez ce qui a été fait ces dernières années&nbsp;: cela change ce que vous recevez et votre fiscalité.",
      fact: { label: "Affectation des revenus", value: "Capitalisation et/ou distribution, sur décision de la SICAV", src: "dic" },
      ask: "Ce fonds a-t-il versé des dividendes ces dernières années, et à quelles dates&nbsp;?" },
    cost("c4", "Coûts", "dic", "0,25", "25&nbsp;€", ["2,50&nbsp;€", "25&nbsp;€", "250&nbsp;€", "2&nbsp;500&nbsp;€"], 1,
      "Le DIC ajoute 0,03&nbsp;% de coûts de transaction par an."),
    { id: "c5", axis: "Enveloppe", type: "tf",
      prompt: "Cet ETF peut être logé dans un PEA.",
      options: ["Vrai", "Faux"], correct: 0,
      good: "Vrai",
      explain: "Le DIC l'indique&nbsp;: le fonds est éligible au PEA et investit donc au moins 75&nbsp;% de ses actifs en actions. Les gains réalisés dans un PEA bénéficient d'une fiscalité avantageuse après cinq ans, sous conditions.",
      fact: { label: "Éligibilité au PEA", value: "Oui, au moins 75&nbsp;% investis en actions", src: "dic" },
      ask: "Quels sont les frais de mon PEA lui-même, en plus de ceux du fonds&nbsp;?" },
    tension("c6", "Risque", "dic", "3&nbsp;530", "EUR", "−64,7&nbsp;%",
      "Ce scénario est particulièrement sévère dans le DIC de ce fonds. Il rappelle qu'un indice de 40 entreprises d'un seul pays peut subir de fortes baisses."),
    horizon("c7", "Risque", "dic"),
  ],
  notes: [
    "Le nom exact est « Amundi CAC 40 UCITS ETF Dist ». La fiche du Décodeur ne dit rien de la distribution possible des revenus.",
    "La fiche indique que les 3 premières lignes pèsent « près d'un quart » : 23,92 % au 31 août 2026 (9,30 + 8,18 + 6,44). Exact.",
  ],
};

export const acwi: Bank = {
  id: "acwi",
  name: "SPDR MSCI All Country World UCITS ETF (Acc)",
  sub: "IE00B44Z5B48",
  short: "SPDR MSCI ACWI",
  family: "ETF et indices",
  share: "Mon ETF ACWI, je le comprends",
  axes: ["Concentration", "Nature", "Coûts", "Revenus", "Risque"],
  src: {
    fs: { name: "State Street (SPDR), fiche du fonds en français", date: "31 juil. 2026", url: "https://www.ssga.com/library-content/products/factsheets/etfs/emea/factsheet-emea-fr-spyy-gy.pdf", refresh: "Revu à chaque nouvelle fiche", watch: true },
    msci: { name: "MSCI, fiche de l'indice MSCI ACWI", date: "30 sept. 2026", url: "https://www.msci.com/documents/10199/255599/msci-acwi.pdf", refresh: "Revu à chaque nouvelle fiche de l'indice", watch: true },
    fiche: FICHE,
  },
  questions: [
    { id: "a1", axis: "Concentration", type: "slider",
      min: 0, max: 100, step: 1, start: 35, unit: "%", target: 64.21, tol: [5, 12], dec: 1, gapUnit: "point",
      real: "64,21&nbsp;%", realLabel: "Réalité (indice MSCI ACWI, au 30 sept. 2026)",
      prompt: "ACWI veut dire «&nbsp;All Country World Index&nbsp;»&nbsp;: pays développés et émergents. Selon vous, quelle part de l'indice est investie aux États-Unis&nbsp;?",
      good: "64,21&nbsp;%",
      explain: "Même avec les pays émergents, près des deux tiers de l'indice sont américains. Le Japon suit avec 5,2&nbsp;%, Taïwan 3,46&nbsp;%, le Royaume-Uni 3&nbsp;%. Le poids de chaque pays dépend de la valeur en bourse de ses entreprises, pas de la taille de son économie.",
      fact: { label: "Part des États-Unis dans l'indice", value: "64,21&nbsp;%", src: "msci" },
      ask: "Quelle part de mon épargne totale est exposée aux États-Unis, tous placements confondus&nbsp;?" },
    { id: "a2", axis: "Nature", type: "choice",
      prompt: "Combien de pays couvre l'indice MSCI ACWI&nbsp;?",
      options: ["Les 23 pays développés seulement", "23 pays développés et 24 pays émergents", "Les 10 plus grandes économies", "Les États-Unis et l'Europe"], correct: 1,
      good: "23 pays développés et 24 émergents",
      explain: "L'indice couvre les grandes et moyennes entreprises de 47 pays. C'est ce qui le distingue du MSCI World, limité aux 23 pays développés. Mais nombre de pays et poids réel ne vont pas ensemble&nbsp;: les émergents restent minoritaires.",
      fact: { label: "Couverture de l'indice", value: "23 pays développés et 24 pays émergents", src: "msci" },
      ask: "Quelle part de ce fonds est réellement investie dans les pays émergents&nbsp;?" },
    { id: "a3", axis: "Nature", type: "choice",
      prompt: "La fiche indique 2&nbsp;418 titres dans l'indice, mais 2&nbsp;241 lignes détenues par le fonds. Pourquoi&nbsp;?",
      options: ["Le fonds a perdu des titres", "La réplication est «&nbsp;optimisée&nbsp;»&nbsp;: le fonds détient un échantillon représentatif plutôt que tous les titres", "Le gérant choisit les meilleures entreprises", "C'est une erreur de la fiche"], correct: 1,
      good: "Une réplication optimisée",
      explain: "Pour limiter les coûts, le fonds ne détient pas forcément chaque titre de l'indice, surtout les plus petits. Il choisit un échantillon qui doit reproduire au plus près la performance de l'ensemble. Ce n'est pas une sélection des «&nbsp;meilleures&nbsp;» entreprises.",
      fact: { label: "Méthode de réplication", value: "Optimisée (2&nbsp;241 lignes pour 2&nbsp;418 titres dans l'indice)", src: "fs" },
      ask: "Quel est l'écart de suivi de ce fonds par rapport à son indice&nbsp;?" },
    cost("a4", "Coûts", "fs", "0,12", "12&nbsp;€", ["1,20&nbsp;€", "12&nbsp;€", "120&nbsp;€", "1&nbsp;200&nbsp;€"], 1),
    { id: "a5", axis: "Revenus", type: "choice",
      prompt: "La fiche indique une politique de revenus «&nbsp;Accumulation&nbsp;». Que deviennent les dividendes&nbsp;?",
      options: ["Ils sont versés chaque trimestre", "Ils sont réinvestis dans le fonds", "Ils sont conservés par State Street", "Ils sont versés en fin de vie du fonds"], correct: 1,
      good: "Ils sont réinvestis",
      explain: "Accumulation, ou capitalisation&nbsp;: les dividendes perçus par le fonds ne vous sont pas versés, ils s'ajoutent à sa valeur. Le prix de la part en tient compte.",
      fact: { label: "Politique de revenus", value: "Accumulation (capitalisation)", src: "fs" },
      ask: "Comment ce fonds est-il imposé dans l'enveloppe où je le détiens&nbsp;?" },
    { id: "a6", axis: "Concentration", type: "choice",
      prompt: "Une seule entreprise non américaine figure parmi les dix premières lignes du fonds. Laquelle&nbsp;?",
      options: ["Nestlé", "Taiwan Semiconductor (TSMC)", "Toyota", "LVMH"], correct: 1,
      good: "TSMC, 1,79&nbsp;%",
      explain: "Le fabricant taïwanais de puces TSMC est sixième (1,79&nbsp;%). Les neuf autres premières lignes sont américaines&nbsp;: Nvidia, Apple, Microsoft, Amazon, Alphabet (deux fois), Broadcom, Meta et Micron. À elles dix, elles pèsent 28,26&nbsp;%.",
      fact: { label: "Dix premières lignes", value: "28,26&nbsp;% du fonds, dont 9 entreprises américaines", src: "fs" },
      ask: "Quelle est ma vraie exposition à ces dix entreprises, tous placements confondus&nbsp;?" },
    { id: "a7", axis: "Risque", type: "choice",
      prompt: "Le fonds est en dollars et détient des actions cotées en dollars, yens, livres, dollars taïwanais... Pour vous, en euros&nbsp;:",
      options: ["Un seul risque de change, celui du dollar", "Un risque de change sur plusieurs devises", "Aucun risque de change"], correct: 1,
      good: "Plusieurs devises",
      explain: "Chaque action vaut un certain montant dans sa propre monnaie. Converties en euros, ces valeurs montent ou baissent aussi avec les taux de change. Le dollar reste la devise dominante, puisque près des deux tiers du fonds sont américains.",
      fact: { label: "Risque de change", value: "Plusieurs devises, dollar en tête", src: "fiche" },
      ask: "Ce fonds existe-t-il dans une version couverte contre le risque de change&nbsp;?" },
  ],
  notes: [
    "La fiche du Décodeur indique environ 2 500 entreprises et 62 % aux États-Unis : l'indice compte 2 414 titres et 64,21 % aux États-Unis au 30 sept. 2026 (MSCI).",
    "Le DIC français de ce fonds n'a pas pu être lu (le site de State Street renvoyait vers un autre produit) : aucune question ne s'appuie sur la note de risque ni sur le scénario de tension.",
  ],
};

export const ftseallworld: Bank = {
  id: "ftseallworld",
  name: "Vanguard FTSE All-World UCITS ETF (USD) Accumulating",
  sub: "IE00BK5BQT80",
  short: "Vanguard FTSE All-World",
  family: "ETF et indices",
  share: "Mon ETF All-World, je le comprends",
  axes: ["Concentration", "Nature", "Coûts", "Risque", "Horizon"],
  src: {
    dic: dic("Vanguard", "part USD capitalisante", "28 juil. 2026", "https://fund-docs.vanguard.com/ie00bk5bqt80_priipskid_fr.pdf"),
    fs: { name: "Vanguard, fiche du fonds en français", date: "31 août 2026", url: "https://fund-docs.vanguard.com/FTSE_All-World_UCITS_ETF_USD_Accumulating_9679_FR_INT_FR.pdf", refresh: "Revu à chaque nouvelle fiche", watch: true },
  },
  questions: [
    { id: "f1", axis: "Concentration", type: "slider",
      min: 0, max: 100, step: 1, start: 35, unit: "%", target: 61.7, tol: [5, 12], dec: 1, gapUnit: "point",
      real: "61,7&nbsp;%", realLabel: "Réalité (fiche Vanguard, au 31 août 2026)",
      prompt: "Le fonds suit des milliers d'entreprises du monde entier. Selon vous, quelle part est investie aux États-Unis&nbsp;?",
      good: "61,7&nbsp;%",
      explain: "Plus de six euros sur dix sont américains. Le Japon, deuxième pays, ne pèse que 6&nbsp;%. «&nbsp;All-World&nbsp;» décrit le nombre de pays couverts, pas une répartition équilibrée entre eux.",
      fact: { label: "Part des États-Unis", value: "61,7&nbsp;%", src: "fs" },
      ask: "Quelle part de mon épargne totale est exposée aux États-Unis, tous placements confondus&nbsp;?" },
    { id: "f2", axis: "Nature", type: "choice",
      prompt: "L'indice compte 4&nbsp;263 actions, le fonds en détient 3&nbsp;784. Pourquoi&nbsp;?",
      options: ["Le gérant écarte les entreprises qu'il juge mauvaises", "Le fonds détient un échantillon représentatif de l'indice", "L'indice compte des entreprises qui n'existent plus", "Le fonds est en retard sur l'indice"], correct: 1,
      good: "Un échantillon représentatif",
      explain: "Le DIC l'indique&nbsp;: le fonds achète physiquement un échantillon représentatif des titres de l'indice. Détenir chaque petite ligne coûterait cher pour un effet minime&nbsp;; l'échantillon vise à reproduire la performance de l'ensemble.",
      fact: { label: "Méthode de réplication", value: "Physique, par échantillon représentatif", src: "dic" },
      ask: "Quel est l'écart entre la performance du fonds et celle de son indice&nbsp;?" },
    cost("f3", "Coûts", "dic", "0,14", "14&nbsp;€", ["1,40&nbsp;€", "14&nbsp;€", "140&nbsp;€", "1&nbsp;400&nbsp;€"], 1,
      "Le DIC du 28 juillet 2026 indique 0,14&nbsp;% de frais de gestion et 0,03&nbsp;% de coûts de transaction."),
    { id: "f4", axis: "Concentration", type: "choice",
      prompt: "Le Japon est le deuxième pays du fonds. Il pèse environ&nbsp;:",
      options: ["6&nbsp;%", "20&nbsp;%", "35&nbsp;%", "1&nbsp;%"], correct: 0,
      good: "6&nbsp;%",
      explain: "Derrière les États-Unis (61,7&nbsp;%), aucun pays ne dépasse 6&nbsp;%&nbsp;: Japon 6&nbsp;%, Taïwan 3,3&nbsp;%, Royaume-Uni 3,3&nbsp;%, Canada 3&nbsp;%, Chine 2,7&nbsp;%, France 2&nbsp;%.",
      fact: { label: "Deuxième pays du fonds", value: "Japon, 6,0&nbsp;%", src: "fs" },
      ask: "Quelle part de ce fonds est investie en Europe&nbsp;?" },
    tension("f5", "Risque", "dic", "4&nbsp;500", "USD", "−55,0&nbsp;%"),
    horizon("f6", "Horizon", "dic"),
    { id: "f7", axis: "Nature", type: "choice",
      prompt: "Que deviennent les dividendes des entreprises du fonds&nbsp;?",
      options: ["Ils vous sont versés chaque trimestre", "Ils sont réinvestis et se reflètent dans le cours de la part", "Ils sont conservés par Vanguard", "Il n'y en a pas"], correct: 1,
      good: "Ils sont réinvestis",
      explain: "Votre part est capitalisante («&nbsp;Accumulating&nbsp;»)&nbsp;: le DIC précise que les revenus sont réinvestis et se reflètent dans le cours. Une autre part du même fonds, distribuante, les verse aux porteurs.",
      fact: { label: "Traitement des revenus", value: "Réinvestis dans le fonds (part capitalisante)", src: "dic" },
      ask: "Quelle part de ce fonds est la plus adaptée à mon enveloppe&nbsp;: capitalisante ou distribuante&nbsp;?" },
  ],
  notes: [
    "Frais : la fiche du Décodeur indique 0,19 % par an. Le DIC du 28 juillet 2026 et la fiche Vanguard du 31 août 2026 indiquent 0,14 %. À corriger dans la fiche.",
    "La fiche du Décodeur indique « environ 3 600 entreprises » : le fonds en détient 3 784 et l'indice 4 263 (Vanguard, 31 août 2026).",
  ],
};

export const worldsmallcap: Bank = {
  id: "worldsmallcap",
  name: "iShares MSCI World Small Cap UCITS ETF",
  sub: "IE00BF4RFH31",
  short: "iShares MSCI World Small Cap",
  family: "ETF et indices",
  share: "Mon ETF petites entreprises, je le comprends",
  axes: ["Concentration", "Nature", "Coûts", "Risque", "Horizon"],
  src: {
    dic: dic("BlackRock", "part USD capitalisante", "4 sept. 2026", "https://www.blackrock.com/fr/particuliers/literature/kiid/eu-priips-ishares-msci-world-small-cap-ucits-etf-usd-acc-ie00bf4rfh31-fr.pdf"),
    msci: { name: "MSCI, fiche de l'indice MSCI World Small Cap", date: "30 sept. 2026", url: "https://www.msci.com/documents/10199/255599/msci-world-small-cap-index.pdf", refresh: "Revu à chaque nouvelle fiche de l'indice", watch: true },
    wfs: ISHARES_WORLD_FS,
  },
  questions: [
    { id: "w1", axis: "Concentration", type: "slider",
      min: 0, max: 30, step: 0.5, start: 15, unit: "%", target: 2.38, tol: [1.5, 4], dec: 1, gapUnit: "point",
      real: "2,38&nbsp;%", realLabel: "Réalité (indice MSCI World Small Cap, au 30 sept. 2026)",
      prompt: "Dans un ETF MSCI World, les dix premières lignes pèsent environ 26&nbsp;%. Et dans l'indice de ce fonds, selon vous&nbsp;?",
      good: "2,38&nbsp;%",
      explain: "Les dix premières entreprises ne pèsent que 2,38&nbsp;% de l'indice, et la plus grosse 0,63&nbsp;%. Aucune entreprise ne domine&nbsp;: c'est l'opposé d'un indice de grandes capitalisations, où quelques géants font la loi.",
      extra: "Pour comparaison, les dix premières lignes de l'ETF iShares Core MSCI World pèsent 26,47&nbsp;% (fiche iShares, au 31 août 2026).",
      fact: { label: "Poids des 10 premières entreprises de l'indice", value: "2,38&nbsp;%", src: "msci" },
      ask: "Ce fonds fait-il doublon avec les ETF de grandes entreprises que je détiens déjà&nbsp;?" },
    { id: "w2", axis: "Nature", type: "choice",
      prompt: "Combien d'entreprises compte l'indice&nbsp;?",
      options: ["Environ 500", "Environ 1&nbsp;250", "Environ 3&nbsp;900", "Environ 10&nbsp;000"], correct: 2,
      good: "Environ 3&nbsp;900 (3&nbsp;873)",
      explain: "L'indice réunit 3&nbsp;873 petites entreprises de pays développés, soit trois fois plus que le MSCI World. Elles sont, par définition, absentes des indices de grandes entreprises.",
      fact: { label: "Nombre d'entreprises de l'indice", value: "3&nbsp;873", src: "msci" },
      ask: "Quelle part de mon épargne est investie dans des petites entreprises&nbsp;?" },
    { id: "w3", axis: "Concentration", type: "choice",
      prompt: "Derrière les États-Unis (61&nbsp;%), quel pays arrive en deuxième position, avec 13&nbsp;%&nbsp;?",
      options: ["Le Royaume-Uni", "Le Japon", "Le Canada", "La Chine"], correct: 1,
      good: "Le Japon, 13,01&nbsp;%",
      explain: "Le Japon pèse 13,01&nbsp;%, bien plus que dans le MSCI World. Suivent le Royaume-Uni (4,41&nbsp;%), le Canada (4,33&nbsp;%) et l'Australie (3,68&nbsp;%). La Chine n'en fait pas partie&nbsp;: c'est un pays émergent.",
      fact: { label: "Deuxième pays de l'indice", value: "Japon, 13,01&nbsp;%", src: "msci" },
      ask: "Quelle part de ce fonds est investie au Japon et en Europe&nbsp;?" },
    cost("w4", "Coûts", "dic", "0,35", "35&nbsp;€", ["3,50&nbsp;€", "35&nbsp;€", "350&nbsp;€", "3&nbsp;500&nbsp;€"], 1,
      "C'est plus que la plupart des ETF de grandes entreprises du Décodeur. Le DIC ajoute 0,01&nbsp;% de coûts de transaction."),
    { id: "w5", axis: "Nature", type: "choice",
      prompt: "Le DIC indique que le fonds suit son indice par «&nbsp;techniques d'optimisation&nbsp;». Cela veut dire&nbsp;:",
      options: ["Il détient toujours chacune des 3&nbsp;873 entreprises", "Il peut ne détenir qu'une sélection de titres, voire des instruments dérivés, pour reproduire la performance de l'indice", "Il choisit les entreprises les plus prometteuses", "Il garantit la performance de l'indice"], correct: 1,
      good: "Une sélection de titres pour coller à l'indice",
      explain: "Le DIC parle de «&nbsp;sélection stratégique de certains titres&nbsp;» et de l'usage possible d'instruments dérivés. Le but reste de reproduire l'indice, pas de le battre. Avec près de 3&nbsp;900 petites lignes, détenir chacune serait coûteux.",
      fact: { label: "Méthode de réplication", value: "Optimisation (sélection de titres, dérivés possibles)", src: "dic" },
      ask: "Quel est l'écart de suivi de ce fonds par rapport à son indice&nbsp;?" },
    tension("w6", "Risque", "dic", "7&nbsp;390", "USD", "−26,1&nbsp;%"),
    horizon("w7", "Horizon", "dic"),
  ],
  notes: [
    "La fiche du Décodeur indique « plus de 3 500 lignes, aucune ne dépasse 0,4 % » : l'indice compte 3 873 entreprises, et la plus grosse pèse 0,63 % au 30 sept. 2026 (MSCI).",
    "Répartition géographique de la fiche (Amérique du Nord 62 %, Europe 20 %, Japon 10 %) : l'indice compte États-Unis 61,03 %, Japon 13,01 %, Royaume-Uni 4,41 %, Canada 4,33 % (MSCI).",
  ],
};

export const russell2000: Bank = {
  id: "russell2000",
  name: "ETF Russell 2000 (plusieurs émetteurs)",
  sub: "Produit générique du Décodeur",
  short: "ETF Russell 2000",
  family: "ETF et indices",
  share: "Mon ETF Russell 2000, je le comprends",
  axes: ["Nature", "Taille", "Coûts", "Enveloppe", "Risque"],
  src: {
    lseg: { name: "FTSE Russell (LSEG), communiqué sur la révision des indices Russell américains", date: "22 mai 2026", url: "https://www.lseg.com/en/media-centre/press-releases/ftse-russell/2026/ftse-russell-begins-june-2026-semi-annual-russell-us-indexes-reconstitution", refresh: "Revu à chaque révision de l'indice (juin et décembre)", watch: true },
    sp: SP_PEA,
    fiche: FICHE,
  },
  questions: [
    { id: "r1", axis: "Nature", type: "choice",
      prompt: "Le «&nbsp;2000&nbsp;» du Russell 2000 désigne&nbsp;:",
      options: ["Les 2&nbsp;000 plus grandes entreprises américaines", "Les entreprises classées du 1&nbsp;001e au 3&nbsp;000e rang du marché américain, c'est-à-dire les plus petites de cet ensemble", "L'année de création de l'indice", "Un niveau de points"], correct: 1,
      good: "Les rangs 1&nbsp;001 à 3&nbsp;000",
      explain: "FTSE Russell classe les entreprises américaines par taille. Les 1&nbsp;000 premières forment le Russell 1000&nbsp;; les 2&nbsp;000 suivantes, le Russell 2000. C'est donc un indice de petites entreprises.",
      fact: { label: "Construction de l'indice", value: "Rangs 1&nbsp;001 à 3&nbsp;000 du Russell 3000", src: "lseg" },
      ask: "Ce fonds fait-il doublon avec un ETF S&P 500 que je détiens déjà&nbsp;?" },
    { id: "r2", axis: "Nature", type: "choice",
      prompt: "Depuis 2026, à quelle fréquence la liste des entreprises du Russell 2000 est-elle revue&nbsp;?",
      options: ["Jamais", "Une fois par an", "Deux fois par an, en juin et en décembre", "Chaque jour"], correct: 2,
      good: "Deux fois par an",
      explain: "FTSE Russell révise désormais ses indices américains deux fois par an, en juin et en décembre. Les entreprises qui ont trop grandi en sortent, d'autres y entrent&nbsp;: le fonds suit ces changements.",
      fact: { label: "Révision de l'indice", value: "Deux fois par an, en juin et en décembre", src: "lseg" },
      ask: "Combien coûtent au fonds les achats et ventes lors des révisions de l'indice&nbsp;?" },
    { id: "r3", axis: "Taille", type: "choice",
      prompt: "Lors de la révision de juin 2026, quelle valeur en bourse séparait les grandes entreprises américaines des petites&nbsp;?",
      options: ["146 millions de dollars", "5,7 milliards de dollars", "100 milliards de dollars", "1&nbsp;000 milliards de dollars"], correct: 1,
      good: "5,7 milliards de dollars",
      explain: "La frontière est passée à 5,7 milliards de dollars, en hausse de 24&nbsp;%. Au-dessus, une entreprise rejoint les grandes valeurs&nbsp;; en dessous, elle peut faire partie du Russell 2000.",
      fact: { label: "Frontière grandes / petites entreprises (juin 2026)", value: "5,7 milliards de dollars", src: "lseg" },
      ask: "Quelle est la taille moyenne des entreprises détenues par ce fonds&nbsp;?" },
    { id: "r4", axis: "Coûts", type: "choice",
      prompt: "Plusieurs sociétés de gestion proposent un ETF Russell 2000. Leurs frais&nbsp;:",
      options: ["Sont identiques, puisque l'indice est le même", "Peuvent différer&nbsp;: il faut lire le DIC de l'ETF précis que l'on achète", "Sont fixés par la loi"], correct: 1,
      good: "Ils peuvent différer",
      explain: "Un même indice peut être suivi par plusieurs ETF, avec des frais, une méthode de réplication et une devise différents. La fiche du Décodeur donne un ordre de grandeur&nbsp;; seul le DIC du fonds choisi fait foi.",
      fact: { label: "Émetteurs", value: "Plusieurs ETF sur le même indice, frais propres à chacun", src: "fiche" },
      ask: "Quel ETF Russell 2000 me proposez-vous précisément, et quels sont ses frais dans son DIC&nbsp;?" },
    { id: "r5", axis: "Enveloppe", type: "choice",
      prompt: "Peut-on loger un ETF Russell 2000 classique dans un PEA&nbsp;?",
      options: ["Oui, comme n'importe quel ETF", "Non&nbsp;: il investit en actions américaines, alors que le PEA est réservé aux actions européennes et aux fonds investis à plus de 75&nbsp;% en actions européennes", "Oui, mais seulement après 5 ans"], correct: 1,
      good: "Non",
      explain: "Le PEA accueille les actions de sociétés de l'Union européenne ou de l'Espace économique européen, et les fonds investis à plus de 75&nbsp;% dans ces actions. Les actions américaines n'y sont pas éligibles.",
      fact: { label: "Éligibilité au PEA", value: "Actions de sociétés américaines non éligibles au PEA", src: "sp" },
      ask: "Dans quelle enveloppe puis-je détenir ce fonds, et avec quels frais&nbsp;?" },
    { id: "r6", axis: "Risque", type: "choice",
      prompt: "Imaginons&nbsp;: le dollar perd 10&nbsp;% face à l'euro, et les actions de l'indice ne bougent pas. Votre part, comptée en euros&nbsp;:",
      options: ["Monte d'environ 10&nbsp;%", "Baisse d'environ 10&nbsp;%", "Ne bouge pas, puisque les actions n'ont pas bougé"], correct: 1,
      good: "Elle baisse d'environ 10&nbsp;%",
      explain: "Les entreprises sont américaines et cotées en dollars. Si le dollar baisse face à l'euro, la même valeur en dollars vaut moins d'euros, sauf si la part est couverte contre le change (mention «&nbsp;Hedged&nbsp;»).",
      fact: { label: "Risque de change", value: "Entreprises cotées en dollars", src: "fiche" },
      ask: "La part qu'on me propose est-elle couverte contre le risque de change&nbsp;?" },
    { id: "r7", axis: "Taille", type: "choice",
      prompt: "Lors de la révision de juin 2026, combien valait en bourse la plus petite entreprise du Russell 2000&nbsp;?",
      options: ["Environ 146 millions de dollars", "Environ 1,5 milliard de dollars", "Environ 15 milliards de dollars", "Environ 150 milliards de dollars"], correct: 0,
      good: "Environ 146 millions de dollars",
      explain: "La plus petite entreprise valait 146,4 millions de dollars, contre plusieurs milliers de milliards pour les géants du S&P 500. Les écarts de taille sont immenses&nbsp;: les plus petites entreprises sont souvent plus fragiles face à un ralentissement.",
      fact: { label: "Plus petite entreprise de l'indice (juin 2026)", value: "146,4 millions de dollars", src: "lseg" },
      ask: "Quelle part de mon épargne est investie dans des petites entreprises&nbsp;?" },
  ],
  notes: [
    "Produit générique, sans ISIN : les frais (0,30 % dans la fiche), la réplication et la devise dépendent de l'ETF précis. Aucune question ne porte sur un DIC.",
  ],
};

export const sp500ew: Bank = {
  id: "sp500ew",
  name: "Xtrackers S&P 500 Equal Weight UCITS ETF 1C",
  sub: "IE00BLNMYC90",
  short: "Xtrackers S&P 500 Equal Weight",
  family: "ETF et indices",
  share: "Mon ETF S&P 500 Equal Weight, je le comprends",
  axes: ["Nature", "Concentration", "Coûts", "Enveloppe", "Risque"],
  src: {
    fs: { name: "DWS (Xtrackers), fiche du fonds", date: "31 août 2026", url: "https://etf.dws.com/download/asset/ca4bf3ca-9cf0-4594-b9b8-765cd368673c", refresh: "Revu à chaque nouvelle fiche", watch: true },
    cspx: ISHARES_SP500_FS,
    sp: SP_PEA,
  },
  questions: [
    { id: "x1", axis: "Nature", type: "choice",
      prompt: "«&nbsp;Equal Weight&nbsp;» signifie que&nbsp;:",
      options: ["Le fonds ne retient que 50 entreprises", "Chacune des 500 entreprises reçoit le même poids à chaque révision de l'indice", "Les plus grosses entreprises pèsent davantage", "Le fonds investit autant aux États-Unis qu'en Europe"], correct: 1,
      good: "Le même poids pour chaque entreprise",
      explain: "Le fonds suit les mêmes 500 entreprises que le S&P 500, mais l'indice leur donne à toutes le même poids au moment de chaque révision, quelle que soit leur taille en bourse. Les géants pèsent donc beaucoup moins que dans le S&P 500 classique.",
      fact: { label: "Indice suivi", value: "S&P 500 Equal Weight", src: "fs" },
      ask: "Quelle différence de risque entre ce fonds et un S&P 500 classique&nbsp;?" },
    { id: "x2", axis: "Concentration", type: "slider",
      min: 0, max: 50, step: 0.5, start: 20, unit: "%", target: 3.27, tol: [1.5, 4], dec: 1, gapUnit: "point",
      real: "3,27&nbsp;%", realLabel: "Réalité (fiche DWS, au 31 août 2026)",
      prompt: "Dans un ETF S&P 500 classique, les dix premières lignes pèsent 37,75&nbsp;%. Selon vous, combien pèsent-elles dans ce fonds&nbsp;?",
      good: "3,27&nbsp;%",
      explain: "Avec des poids égaux, aucune entreprise ne domine. Les dix premières lignes pèsent 3,27&nbsp;%, contre 37,75&nbsp;% dans le S&P 500 classique (fiche iShares, au 31 août 2026). Le risque est mieux réparti entre les entreprises, mais reste concentré sur un seul pays.",
      fact: { label: "Poids des 10 premières lignes", value: "3,27&nbsp;%", src: "fs" },
      ask: "Ce fonds fait-il doublon avec un ETF S&P 500 ou World que je détiens déjà&nbsp;?" },
    { id: "x3", axis: "Concentration", type: "choice",
      prompt: "Avec 500 entreprises à poids égal, chacune pèse au départ environ&nbsp;:",
      options: ["0,02&nbsp;%", "0,2&nbsp;%", "2&nbsp;%", "20&nbsp;%"], correct: 1,
      good: "0,2&nbsp;%",
      explain: "100&nbsp;% divisés par 500, cela fait 0,2&nbsp;%. Entre deux révisions, les poids s'écartent avec les cours&nbsp;: au 31 août 2026, la plus grosse ligne pesait 0,58&nbsp;%.",
      fact: { label: "Plus grosse ligne du fonds", value: "0,58&nbsp;%", src: "fs", note: "Calcul Kompa&nbsp;: 100&nbsp;% ÷ 500 = 0,2&nbsp;%." },
      ask: "Comment évoluent les poids entre deux révisions de l'indice&nbsp;?" },
    { id: "x4", axis: "Nature", type: "choice",
      prompt: "À quelle fréquence l'indice remet-il les poids à égalité&nbsp;?",
      options: ["Chaque jour", "Chaque trimestre", "Chaque année", "Jamais"], correct: 1,
      good: "Chaque trimestre",
      explain: "L'indice est revu chaque trimestre. Le fonds vend alors un peu des entreprises qui ont le plus monté et rachète celles qui ont baissé, pour revenir à des poids égaux. Ces ajustements ont un coût, compris dans la gestion du fonds.",
      fact: { label: "Révision de l'indice", value: "Trimestrielle", src: "fs" },
      ask: "Combien coûtent au fonds ses rééquilibrages trimestriels&nbsp;?" },
    cost("x5", "Coûts", "fs", "0,15", "15&nbsp;€", ["1,50&nbsp;€", "15&nbsp;€", "150&nbsp;€", "1&nbsp;500&nbsp;€"], 1),
    peaUs("x6", "Enveloppe"),
    changeUsd("x7", "Risque", "fs", "Devise de base du fonds&nbsp;: dollar américain"),
  ],
  notes: [
    "Frais : la fiche du Décodeur indique 0,20 % par an, la fiche DWS du 31 août 2026 indique 0,15 %. À corriger.",
    "Le DIC n'a pas été consulté : pas de question sur la note de risque ni le scénario de tension.",
  ],
};

export const stoxx600: Bank = {
  id: "stoxx600",
  name: "iShares STOXX Europe 600 UCITS ETF (DE) EUR Dist",
  sub: "DE0002635307",
  short: "iShares STOXX Europe 600",
  family: "ETF et indices",
  share: "Mon ETF Europe 600, je le comprends",
  axes: ["Nature", "Concentration", "Coûts", "Risque", "Horizon"],
  src: {
    dic: dic("BlackRock", "part EUR distribuante", "3 sept. 2026", "https://www.blackrock.com/fr/particuliers/literature/kiid/eu-priips-ishares-stoxx-europe-600-ucits-etf-de-eur-dist-de0002635307-fr.pdf"),
    fs: { name: "iShares, fiche mensuelle du fonds", date: "31 août 2026", url: "https://www.ishares.com/ch/individual/en/literature/fact-sheet/exsa-ishares-stoxx-europe-600-ucits-etf-de-fund-fact-sheet-fr-ch.pdf", refresh: "Revu à chaque nouvelle fiche mensuelle", watch: true },
    fiche: FICHE,
  },
  questions: [
    { id: "t1", axis: "Nature", type: "choice",
      prompt: "Parmi les dix premières lignes du fonds figurent HSBC, Roche, Novartis, Shell, Nestlé et AstraZeneca. Ce que ça montre&nbsp;:",
      options: ["Le fonds n'investit qu'en zone euro", "Le fonds investit aussi hors zone euro, notamment au Royaume-Uni et en Suisse", "Le fonds investit surtout aux États-Unis", "Ce sont des obligations"], correct: 1,
      good: "Il investit aussi au Royaume-Uni et en Suisse",
      explain: "HSBC, Shell et AstraZeneca sont britanniques&nbsp;; Roche, Novartis et Nestlé sont suisses. Le STOXX Europe 600 couvre toute l'Europe développée, pas seulement les pays qui utilisent l'euro.",
      fact: { label: "Dix premières lignes", value: "Dont des entreprises britanniques et suisses", src: "fs" },
      ask: "Quelle part de ce fonds est investie hors zone euro&nbsp;?" },
    { id: "t2", axis: "Concentration", type: "slider",
      min: 0, max: 60, step: 1, start: 40, unit: "%", target: 19.36, tol: [3, 8], dec: 1, gapUnit: "point",
      real: "19,36&nbsp;%", realLabel: "Réalité (fiche iShares, au 31 août 2026)",
      prompt: "Le fonds détient 600 entreprises. Selon vous, quelle part représentent ses dix premières lignes&nbsp;?",
      good: "19,36&nbsp;%",
      explain: "Les dix premières lignes pèsent moins d'un cinquième du fonds. La première, ASML, pèse 4,16&nbsp;%. C'est bien moins concentré qu'un ETF CAC 40 (61,61&nbsp;%) ou S&P 500 (37,75&nbsp;%).",
      fact: { label: "Poids des 10 premières lignes", value: "19,36&nbsp;%", src: "fs" },
      ask: "Ce fonds fait-il doublon avec un ETF CAC 40 ou EURO STOXX 50 que je détiens&nbsp;?" },
    { id: "t3", axis: "Nature", type: "choice",
      prompt: "Que deviennent les dividendes des 600 entreprises&nbsp;?",
      options: ["Ils sont réinvestis dans le fonds", "Ils vous sont versés, au moins une fois par an", "Ils sont conservés par BlackRock", "Il n'y en a pas"], correct: 1,
      good: "Ils vous sont versés",
      explain: "La part est distribuante («&nbsp;Dist&nbsp;»)&nbsp;: le DIC précise que les revenus sont versés au moins une fois par an, et la fiche iShares indique jusqu'à quatre versements par an. Ces sommes arrivent sur votre compte, et sont imposables selon votre enveloppe.",
      fact: { label: "Traitement des revenus", value: "Distribution, au moins une fois par an (jusqu'à 4)", src: "dic" },
      ask: "Comment sont imposés les dividendes de ce fonds dans mon enveloppe&nbsp;?" },
    cost("t4", "Coûts", "dic", "0,20", "20&nbsp;€", ["2&nbsp;€", "20&nbsp;€", "200&nbsp;€", "2&nbsp;000&nbsp;€"], 1,
      "Le DIC ajoute 0,01&nbsp;% de coûts de transaction par an."),
    { id: "t5", axis: "Risque", type: "tf",
      prompt: "La part est en euros. Vous n'avez donc aucun risque de change.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "La part s'achète en euros, mais une partie du fonds est investie en livres sterling, francs suisses ou couronnes scandinaves. Si ces monnaies baissent face à l'euro, la valeur de ces actions baisse aussi, convertie en euros.",
      fact: { label: "Devises du fonds", value: "Euro, livre sterling, franc suisse, couronnes scandinaves", src: "fiche" },
      ask: "Quelle part de ce fonds est exposée à d'autres monnaies que l'euro&nbsp;?" },
    tension("t6", "Risque", "dic", "7&nbsp;590", "EUR", "−24,1&nbsp;%"),
    horizon("t7", "Horizon", "dic"),
  ],
};

export const eurostoxx50: Bank = {
  id: "eurostoxx50",
  name: "iShares Core EURO STOXX 50 UCITS ETF EUR (Acc)",
  sub: "IE00B53L3W79",
  short: "iShares Core EURO STOXX 50",
  family: "ETF et indices",
  share: "Mon ETF EURO STOXX 50, je le comprends",
  axes: ["Nature", "Concentration", "Coûts", "Enveloppe", "Risque"],
  src: {
    dic: dic("BlackRock", "part EUR capitalisante", "3 sept. 2026", "https://www.blackrock.com/fr/particuliers/literature/kiid/eu-priips-ishares-core-euro-stoxx-50-ucits-etf-eur-acc-ie00b53l3w79-fr.pdf"),
    bfr: { name: "BlackRock France, page du fonds", date: "consultée le 7 oct. 2026", url: "https://www.blackrock.com/fr/intermediaries/products/253712/ishares-euro-stoxx-50-b-ucits-etf-acc-fund", refresh: "Revu à chaque mise à jour de la page" },
    fs: { name: "iShares, fiche mensuelle d'un ETF sur le même indice (EXW1)", date: "31 août 2026", url: "https://www.blackrock.com/gls-download/literature/fact-sheet/exw1-ishares-core-euro-stoxx-50-ucits-etf-de-fund-fact-sheet-en-lu.pdf", refresh: "Revu à chaque nouvelle fiche mensuelle", watch: true },
  },
  questions: [
    { id: "u1", axis: "Nature", type: "choice",
      prompt: "Quelles entreprises réunit l'indice EURO STOXX 50&nbsp;?",
      options: ["Les 50 plus grandes d'Europe, Royaume-Uni et Suisse compris", "50 grandes entreprises des pays de la zone euro", "Les 50 plus grandes entreprises françaises", "Les 50 plus grandes entreprises du monde"], correct: 1,
      good: "50 grandes entreprises de la zone euro",
      explain: "L'indice se limite aux pays qui utilisent l'euro. Les entreprises britanniques ou suisses, comme Nestlé ou HSBC, n'en font pas partie. La fiche iShares le désigne d'ailleurs comme le «&nbsp;STOXX Eurozone 50&nbsp;».",
      fact: { label: "Indice de référence", value: "50 entreprises de la zone euro (STOXX Eurozone 50)", src: "fs" },
      ask: "Quelle est la différence entre ce fonds et un ETF STOXX Europe 600&nbsp;?" },
    { id: "u2", axis: "Concentration", type: "slider",
      min: 0, max: 100, step: 1, start: 20, unit: "%", target: 42.13, tol: [5, 10], dec: 1, gapUnit: "point",
      real: "42,13&nbsp;%", realLabel: "Réalité (fiche iShares, au 31 août 2026)",
      prompt: "Selon vous, quelle part de l'indice représentent ses dix premières lignes&nbsp;?",
      good: "42,13&nbsp;%",
      explain: "Dix entreprises sur cinquante pèsent plus de 40&nbsp;%. La première, le néerlandais ASML, pèse à elle seule 8,67&nbsp;%.",
      fact: { label: "Poids des 10 premières lignes", value: "42,13&nbsp;%", src: "fs" },
      ask: "Quelle part de mon épargne repose sur ces dix entreprises&nbsp;?" },
    { id: "u3", axis: "Concentration", type: "choice",
      prompt: "Quelle est la première ligne de l'indice&nbsp;?",
      options: ["TotalEnergies", "LVMH", "ASML", "SAP"], correct: 2,
      good: "ASML, 8,67&nbsp;%",
      explain: "ASML, fabricant néerlandais de machines pour l'industrie des puces, arrive en tête avec 8,67&nbsp;%, devant Siemens (4,69&nbsp;%) et SAP (4,32&nbsp;%).",
      fact: { label: "Première ligne", value: "ASML, 8,67&nbsp;%", src: "fs" },
      ask: "Si je détiens ces actions en direct, quelle est ma vraie exposition à chacune&nbsp;?" },
    cost("u4", "Coûts", "dic", "0,10", "10&nbsp;€", ["1&nbsp;€", "10&nbsp;€", "100&nbsp;€", "1&nbsp;000&nbsp;€"], 1,
      "Le DIC ajoute 0,05&nbsp;% de coûts de transaction par an."),
    { id: "u5", axis: "Enveloppe", type: "tf",
      prompt: "Cet ETF peut être logé dans un PEA.",
      options: ["Vrai", "Faux"], correct: 0,
      good: "Vrai",
      explain: "La page française du fonds chez BlackRock indique «&nbsp;Régime fiscal PEA&nbsp;: Oui&nbsp;». Le fonds investit dans des entreprises de la zone euro, compatibles avec les règles du PEA.",
      fact: { label: "Éligibilité au PEA", value: "Oui", src: "bfr" },
      ask: "Quels sont les frais de mon PEA lui-même, en plus de ceux du fonds&nbsp;?" },
    tension("u6", "Risque", "dic", "6&nbsp;510", "EUR", "−34,9&nbsp;%"),
    horizon("u7", "Risque", "dic"),
  ],
  notes: [
    "Les dix premières lignes viennent de la fiche d'un autre ETF iShares sur le même indice (EXW1) : la fiche du fonds lui-même n'a pas pu être ouverte.",
    "La fiche du Décodeur indique « les 10 premières lignes représentent environ 40 % » : 42,13 % au 31 août 2026.",
  ],
};

export const japan: Bank = {
  id: "japan",
  name: "iShares MSCI Japan UCITS ETF USD (Dist)",
  sub: "IE00B02KXH56",
  short: "iShares MSCI Japan",
  family: "ETF et indices",
  share: "Mon ETF Japon, je le comprends",
  axes: ["Risque", "Revenus", "Nature", "Concentration", "Coûts"],
  src: {
    dic: dic("BlackRock", "part USD distribuante", "9 avr. 2026", "https://www.blackrock.com/fr/particuliers/literature/kiid/eu-priips-ishares-msci-japan-ucits-etf-dist-ie00b02kxh56-fr.pdf"),
    fs: { name: "iShares, fiche mensuelle du fonds", date: "31 août 2026", url: "https://www.ishares.com/gls-download/literature/fact-sheet/ijpn-ishares-msci-japan-ucits-etf-usd-dist-fund-fact-sheet-en-gb.pdf", refresh: "Revu à chaque nouvelle fiche mensuelle", watch: true },
    world: { name: "BlackRock, DIC de l'ETF iShares Core MSCI World", date: "3 sept. 2026", url: "https://www.blackrock.com/fr/particuliers/literature/kiid/eu-priips-ishares-core-msci-world-ucits-etf-ie00b4l5y983-fr.pdf", refresh: DIC_REFRESH },
  },
  questions: [
    { id: "j1", axis: "Risque", type: "choice",
      prompt: "La part est en dollars, les entreprises du fonds sont cotées en yens. Le yen baisse fortement face à l'euro, les actions ne bougent pas. Pour vous, en euros&nbsp;:",
      options: ["Votre part monte", "Votre part baisse", "Rien ne change, puisque la part est en dollars"], correct: 1,
      good: "Votre part baisse",
      explain: "Ce qui compte, c'est la monnaie des actions détenues, pas celle de la part. Si le yen baisse face à l'euro, les actions japonaises valent moins d'euros. Le DIC signale ce risque de change.",
      fact: { label: "Risque de change", value: "Actions en yens, part en dollars", src: "dic" },
      ask: "Ce fonds existe-t-il dans une version couverte contre le risque de change&nbsp;?" },
    { id: "j2", axis: "Revenus", type: "choice",
      prompt: "Que deviennent les dividendes des entreprises japonaises du fonds&nbsp;?",
      options: ["Ils sont réinvestis dans le fonds", "Ils vous sont versés deux fois par an", "Ils vous sont versés chaque mois", "Ils restent chez BlackRock"], correct: 1,
      good: "Versés deux fois par an",
      explain: "Cette part est distribuante («&nbsp;Dist&nbsp;»)&nbsp;: le DIC indique que les revenus sont payés une fois par semestre. Ces sommes arrivent sur votre compte et sont imposables selon votre enveloppe.",
      fact: { label: "Traitement des revenus", value: "Distribution semestrielle", src: "dic" },
      ask: "Comment sont imposés ces dividendes dans mon enveloppe&nbsp;?" },
    { id: "j3", axis: "Nature", type: "choice",
      prompt: "Combien d'entreprises le fonds détient-il&nbsp;?",
      options: ["40", "168", "1&nbsp;250", "3&nbsp;000"], correct: 1,
      good: "168",
      explain: "Le fonds détient 168 grandes et moyennes entreprises japonaises. C'est diversifié entre entreprises, mais concentré à 100&nbsp;% sur un seul pays.",
      fact: { label: "Nombre de lignes", value: "168", src: "fs" },
      ask: "Quelle part de mon épargne totale est investie au Japon&nbsp;?" },
    { id: "j4", axis: "Concentration", type: "choice",
      prompt: "Quelle est la première ligne du fonds&nbsp;?",
      options: ["Toyota", "Sony", "Mitsubishi UFJ Financial Group", "Nintendo"], correct: 2,
      good: "Mitsubishi UFJ Financial Group, 4,62&nbsp;%",
      explain: "Le premier groupe bancaire japonais arrive en tête (4,62&nbsp;%), devant Toyota (3,49&nbsp;%). Trois banques figurent parmi les dix premières lignes, qui pèsent ensemble 30,14&nbsp;%.",
      fact: { label: "Première ligne", value: "Mitsubishi UFJ Financial Group, 4,62&nbsp;%", src: "fs" },
      ask: "Quels secteurs pèsent le plus dans ce fonds&nbsp;?" },
    cost("j5", "Coûts", "dic", "0,12", "12&nbsp;€", ["1,20&nbsp;€", "12&nbsp;€", "120&nbsp;€", "1&nbsp;200&nbsp;€"], 1,
      "Le DIC ajoute 0,02&nbsp;% de coûts de transaction par an."),
    { id: "j6", axis: "Risque", type: "choice",
      prompt: "Le DIC classe ce fonds 5 sur une échelle de risque de 1 à 7. Un ETF MSCI World est classé 4. Ce que ça signifie&nbsp;:",
      options: ["Selon cet indicateur, cet ETF Japon est plus risqué", "Il est moins risqué", "Ils sont aussi risqués l'un que l'autre"], correct: 0,
      good: "Plus risqué selon cet indicateur",
      explain: "Plus la note est haute, plus la valeur peut varier fortement. Un seul pays, une seule devise&nbsp;: la diversification est moindre qu'un indice mondial. La note n'est pas une garantie et peut évoluer.",
      fact: { label: "Indicateur de risque", value: "5 sur 7 (MSCI World&nbsp;: 4 sur 7)", src: "dic" },
      ask: "Comment ce fonds s'est-il comporté lors des fortes variations du yen&nbsp;?" },
    tension("j7", "Risque", "dic", "7&nbsp;030", "USD", "−29,7&nbsp;%"),
  ],
  notes: [
    "La fiche du Décodeur indique « environ 200 entreprises » : le fonds en détient 168 (iShares, 31 août 2026). Elle ne dit pas que la part est distribuante.",
    "La fiche iShares du 31 août 2026 semble afficher un indicateur de risque de 4, le DIC du 9 avril 2026 indique 5 : c'est le DIC qui fait foi. À revérifier lors du prochain DIC.",
  ],
};

export const china: Bank = {
  id: "china",
  name: "iShares MSCI China UCITS ETF USD (Acc)",
  sub: "IE00BJ5JPG56",
  short: "iShares MSCI China",
  family: "ETF et indices",
  share: "Mon ETF Chine, je le comprends",
  axes: ["Concentration", "Nature", "Coûts", "Risque", "Horizon"],
  src: {
    dic: dic("BlackRock", "part USD capitalisante", "22 juil. 2026", "https://www.blackrock.com/fr/particuliers/literature/kiid/eu-priips-ishares-msci-china-ucits-etf-usd-acc-ie00bj5jpg56-fr.pdf"),
    msci: { name: "MSCI, fiche de l'indice MSCI China", date: "30 sept. 2026", url: "https://www.msci.com/documents/10199/255599/msci-china-index-usd-net.pdf", refresh: "Revu à chaque nouvelle fiche de l'indice", watch: true },
  },
  questions: [
    { id: "h1", axis: "Concentration", type: "slider",
      min: 0, max: 60, step: 1, start: 10, unit: "%", target: 23.23, tol: [3, 8], dec: 1, gapUnit: "point",
      real: "23,23&nbsp;%", realLabel: "Réalité (indice MSCI China, au 30 sept. 2026)",
      prompt: "L'indice compte 576 entreprises. Selon vous, combien pèsent ensemble les deux premières, Tencent et Alibaba&nbsp;?",
      good: "23,23&nbsp;%",
      explain: "Tencent (13,86&nbsp;%) et Alibaba (9,37&nbsp;%) pèsent près d'un quart de l'indice. Les dix premières entreprises en représentent 41,60&nbsp;%.",
      fact: { label: "Poids de Tencent et Alibaba", value: "23,23&nbsp;%", src: "msci", note: "Calcul Kompa&nbsp;: 13,86&nbsp;% + 9,37&nbsp;%." },
      ask: "Quelle part de mon épargne dépend de ces deux entreprises&nbsp;?" },
    { id: "h2", axis: "Nature", type: "choice",
      prompt: "Où sont cotées les actions chinoises de l'indice&nbsp;?",
      options: ["Uniquement à Shanghai et Shenzhen", "En Chine continentale, à Hong Kong et à l'étranger", "Uniquement à New York", "Uniquement à Hong Kong"], correct: 1,
      good: "En Chine, à Hong Kong et à l'étranger",
      explain: "Le DIC précise que l'indice inclut des actions A (cotées en Chine continentale), des actions H (cotées à Hong Kong) et des valeurs chinoises négociées à l'étranger. Une même économie, plusieurs marchés et plusieurs règles.",
      fact: { label: "Composition de l'indice", value: "Actions A, actions H et valeurs chinoises cotées à l'étranger", src: "dic" },
      ask: "Quelles règles particulières s'appliquent aux actions chinoises détenues par ce fonds&nbsp;?" },
    { id: "h3", axis: "Concentration", type: "choice",
      prompt: "Quel secteur pèse le plus dans l'indice&nbsp;?",
      options: ["La technologie", "La consommation discrétionnaire (commerce, automobile, loisirs)", "L'énergie", "La santé"], correct: 1,
      good: "La consommation discrétionnaire, 22,56&nbsp;%",
      explain: "La consommation discrétionnaire arrive en tête (22,56&nbsp;%), devant la finance (20,98&nbsp;%) et les services de communication (17,94&nbsp;%). Alibaba est classée dans le commerce, Tencent dans la communication, selon la classification de MSCI.",
      fact: { label: "Premier secteur de l'indice", value: "Consommation discrétionnaire, 22,56&nbsp;%", src: "msci" },
      ask: "Quels secteurs de l'économie chinoise ce fonds représente-t-il peu&nbsp;?" },
    cost("h4", "Coûts", "dic", "0,28", "28&nbsp;€", ["2,80&nbsp;€", "28&nbsp;€", "280&nbsp;€", "2&nbsp;800&nbsp;€"], 1,
      "Le DIC ajoute 0,02&nbsp;% de coûts de transaction par an."),
    { id: "h5", axis: "Risque", type: "choice",
      prompt: "Le DIC classe ce fonds 5 sur une échelle de risque de 1 à 7. Ce que ça signifie&nbsp;:",
      options: ["Un risque entre moyen et élevé&nbsp;: la valeur peut varier fortement", "Le capital est protégé à 50&nbsp;%", "Le fonds perdra 5&nbsp;% par an", "Un risque faible"], correct: 0,
      good: "Un risque entre moyen et élevé",
      explain: "La note résume l'ampleur possible des variations. À 5, la valeur peut fortement monter ou baisser. Le DIC rappelle que ce classement n'est pas une garantie et qu'il n'intègre pas le risque de change.",
      fact: { label: "Indicateur de risque", value: "5 sur 7", src: "dic" },
      ask: "Comment ce fonds s'est-il comporté lors des récentes périodes de tension sur les marchés chinois&nbsp;?" },
    tension("h6", "Risque", "dic", "5&nbsp;200", "USD", "−48,0&nbsp;%"),
    horizon("h7", "Horizon", "dic"),
  ],
  notes: [
    "La fiche du Décodeur indique que le fonds gagne quand « les grandes entreprises technologiques et financières » progressent : selon MSCI, le premier secteur est la consommation discrétionnaire (22,56 %), devant la finance et la communication.",
  ],
};

export const india: Bank = {
  id: "india",
  name: "iShares MSCI India UCITS ETF USD (Acc)",
  sub: "IE00BZCQB185",
  short: "iShares MSCI India",
  family: "ETF et indices",
  share: "Mon ETF Inde, je le comprends",
  axes: ["Coûts", "Concentration", "Nature", "Risque", "Horizon"],
  src: {
    dic: dic("BlackRock", "part USD capitalisante", "3 sept. 2026", "https://www.blackrock.com/fr/particuliers/literature/kiid/eu-priips-ishares-msci-india-ucits-etf-usd-acc-ie00bzcqb185-fr.pdf"),
    ish: { name: "iShares, page du fonds", date: "5 oct. 2026", url: "https://www.ishares.com/uk/individual/en/products/297617/ishares-msci-india-ucits-etf", refresh: "Revu à chaque mise à jour de la page", watch: true },
    sp: dic("BlackRock", "ETF iShares Core S&P 500, pour comparaison", "3 sept. 2026", "https://www.blackrock.com/fr/intermediaries/literature/kiid/eu-priips-ishares-core-sp-500-ucits-etf-usd-acc-ie00b5bmr087-fr.pdf"),
  },
  questions: [
    cost("i1", "Coûts", "dic", "0,65", "65&nbsp;€", ["6,50&nbsp;€", "65&nbsp;€", "650&nbsp;€", "6&nbsp;500&nbsp;€"], 1,
      "C'est l'un des ETF les plus chers du Décodeur&nbsp;: neuf fois plus que l'ETF iShares Core S&P 500 (0,07&nbsp;%). Le DIC ajoute 0,03&nbsp;% de coûts de transaction."),
    { id: "i2", axis: "Concentration", type: "choice",
      prompt: "Quel secteur pèse le plus dans le fonds&nbsp;?",
      options: ["La technologie", "La finance", "L'énergie", "La santé"], correct: 1,
      good: "La finance, 30,22&nbsp;%",
      explain: "Les banques et assurances pèsent 30,22&nbsp;% du fonds, devant la consommation discrétionnaire (12,75&nbsp;%) et l'industrie (10,87&nbsp;%). La santé de quelques grandes banques indiennes compte donc beaucoup.",
      fact: { label: "Premier secteur du fonds", value: "Finance, 30,22&nbsp;%", src: "ish" },
      ask: "Quelle part de mon épargne dépend du secteur financier, tous placements confondus&nbsp;?" },
    { id: "i3", axis: "Nature", type: "choice",
      prompt: "Combien d'entreprises le fonds détient-il&nbsp;?",
      options: ["40", "165", "1&nbsp;250", "3&nbsp;000"], correct: 1,
      good: "165",
      explain: "Le fonds détient 165 grandes et moyennes entreprises indiennes. Il est diversifié entre entreprises, mais concentré à 100&nbsp;% sur un seul pays.",
      fact: { label: "Nombre de lignes", value: "165", src: "ish" },
      ask: "Quelle part de mon épargne totale est investie en Inde&nbsp;?" },
    { id: "i4", axis: "Risque", type: "choice",
      prompt: "Les entreprises sont cotées en roupies, la part en dollars. La roupie baisse face à l'euro, les actions ne bougent pas. Pour vous, en euros&nbsp;:",
      options: ["Votre part monte", "Votre part baisse", "Rien ne change"], correct: 1,
      good: "Votre part baisse",
      explain: "La même valeur en roupies vaut moins d'euros une fois convertie. Le DIC signale ce risque de change, que la note de risque de 1 à 7 n'intègre pas.",
      fact: { label: "Risque de change", value: "Actions en roupies, part en dollars", src: "dic" },
      ask: "Comment la roupie a-t-elle évolué face à l'euro ces dernières années&nbsp;?" },
    tension("i5", "Risque", "dic", "6&nbsp;100", "USD", "−39,0&nbsp;%"),
    horizon("i6", "Horizon", "dic"),
    { id: "i7", axis: "Nature", type: "choice",
      prompt: "Que deviennent les dividendes des entreprises indiennes du fonds&nbsp;?",
      options: ["Ils vous sont versés chaque trimestre", "Ils sont réinvestis dans le fonds", "Ils restent chez BlackRock", "Il n'y en a pas"], correct: 1,
      good: "Ils sont réinvestis",
      explain: "La part est capitalisante&nbsp;: le DIC précise que les revenus sont inclus dans la valeur des parts. Rien n'arrive sur votre compte.",
      fact: { label: "Traitement des revenus", value: "Capitalisation", src: "dic" },
      ask: "Comment ce fonds est-il imposé dans l'enveloppe où je le détiens&nbsp;?" },
  ],
};

export const ETF_BANKS: Bank[] = [world, sp500, nasdaq, em, cac40, acwi, ftseallworld, worldsmallcap, russell2000, sp500ew, stoxx600, eurostoxx50, japan, china, india];
