import type { Bank } from "../types";
import { FICHE, AMF_OBLIGATIONS, AMF_FRAIS_2017, AMF_FRAIS_2023, AMF_ETUDE_FRAIS_2024 } from "../sources";

const SPIVA = {
  name: "S&P Dow Jones Indices, SPIVA Europe, mi-2025",
  date: "période terminée le 30 juin 2025",
  url: "https://www.spglobal.com/spdji/en/spiva/article/spiva-europe-mid-year-2025",
  refresh: "Revu à chaque nouvelle édition (deux par an)",
  watch: true,
};

export const actif: Bank = {
  id: "fonds-actif-actions",
  name: "Fonds actions géré activement (OPCVM, exemple générique)",
  sub: "Produit générique du Décodeur",
  short: "Fonds actions géré activement",
  family: "Fonds d'investissement",
  share: "Mon fonds géré activement, je le comprends",
  axes: ["Nature", "Frais", "Performance", "Documents", "Risque"],
  src: { amf24: AMF_ETUDE_FRAIS_2024, amf17: AMF_FRAIS_2017, spiva: SPIVA, fiche: FICHE },
  questions: [
    { id: "g1", axis: "Nature", type: "choice",
      prompt: "Qu'est-ce qui distingue un fonds géré activement d'un ETF&nbsp;?",
      options: ["Rien, ce sont deux noms pour la même chose", "Une équipe de gérants choisit les titres pour essayer de faire mieux qu'un indice, au lieu de le suivre", "Un fonds actif est garanti", "Un fonds actif n'investit qu'en obligations"], correct: 1,
      good: "Des gérants choisissent les titres",
      explain: "Dans un fonds actif, des gérants achètent et vendent selon leurs convictions, avec l'objectif de battre un indice de référence. Un ETF se contente de suivre son indice. Les choix humains ont un coût, et ne réussissent pas toujours.",
      fact: { label: "Définition", value: "Des gérants sélectionnent les titres pour viser mieux que l'indice", src: "fiche" },
      ask: "Quel est l'indice de référence de ce fonds, et comment s'est-il comparé à lui sur dix ans, frais déduits&nbsp;?" },
    { id: "g2", axis: "Frais", type: "choice",
      prompt: "Selon une étude de l'AMF sur les fonds de droit français, les fonds indiciels sont en moyenne&nbsp;:",
      options: ["Plus chers que les fonds gérés activement", "Moins chers que les fonds gérés activement", "Au même prix"], correct: 1,
      good: "Moins chers",
      explain: "L'AMF confirme que les fonds indiciels sont en moyenne moins chers que les fonds gérés activement, en frais courants comme en frais d'entrée. Payer plus n'est justifié que si la gestion apporte davantage, ce qui n'est jamais garanti.",
      fact: { label: "Frais des fonds indiciels", value: "En moyenne moins élevés que ceux des fonds actifs", src: "amf24" },
      ask: "Quels sont les frais courants de ce fonds, comparés à ceux d'un ETF sur le même marché&nbsp;?" },
    { id: "g3", axis: "Performance", type: "slider",
      min: 0, max: 100, step: 1, start: 50, unit: "%", target: 98, tol: [5, 12], dec: 0, gapUnit: "point",
      real: "98&nbsp;%", realLabel: "Réalité (SPIVA Europe, 10 ans au 30 juin 2025)",
      prompt: "Sur dix ans, selon vous, quelle part des fonds actions mondiales gérés activement en euros a fait moins bien que son indice&nbsp;?",
      good: "98&nbsp;%",
      explain: "Selon l'étude SPIVA d'S&P Dow Jones Indices, 98&nbsp;% de ces fonds ont fait moins bien que leur indice sur dix ans, frais déduits. Les résultats varient selon les marchés et les périodes&nbsp;: sur six mois en 2025, seuls 32&nbsp;% des fonds actions françaises ont fait moins bien que leur indice.",
      fact: { label: "Fonds actions mondiales en euros sous leur indice, sur 10 ans", value: "98&nbsp;%", src: "spiva" },
      ask: "Comment ce fonds s'est-il comporté face à son indice sur 5 et 10 ans, frais déduits&nbsp;?" },
    { id: "g4", axis: "Performance", type: "choice",
      prompt: "L'étude SPIVA Europe suit les fonds actions vendus en Europe. Au bout de dix ans, quelle part existe encore&nbsp;?",
      options: ["Presque tous", "Environ 58&nbsp;%", "Environ 10&nbsp;%"], correct: 1,
      good: "Environ 58&nbsp;%",
      explain: "Selon SPIVA, seuls 58&nbsp;% des fonds actions existaient encore dix ans plus tard&nbsp;: les autres ont été fermés ou fusionnés, souvent après de mauvais résultats. Les classements de fonds qui ne montrent que les survivants donnent donc une image trop flatteuse.",
      fact: { label: "Fonds actions encore existants après 10 ans", value: "58&nbsp;%", src: "spiva" },
      ask: "Depuis quand ce fonds existe-t-il, et a-t-il changé de gérant ou de stratégie&nbsp;?" },
    { id: "g5", axis: "Frais", type: "choice",
      prompt: "La fiche donne 1,58&nbsp;% de frais courants dans son exemple. Comment ces frais sont-ils prélevés&nbsp;?",
      options: ["Par un prélèvement sur votre compte bancaire", "Directement dans la valeur des parts, sans ligne visible", "Seulement les années où le fonds gagne"], correct: 1,
      good: "Dans la valeur des parts",
      explain: "Selon l'AMF, les frais courants sont déduits du calcul de la valeur liquidative, publiée nette de frais. Vous ne les voyez jamais passer, et ils sont prélevés que le fonds monte ou baisse.",
      fact: { label: "Prélèvement des frais courants", value: "Déduits de la valeur liquidative", src: "amf17" },
      ask: "Quel montant en euros ces frais courants représentent-ils chaque année sur mon placement&nbsp;?" },
    { id: "g6", axis: "Documents", type: "choice",
      prompt: "Où trouver les frais maximaux d'entrée et de sortie, les frais courants et la commission de surperformance d'un fonds&nbsp;?",
      options: ["Dans son document d'informations clés ou son prospectus", "Sur la plaquette commerciale uniquement", "Nulle part&nbsp;: c'est confidentiel"], correct: 0,
      good: "Dans le document d'informations clés ou le prospectus",
      explain: "L'AMF invite à lire la partie relative aux frais du document d'informations clés ou du prospectus. La commission de surperformance, quand elle existe, rémunère la société de gestion lorsque le fonds dépasse les objectifs de performance fixés à l'avance.",
      fact: { label: "Où lire les frais", value: "Document d'informations clés ou prospectus", src: "amf17" },
      ask: "Ce fonds prélève-t-il une commission de surperformance, et selon quelle règle&nbsp;?" },
    { id: "g7", axis: "Risque", type: "choice",
      prompt: "Le marché des actions monte de 10&nbsp;% sur l'année. Votre fonds géré activement&nbsp;:",
      options: ["Monte forcément de 10&nbsp;%", "Peut monter plus ou moins, selon les choix des gérants et après les frais", "Ne bouge pas, il est protégé"], correct: 1,
      good: "Plus ou moins, selon les choix et les frais",
      explain: "Le fonds ne détient pas tout le marché&nbsp;: sa performance dépend des titres choisis, puis des frais. Il peut faire mieux, ou moins bien, que le marché, à la hausse comme à la baisse.",
      fact: { label: "Risque de gestion", value: "La performance dépend des choix des gérants et des frais", src: "fiche" },
      ask: "Comment ce fonds s'est-il comporté pendant les dernières baisses de marché&nbsp;?" },
  ],
  notes: [
    "SPIVA (S&P Dow Jones Indices) n'est pas dans la liste des sources prioritaires, mais c'est la référence la plus suivie sur ce sujet. La fiche du Décodeur cite « 80 % à 90 % sur 15 à 20 ans » sans source.",
    "La fiche indique des frais « souvent autour de 1,5 % à 2 % par an en France » sans source. L'étude AMF de mai 2024 donne une médiane d'environ 1 % tous fonds confondus sur 2017-2022, sans chiffre isolé pour les fonds actions actifs.",
  ],
};

export const diversifie: Bank = {
  id: "fonds-diversifie",
  name: "Fonds diversifié (profil équilibré, exemple générique)",
  sub: "Produit générique du Décodeur",
  short: "Fonds diversifié",
  family: "Fonds d'investissement",
  share: "Mon fonds diversifié, je le comprends",
  axes: ["Nature", "Frais annuels", "Frais d'entrée", "Risque", "Enveloppe"],
  src: { amf17: AMF_FRAIS_2017, amf23: AMF_FRAIS_2023, amfobl: AMF_OBLIGATIONS, fiche: FICHE },
  questions: [
    { id: "f1", axis: "Nature", type: "choice",
      prompt: "Un fonds diversifié «&nbsp;équilibré&nbsp;» contient en général&nbsp;:",
      options: ["Uniquement des actions", "Un mélange d'actions et d'obligations, dosé selon un profil", "Uniquement des obligations d'État", "De l'immobilier détenu en direct"], correct: 1,
      good: "Un mélange d'actions et d'obligations",
      explain: "Il mélange actions, obligations et parfois d'autres actifs, selon un profil défini à l'avance&nbsp;: prudent, équilibré ou dynamique. L'AMF note par exemple que les fonds diversifiés dits prudents détiennent beaucoup d'obligations.",
      fact: { label: "Composition", value: "Actions et obligations dosées selon un profil", src: "amfobl" },
      ask: "Quelle est la répartition actuelle entre actions et obligations, et dans quelles limites le gérant peut-il la modifier&nbsp;?" },
    { id: "f2", axis: "Frais annuels", type: "choice",
      prompt: "Les frais courants d'un fonds sont prélevés comment&nbsp;?",
      options: ["Par un prélèvement sur votre compte bancaire", "Directement dans la valeur des parts, sans ligne visible", "Seulement les années où le fonds gagne", "Une seule fois, à l'achat"], correct: 1,
      good: "Directement dans la valeur des parts",
      explain: "Selon l'AMF, les frais courants sont déduits du calcul de la valeur liquidative, qui est publiée nette de frais. Vous ne les voyez jamais passer&nbsp;: ils sont déjà dans le prix de la part.",
      fact: { label: "Prélèvement des frais courants", value: "Déduits de la valeur liquidative du fonds", src: "amf17" },
      ask: "Quels sont les frais courants de ce fonds, en pourcentage et en euros sur mon montant&nbsp;?" },
    { id: "f3", axis: "Frais annuels", type: "choice",
      prompt: "Exemple fictif&nbsp;: 10&nbsp;000&nbsp;€ placés 20 ans, avec un rendement supposé de 4&nbsp;% par an. Qu'est-ce qui coûte le plus cher&nbsp;?",
      options: ["3&nbsp;% de frais d'entrée, une seule fois", "1,5&nbsp;% de frais chaque année", "Les deux coûtent à peu près pareil"], correct: 1,
      good: "1,5&nbsp;% par an, de loin",
      explain: "Dans cet exemple, les 3&nbsp;% d'entrée coûtent environ 657&nbsp;€ au bout de 20 ans. Les 1,5&nbsp;% annuels en coûtent environ 5&nbsp;716&nbsp;€, près de neuf fois plus. L'AMF le rappelle&nbsp;: les frais prélevés chaque année pèsent plus que ceux prélevés au départ.",
      fact: { label: "Frais annuels et frais d'entrée", value: "Les frais annuels pèsent davantage sur le rendement", src: "amf23", note: "Calcul Kompa&nbsp;: 10&nbsp;000&nbsp;€ sur 20 ans à 4&nbsp;% par an supposés, frais déduits du rendement. Exemple, pas une prévision." },
      ask: "Quel est le total des frais que je paierai chaque année sur ce fonds, en euros&nbsp;?" },
    { id: "f4", axis: "Frais d'entrée", type: "tf",
      prompt: "Les frais d'entrée d'un fonds sont fixés une fois pour toutes&nbsp;: impossible d'en discuter.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "L'AMF indique que les frais d'entrée peuvent être négociables, tout comme les frais de sortie. Rien n'interdit de poser la question avant de souscrire.",
      fact: { label: "Frais d'entrée", value: "Ils peuvent être négociables", src: "amf17" },
      ask: "Pouvez-vous réduire ou supprimer les frais d'entrée sur ce fonds&nbsp;?" },
    { id: "f5", axis: "Enveloppe", type: "choice",
      prompt: "Ce fonds est logé dans une assurance-vie. Ce que vous payez au total&nbsp;:",
      options: ["Seulement les frais du fonds", "Les frais du fonds, plus les frais de gestion du contrat", "Seulement les frais du contrat", "Rien, l'assurance-vie supprime les frais"], correct: 1,
      good: "Les frais du fonds et ceux du contrat",
      explain: "Les frais s'empilent&nbsp;: ceux du fonds, puis les frais de gestion annuels du contrat, et parfois des frais d'arbitrage quand vous changez de support. L'AMF souligne que ces frais cumulés peuvent parfois représenter 3 à 4&nbsp;% de l'épargne placée.",
      fact: { label: "Empilement des frais", value: "Cumulés, ils peuvent parfois atteindre 3 à 4&nbsp;% de l'épargne placée", src: "amf23" },
      ask: "Quels sont, en euros, tous les frais prélevés chaque année sur mon contrat et sur ce fonds&nbsp;?" },
    { id: "f6", axis: "Risque", type: "choice",
      prompt: "Les taux d'intérêt montent et les actions baissent en même temps. Votre fonds équilibré&nbsp;:",
      options: ["Est protégé, les obligations compensent toujours les actions", "Peut baisser des deux côtés à la fois", "Ne bouge pas"], correct: 1,
      good: "Il peut baisser des deux côtés",
      explain: "La partie obligataire n'est pas un bouclier automatique&nbsp;: quand les taux montent, le prix des obligations déjà émises baisse, comme l'explique l'AMF. Si les actions reculent au même moment, les deux parties du fonds perdent ensemble.",
      fact: { label: "Taux et obligations", value: "Quand les taux montent, le prix des obligations déjà émises baisse", src: "amfobl" },
      ask: "Comment ce fonds s'est-il comporté les années où actions et obligations ont baissé ensemble&nbsp;?" },
    { id: "f7", axis: "Risque", type: "tf",
      prompt: "«&nbsp;Profil équilibré&nbsp;» signifie que votre capital est protégé.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "«&nbsp;Équilibré&nbsp;» décrit un dosage entre actions et obligations, pas une garantie. Le fonds peut perdre de la valeur, et rien ne garantit de retrouver sa mise.",
      fact: { label: "Garantie du capital", value: "Aucune&nbsp;: «&nbsp;équilibré&nbsp;» décrit un dosage, pas une protection", src: "fiche" },
      ask: "Ce fonds offre-t-il une garantie sur le capital, et si oui, à quelles conditions&nbsp;?" },
  ],
  notes: [
    "Produit générique : le test le plus utile portera sur le fonds précis de la personne, avec son propre DIC.",
    "La fiche du Décodeur cite des frais « souvent proches de 1,5 % à 1,6 % par an » sans source ni date.",
  ],
};

export const flexible: Bank = {
  id: "fonds-flexible",
  name: "Fonds flexible (allocation d'actifs discrétionnaire, exemple générique)",
  sub: "Produit générique du Décodeur",
  short: "Fonds flexible",
  family: "Fonds d'investissement",
  share: "Mon fonds flexible, je le comprends",
  axes: ["Nature", "Exposition", "Frais", "Risque", "Documents"],
  src: { amf17: AMF_FRAIS_2017, amfobl: AMF_OBLIGATIONS, fiche: FICHE },
  questions: [
    { id: "x1", axis: "Nature", type: "choice",
      prompt: "Ce qui caractérise un fonds flexible&nbsp;:",
      options: ["Il garde toujours 50&nbsp;% d'actions et 50&nbsp;% d'obligations", "Son gérant peut faire varier fortement la part d'actions, parfois de 0 à 100&nbsp;%, selon sa lecture des marchés", "Il est garanti", "Il suit un indice"], correct: 1,
      good: "Une part d'actions qui peut varier fortement",
      explain: "Le gérant d'un fonds flexible ajuste librement la part d'actions et d'obligations. Vous lui déléguez ces décisions&nbsp;: le résultat dépend donc beaucoup de la justesse de ses choix.",
      fact: { label: "Définition", value: "Part d'actions variable, parfois de 0 à 100&nbsp;%", src: "fiche" },
      ask: "Dans quelles limites le gérant peut-il faire varier la part d'actions de ce fonds&nbsp;?" },
    { id: "x2", axis: "Exposition", type: "slider",
      min: 0, max: 40, step: 1, start: 30, unit: "%", target: 16, tol: [1, 4], dec: 0, gapUnit: "point", fem: false,
      real: "16&nbsp;%", realLabel: "Réponse (calcul Kompa)",
      prompt: "Exemple fictif&nbsp;: votre fonds flexible est investi à 80&nbsp;% en actions. Les actions baissent de 20&nbsp;%, le reste ne bouge pas. Selon vous, de combien baisse le fonds&nbsp;?",
      good: "16&nbsp;%",
      explain: "80&nbsp;% du fonds perdent 20&nbsp;%&nbsp;: 0,8 × 20 = 16&nbsp;%. Avec 30&nbsp;% d'actions, la même baisse aurait coûté 6&nbsp;%. Dans un fonds flexible, ce qui compte, c'est la part d'actions au moment où le marché bouge.",
      fact: { label: "Effet de la part d'actions", value: "Baisse du fonds ≈ part d'actions × baisse des actions", src: "fiche", note: "Calcul Kompa sur un exemple fictif, sans frais." },
      ask: "Quelle était la part d'actions de ce fonds lors des dernières baisses de marché&nbsp;?" },
    { id: "x3", axis: "Exposition", type: "tf",
      prompt: "Le gérant peut réduire les actions avant une baisse. Un fonds flexible vous protège donc des baisses.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "La flexibilité permet d'essayer de limiter les baisses, sans rien garantir&nbsp;: le gérant peut se tromper de moment, rester investi juste avant une chute ou sortir juste avant une hausse.",
      fact: { label: "Protection", value: "Aucune garantie&nbsp;: tout dépend des décisions du gérant", src: "fiche" },
      ask: "Comment ce fonds s'est-il comporté pendant les dernières fortes baisses, comparé à un fonds équilibré classique&nbsp;?" },
    { id: "x4", axis: "Frais", type: "choice",
      prompt: "Certains fonds flexibles prélèvent une «&nbsp;commission de surperformance&nbsp;». Elle rémunère la société de gestion&nbsp;:",
      options: ["Chaque année, quoi qu'il arrive", "Lorsque le fonds dépasse les objectifs de performance fixés à l'avance", "Uniquement quand le fonds perd de l'argent"], correct: 1,
      good: "Quand le fonds dépasse ses objectifs",
      explain: "C'est la définition de l'AMF. Elle s'ajoute aux frais courants. Sa règle de calcul figure dans le document d'informations clés ou le prospectus&nbsp;: elle vaut la peine d'être lue.",
      fact: { label: "Commission de surperformance", value: "Prélevée quand le fonds dépasse ses objectifs fixés", src: "amf17" },
      ask: "Ce fonds prélève-t-il une commission de surperformance, et selon quelle règle&nbsp;?" },
    { id: "x5", axis: "Frais", type: "tf",
      prompt: "Les frais d'entrée d'un fonds ne se discutent jamais.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "L'AMF indique que les frais d'entrée, comme les frais de sortie, peuvent être négociables. Demander une réduction avant de souscrire est légitime.",
      fact: { label: "Frais d'entrée", value: "Ils peuvent être négociables", src: "amf17" },
      ask: "Pouvez-vous réduire ou supprimer les frais d'entrée sur ce fonds&nbsp;?" },
    { id: "x6", axis: "Risque", type: "choice",
      prompt: "Le fonds détient beaucoup d'obligations. Les taux d'intérêt montent. Cette partie du fonds&nbsp;:",
      options: ["Gagne de la valeur", "Perd de la valeur", "Ne bouge pas"], correct: 1,
      good: "Elle perd de la valeur",
      explain: "Quand les taux montent, le prix des obligations déjà émises baisse, comme l'explique l'AMF. Réduire les actions ne met donc pas forcément à l'abri.",
      fact: { label: "Taux et obligations", value: "Quand les taux montent, le prix des obligations déjà émises baisse", src: "amfobl" },
      ask: "Quelle est la durée moyenne des obligations détenues par ce fonds&nbsp;?" },
    { id: "x7", axis: "Documents", type: "choice",
      prompt: "Où trouver les frais maximaux d'entrée et de sortie, les frais courants et la commission de surperformance&nbsp;?",
      options: ["Dans le document d'informations clés ou le prospectus du fonds", "Sur la plaquette commerciale uniquement", "Nulle part&nbsp;: c'est confidentiel"], correct: 0,
      good: "Dans le document d'informations clés ou le prospectus",
      explain: "L'AMF invite à lire attentivement la partie relative aux frais de ces documents&nbsp;: elle indique les frais maximaux d'entrée et de sortie, les frais courants et la commission de surperformance.",
      fact: { label: "Où lire les frais", value: "Document d'informations clés ou prospectus", src: "amf17" },
      ask: "Pouvez-vous me remettre le document d'informations clés de ce fonds&nbsp;?" },
  ],
};

export const FONDS_BANKS: Bank[] = [actif, diversifie, flexible];
