import type { Bank } from "../types";
import { FICHE, AMF_SCPI } from "../sources";

export const scpi: Bank = {
  id: "scpi",
  name: "SCPI de rendement (Société Civile de Placement Immobilier)",
  sub: "Produit générique du Décodeur",
  short: "SCPI",
  family: "Immobilier",
  share: "Ma SCPI, je la comprends",
  axes: ["Nature", "Coûts", "Risque", "Revenus", "Horizon"],
  src: { amfscpi: AMF_SCPI, fiche: FICHE },
  questions: [
    { id: "s1", axis: "Nature", type: "choice",
      prompt: "Acheter des parts de SCPI, c'est&nbsp;:",
      options: ["Acheter un appartement à votre nom", "Détenir une part d'un ensemble d'immeubles loués, géré par une société de gestion", "Prêter à un promoteur immobilier", "Acheter des actions de sociétés immobilières cotées en bourse"], correct: 1,
      good: "Détenir une part d'un parc immobilier loué",
      explain: "Vous détenez des parts d'une société qui possède et loue un parc immobilier&nbsp;: bureaux, commerces, entrepôts... La société de gestion s'occupe des locataires et vous reverse une partie des loyers. Les foncières cotées, elles, sont des actions&nbsp;: un autre produit du Décodeur.",
      fact: { label: "Nature d'une SCPI", value: "Des parts d'un parc immobilier locatif géré pour vous", src: "amfscpi" },
      ask: "Quels types de biens cette SCPI détient-elle, et dans quels pays&nbsp;?" },
    { id: "s2", axis: "Coûts", type: "slider",
      min: 5000, max: 10000, step: 100, start: 7500, unit: "€", target: 9000, tol: [150, 500], dec: 0, gapUnit: "€", fem: false,
      real: "9&nbsp;000&nbsp;€", realLabel: "Montant réellement investi (exemple)",
      prompt: "Exemple fictif&nbsp;: vous investissez 10&nbsp;000&nbsp;€ dans une SCPI qui prélève 10&nbsp;% de frais d'entrée. Combien travaille réellement dans l'immobilier&nbsp;?",
      good: "9&nbsp;000&nbsp;€",
      explain: "10&nbsp;% de frais d'entrée, ce sont 1&nbsp;000&nbsp;€ prélevés dès le départ&nbsp;: seuls 9&nbsp;000&nbsp;€ travaillent. L'AMF indique des frais d'entrée compris entre 5 et 12&nbsp;%, auxquels s'ajoutent des frais de gestion annuels de 8 à 10&nbsp;% des revenus.",
      fact: { label: "Frais d'une SCPI selon l'AMF", value: "Entrée de 5 à 12&nbsp;%, gestion de 8 à 10&nbsp;% des revenus", src: "amfscpi" },
      ask: "Quels sont exactement les frais d'entrée, de gestion et de revente de cette SCPI&nbsp;?" },
    { id: "s3", axis: "Risque", type: "tf",
      prompt: "Le capital investi dans une SCPI est garanti.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "L'AMF est explicite&nbsp;: le capital investi dans une SCPI n'est pas garanti, c'est un placement risqué. La valeur des parts peut baisser si les immeubles perdent de la valeur.",
      fact: { label: "Garantie du capital", value: "Aucune&nbsp;: le capital n'est pas garanti", src: "amfscpi" },
      ask: "Comment la valeur des parts de cette SCPI a-t-elle évolué ces dernières années&nbsp;?" },
    { id: "s4", axis: "Revenus", type: "choice",
      prompt: "Les revenus versés par une SCPI sont&nbsp;:",
      options: ["Garantis par la société de gestion", "Garantis par l'État", "Variables&nbsp;: ils peuvent baisser si des locataires partent", "Fixés pour toute la durée du placement"], correct: 2,
      good: "Variables",
      explain: "Les revenus viennent des loyers. L'AMF rappelle qu'ils peuvent diminuer, par exemple au départ de locataires ou lors d'une relocation moins favorable.",
      fact: { label: "Revenus", value: "Non garantis&nbsp;: ils dépendent des loyers encaissés", src: "amfscpi" },
      ask: "Quel est le taux d'occupation des immeubles de cette SCPI&nbsp;?" },
    { id: "s5", axis: "Risque", type: "choice",
      prompt: "Vous voulez revendre vos parts. Selon l'AMF&nbsp;:",
      options: ["La revente est immédiate, comme pour une action", "Elle peut prendre plusieurs semaines, voire plusieurs mois", "La société de gestion doit vous racheter sous 48 heures", "Il est interdit de revendre avant 10 ans"], correct: 1,
      good: "Plusieurs semaines, voire plusieurs mois",
      explain: "Les parts de SCPI ne se revendent pas facilement&nbsp;: le délai peut atteindre plusieurs mois, sans garantie sur le prix. C'est une grande différence avec un placement coté en bourse.",
      fact: { label: "Revente des parts", value: "Délai de plusieurs semaines à plusieurs mois", src: "amfscpi" },
      ask: "Combien de parts sont actuellement en attente de revente sur cette SCPI&nbsp;?" },
    { id: "s6", axis: "Horizon", type: "choice",
      prompt: "Sur quelle durée l'AMF dit-elle d'envisager un placement en SCPI&nbsp;?",
      options: ["1 à 2 ans", "3 à 5 ans", "10 à 20 ans au moins", "Aucune durée particulière"], correct: 2,
      good: "10 à 20 ans au moins",
      explain: "Comme tout investissement immobilier, une SCPI doit s'envisager sur le long terme&nbsp;: entre 10 et 20 ans au moins, selon l'AMF. Les frais d'entrée et le délai de revente pèsent lourd sur une durée courte.",
      fact: { label: "Durée de placement", value: "Long terme&nbsp;: 10 à 20 ans au moins", src: "amfscpi" },
      ask: "Quelle durée de placement indique la documentation de cette SCPI&nbsp;?" },
    { id: "s7", axis: "Coûts", type: "choice",
      prompt: "Vous revendez vos parts au bout de 2 ans. Le principal frein&nbsp;:",
      options: ["Les frais d'entrée n'ont pas eu le temps d'être compensés par les revenus", "Une pénalité fixée par l'État", "Il n'y a aucun frein", "L'impôt sur la fortune"], correct: 0,
      good: "Les frais d'entrée pas encore compensés",
      explain: "Les frais d'entrée sont prélevés en une fois, au départ. Sur une courte durée, les revenus perçus ont rarement le temps de les compenser, et une commission de revente peut s'y ajouter.",
      fact: { label: "Frais à la revente", value: "Une commission de revente peut s'ajouter", src: "amfscpi" },
      ask: "Quels frais s'appliqueraient si je revendais mes parts au bout de deux ans&nbsp;?" },
  ],
  notes: [
    "La fiche du Décodeur indique des frais d'entrée « souvent entre 8 % et 12 % » ; l'AMF donne une fourchette de 5 à 12 %. À harmoniser.",
    "La fiche cite un taux de distribution moyen de 4,9 % en 2025 selon l'ASPIM, qui ne fait pas partie des sources prioritaires.",
  ],
};

export const opci: Bank = {
  id: "opci",
  name: "OPCI (Organisme de Placement Collectif en Immobilier)",
  sub: "Produit générique du Décodeur",
  short: "OPCI",
  family: "Immobilier",
  share: "Mon OPCI, je le comprends",
  axes: ["Nature", "Composition", "Disponibilité", "Frais", "Risque"],
  src: {
    opcimmo: { name: "Amundi, prospectus de l'OPCI grand public OPCIMMO (exemple)", date: "consulté le 7 oct. 2026", url: "https://www.amundi.fr/fr_part/dl/doc/prospectus/FR0011066802/FRA/FRA", refresh: "Revu à chaque nouvelle version du prospectus" },
    amfscpi: AMF_SCPI,
    fiche: FICHE,
  },
  questions: [
    { id: "p1", axis: "Nature", type: "choice",
      prompt: "Ce qui distingue principalement un OPCI d'une SCPI&nbsp;:",
      options: ["L'OPCI n'investit pas dans l'immobilier", "L'OPCI mélange immobilier, actifs financiers et liquidités", "L'OPCI est garanti par l'État", "Il n'y a aucune différence"], correct: 1,
      good: "Il mélange immobilier, actifs financiers et liquidités",
      explain: "Un OPCI détient surtout de l'immobilier, mais aussi des actions, des obligations et de la trésorerie. Cette poche financière le rend plus facile à revendre qu'une SCPI, mais aussi plus sensible aux marchés financiers.",
      fact: { label: "Composition", value: "Immobilier, actifs financiers et liquidités", src: "opcimmo" },
      ask: "Quelle est la répartition actuelle de cet OPCI entre immobilier, actions, obligations et liquidités&nbsp;?" },
    { id: "p2", axis: "Composition", type: "slider",
      min: 0, max: 80, step: 1, start: 15, unit: "%", target: 51, tol: [5, 12], dec: 0, gapUnit: "point",
      real: "51&nbsp;%", realLabel: "Réponse (prospectus OPCIMMO)",
      prompt: "Dans le prospectus d'un grand OPCI grand public, quelle part minimale doit être investie en immobilier non coté&nbsp;?",
      good: "51&nbsp;% au minimum",
      explain: "Le prospectus fixe au moins 51&nbsp;% d'immobilier non coté, avec une cible de 60&nbsp;%. Les actifs financiers peuvent monter jusqu'à 49&nbsp;%, et les liquidités représentent entre 5&nbsp;% et 40&nbsp;%.",
      fact: { label: "Part minimale d'immobilier non coté (exemple OPCIMMO)", value: "51&nbsp;%, cible de 60&nbsp;%", src: "opcimmo" },
      ask: "Quelle part de cet OPCI est réellement investie en immeubles aujourd'hui&nbsp;?" },
    { id: "p3", axis: "Composition", type: "choice",
      prompt: "Pourquoi un OPCI garde-t-il une poche de liquidités (au moins 5&nbsp;% dans cet exemple)&nbsp;?",
      options: ["Pour pouvoir rembourser les épargnants qui veulent sortir, sans vendre un immeuble en urgence", "Pour garantir le capital", "Pour payer l'impôt de ses porteurs", "C'est une obligation fiscale sans utilité"], correct: 0,
      good: "Pour pouvoir rembourser les sorties",
      explain: "Vendre un immeuble prend des mois. Garder de la trésorerie permet de payer les épargnants qui sortent. Mais si les demandes de sortie dépassent cette réserve, les rachats peuvent être étalés.",
      fact: { label: "Liquidités (exemple OPCIMMO)", value: "Entre 5&nbsp;% et 40&nbsp;% de l'actif", src: "opcimmo" },
      ask: "Quelle est la part de liquidités de cet OPCI aujourd'hui&nbsp;?" },
    { id: "p4", axis: "Disponibilité", type: "choice",
      prompt: "Dans cet exemple, en combien de temps êtes-vous remboursé quand vous demandez à sortir&nbsp;?",
      options: ["Immédiatement, toujours", "En 8 jours ouvrés normalement, mais jusqu'à 12 mois en situation exceptionnelle", "Après 10 ans seulement", "Jamais avant la fin du fonds"], correct: 1,
      good: "8 jours ouvrés, jusqu'à 12 mois en cas exceptionnel",
      explain: "Le prospectus prévoit un règlement sous 8 jours ouvrés en temps normal. Si les demandes de sortie sont trop nombreuses, un mécanisme de plafonnement peut étaler les remboursements, sur 12 mois au maximum.",
      fact: { label: "Délai de rachat (exemple OPCIMMO)", value: "8 jours ouvrés, jusqu'à 12 mois en situation exceptionnelle", src: "opcimmo" },
      ask: "Cet OPCI a-t-il déjà plafonné ou étalé des rachats&nbsp;?" },
    { id: "p5", axis: "Frais", type: "choice",
      prompt: "Dans cet exemple, les frais de souscription comprennent une part acquise au fonds (jusqu'à 3,5&nbsp;%) et une part non acquise (jusqu'à 5&nbsp;% pour certaines parts). Sur 10&nbsp;000&nbsp;€, ils peuvent atteindre&nbsp;:",
      options: ["350&nbsp;€", "500&nbsp;€", "850&nbsp;€", "Rien"], correct: 2,
      good: "Jusqu'à 850&nbsp;€",
      explain: "3,5&nbsp;% + 5&nbsp;% = 8,5&nbsp;%, soit 850&nbsp;€ sur 10&nbsp;000&nbsp;€, pour les parts les plus chargées. Ces frais sont prélevés dès le départ&nbsp;: il faut du temps pour les compenser. Les montants exacts dépendent de la part souscrite.",
      fact: { label: "Frais de souscription (exemple OPCIMMO)", value: "Jusqu'à 3,5&nbsp;% acquis au fonds et 5&nbsp;% non acquis selon les parts", src: "opcimmo", note: "Calcul Kompa&nbsp;: 3,5&nbsp;% + 5&nbsp;%." },
      ask: "Quels sont exactement les frais de souscription de la part que vous me proposez&nbsp;?" },
    { id: "p6", axis: "Risque", type: "tf",
      prompt: "Le capital investi dans un OPCI est garanti.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "Le prospectus le dit en toutes lettres&nbsp;: ni le capital investi, ni le niveau de performance ne sont garantis. L'immobilier et les marchés financiers peuvent baisser ensemble.",
      fact: { label: "Garantie", value: "Ni le capital ni la performance ne sont garantis", src: "opcimmo" },
      ask: "Comment la valeur de cet OPCI a-t-elle évolué lors des dernières années difficiles pour l'immobilier&nbsp;?" },
    { id: "p7", axis: "Risque", type: "choice",
      prompt: "Quelle durée de placement minimale recommande ce prospectus&nbsp;?",
      options: ["1 an", "3 ans", "8 ans", "Aucune"], correct: 2,
      good: "8 ans",
      explain: "Le prospectus recommande au moins 8 ans. Les frais d'entrée et les cycles de l'immobilier rendent ce placement peu adapté à une durée courte.",
      fact: { label: "Durée de placement recommandée (exemple OPCIMMO)", value: "8 ans minimum", src: "opcimmo" },
      ask: "Quelle durée de placement recommande la documentation de cet OPCI&nbsp;?" },
  ],
  notes: [
    "Produit générique : les règles chiffrées viennent du prospectus d'un OPCI réel (OPCIMMO, Amundi), présenté comme exemple. Le prospectus consulté n'affiche pas de date : à dater lors de la mise en ligne.",
    "La fiche du Décodeur indique « 60 % à 70 % » d'immobilier et des frais d'entrée « souvent entre 3 % et 5 % » : dans OPCIMMO, au moins 51 % (cible 60 %) et jusqu'à 8,5 % de frais de souscription selon les parts.",
  ],
};

export const fonciere: Bank = {
  id: "fonciere-cotee",
  name: "Foncière cotée (SIIC / REIT, exemple générique)",
  sub: "Produit générique du Décodeur",
  short: "Foncière cotée",
  family: "Immobilier",
  share: "Ma foncière cotée, je la comprends",
  axes: ["Nature", "Revenus", "Disponibilité", "Risque", "Comparaison"],
  src: {
    bofip: { name: "BOFiP, régime des sociétés d'investissements immobiliers cotées (SIIC)", date: "27 mars 2019", url: "https://bofip.impots.gouv.fr/bofip/4486-PGP.html/identifiant=BOI-IS-CHAMP-30-20-20190327", refresh: "Revu à chaque modification du régime" },
    amfscpi: AMF_SCPI,
    fiche: FICHE,
  },
  questions: [
    { id: "r1", axis: "Nature", type: "choice",
      prompt: "En achetant une action de foncière cotée, vous détenez&nbsp;:",
      options: ["Un immeuble en direct", "Une part d'une entreprise cotée en bourse qui possède et loue de l'immobilier", "Une part de SCPI", "Un prêt immobilier"], correct: 1,
      good: "Une action d'entreprise immobilière",
      explain: "Une foncière cotée est une entreprise&nbsp;: elle détient des bureaux, commerces ou entrepôts et les loue. Vous en achetez des actions, en bourse, comme pour n'importe quelle société.",
      fact: { label: "Définition", value: "Une société cotée qui détient et exploite de l'immobilier", src: "fiche" },
      ask: "Quels types d'immeubles cette foncière détient-elle, et dans quels pays&nbsp;?" },
    { id: "r2", axis: "Revenus", type: "slider",
      min: 0, max: 100, step: 1, start: 50, unit: "%", target: 95, tol: [2, 8], dec: 0, gapUnit: "point",
      real: "95&nbsp;%", realLabel: "Réalité (BOFiP)",
      prompt: "En France, une SIIC bénéficie d'un régime fiscal particulier. En échange, quelle part de ses bénéfices de location doit-elle redistribuer&nbsp;?",
      good: "95&nbsp;%",
      explain: "Les bénéfices provenant de la location d'immeubles doivent être distribués à hauteur de 95&nbsp;%, avant la fin de l'exercice suivant. C'est pourquoi les foncières cotées versent en général des dividendes importants.",
      fact: { label: "Obligation de distribution des loyers (SIIC)", value: "95&nbsp;% des bénéfices de location", src: "bofip" },
      ask: "Quel dividende cette foncière a-t-elle versé ces dernières années, et a-t-il varié&nbsp;?" },
    { id: "r3", axis: "Revenus", type: "choice",
      prompt: "Et quand une SIIC vend un immeuble avec une plus-value, quelle part doit-elle redistribuer&nbsp;?",
      options: ["Rien", "70&nbsp;%, dans les deux ans", "100&nbsp;%, immédiatement", "10&nbsp;%"], correct: 1,
      good: "70&nbsp;% dans les deux ans",
      explain: "Les plus-values de cession d'immeubles doivent être distribuées à 70&nbsp;%, dans les deux ans qui suivent. Les dividendes reçus de filiales ayant opté pour le régime doivent, eux, être intégralement redistribués.",
      fact: { label: "Obligation de distribution des plus-values (SIIC)", value: "70&nbsp;%, dans les deux ans", src: "bofip" },
      ask: "Quelle part du dividende de cette foncière vient des loyers, et quelle part de ventes d'immeubles&nbsp;?" },
    { id: "r4", axis: "Disponibilité", type: "choice",
      prompt: "Vous voulez récupérer votre argent. Avec une foncière cotée&nbsp;:",
      options: ["Il faut attendre plusieurs mois, comme pour une SCPI", "Vous vendez vos actions en bourse, chaque jour de cotation, au prix du moment", "C'est impossible avant 8 ans"], correct: 1,
      good: "Vous vendez en bourse, au prix du moment",
      explain: "C'est une action&nbsp;: elle se vend pendant les heures de bourse. À l'inverse, l'AMF rappelle que la revente de parts de SCPI peut prendre plusieurs semaines, voire plusieurs mois. La contrepartie&nbsp;: un prix qui varie chaque jour.",
      fact: { label: "Revente d'une SCPI, pour comparaison", value: "Plusieurs semaines à plusieurs mois", src: "amfscpi" },
      ask: "Quels frais s'appliquent à l'achat et à la vente de cette action&nbsp;?" },
    { id: "r5", axis: "Risque", type: "choice",
      prompt: "Le cours d'une foncière cotée peut baisser même si ses loyers restent stables. Par exemple quand&nbsp;:",
      options: ["Les taux d'intérêt montent", "Les loyers sont encaissés", "L'entreprise verse son dividende"], correct: 0,
      good: "Quand les taux d'intérêt montent",
      explain: "Une hausse des taux renchérit la dette des foncières et rend d'autres placements plus attractifs&nbsp;: la valeur des immeubles et le cours de bourse peuvent baisser, sans que les loyers aient changé.",
      fact: { label: "Sensibilité aux taux", value: "Forte sensibilité aux taux d'intérêt", src: "fiche" },
      ask: "Quel est le niveau d'endettement de cette foncière, et à quel taux&nbsp;?" },
    { id: "r6", axis: "Comparaison", type: "choice",
      prompt: "Foncière cotée ou SCPI&nbsp;: laquelle voit sa valeur bouger chaque jour de bourse&nbsp;?",
      options: ["La SCPI", "La foncière cotée", "Les deux", "Aucune"], correct: 1,
      good: "La foncière cotée",
      explain: "Le cours d'une foncière cotée varie à chaque séance, comme une action. Une SCPI n'a pas de cotation quotidienne&nbsp;: sa valeur bouge moins souvent, mais elle se revend beaucoup moins facilement.",
      fact: { label: "Comportement en bourse", value: "Cours variable chaque jour, comme une action", src: "fiche" },
      ask: "Pourquoi me proposez-vous une foncière cotée plutôt qu'une SCPI, ou l'inverse&nbsp;?" },
    { id: "r7", axis: "Revenus", type: "tf",
      prompt: "Puisqu'une SIIC doit redistribuer 95&nbsp;% de ses bénéfices de location, son dividende est garanti.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "Elle doit redistribuer 95&nbsp;% de ses bénéfices de location, mais ces bénéfices peuvent baisser, par exemple si des locataires partent. Moins de bénéfices, c'est moins de dividende.",
      fact: { label: "Base de l'obligation", value: "Un pourcentage de bénéfices qui peuvent varier", src: "bofip" },
      ask: "Les bénéfices locatifs de cette foncière ont-ils baissé récemment&nbsp;?" },
  ],
  notes: [
    "La fiche du Décodeur indique que les foncières « doivent reverser au moins 85 % de leurs bénéfices locatifs » : le taux est de 95 % (BOFiP du 27 mars 2019). À corriger.",
    "La fiche cite des rendements « de l'ordre de 6 % à 8 % en 2026 » sans source.",
  ],
};

export const IMMOBILIER_BANKS: Bank[] = [scpi, opci, fonciere];
