import type { Bank } from "../types";
import { FICHE, AMF_FRAIS_2017, ECO_GARANTIE } from "../sources";

export const monetaire: Bank = {
  id: "fonds-monetaire-euro",
  name: "Fonds monétaire euro (exemple générique)",
  sub: "Produit générique du Décodeur",
  short: "Fonds monétaire euro",
  family: "Produits monétaires",
  share: "Mon fonds monétaire, je le comprends",
  axes: ["Nature", "Rendement", "Risque", "Frais", "Usage"],
  src: {
    ecb: { name: "Banque centrale européenne, taux €STR", date: "5 oct. 2026", url: "https://www.ecb.europa.eu/stats/financial_markets_and_interest_rates/euro_short-term_rate/html/index.en.html", refresh: "Publié chaque jour ouvré", watch: true },
    amfmmf: { name: "AMF, « L'évolution du marché des fonds monétaires français »", date: "juil. 2023", url: "https://www.amf-france.org/sites/institutionnel/files/private/2023-07/Contenu_Publication_MMF_03072023_vFinal2_0.pdf", refresh: "Revu si l'AMF publie une nouvelle étude" },
    amf17: AMF_FRAIS_2017,
    eco: ECO_GARANTIE,
    fiche: FICHE,
  },
  questions: [
    { id: "m1", axis: "Nature", type: "choice",
      prompt: "Un fonds monétaire investit surtout dans&nbsp;:",
      options: ["Des actions de grandes entreprises", "Des titres de dette à très court terme", "De l'immobilier", "De l'or"], correct: 1,
      good: "De la dette à très court terme",
      explain: "Il prête à très court terme à des États, des banques ou de grandes entreprises. La réglementation encadre la durée de vie moyenne de ces titres&nbsp;: moins de 120 jours pour les fonds monétaires «&nbsp;court terme&nbsp;», moins de 12 mois pour les fonds «&nbsp;standard&nbsp;».",
      fact: { label: "Durée de vie moyenne des titres", value: "Moins de 120 jours (court terme) ou de 12 mois (standard)", src: "amfmmf" },
      ask: "Ce fonds est-il de type « court terme » ou « standard »&nbsp;?" },
    { id: "m2", axis: "Rendement", type: "slider",
      min: 0, max: 6, step: 0.1, start: 4.5, unit: "%", target: 2.438, tol: [0.15, 0.5], dec: 2, gapUnit: "point", fem: false,
      real: "2,438&nbsp;%", realLabel: "Réalité (€STR publié par la BCE pour le 5 oct. 2026)",
      prompt: "Le rendement d'un fonds monétaire suit de près l'€STR, le taux auquel les banques de la zone euro se prêtent au jour le jour. Selon vous, à combien est-il&nbsp;?",
      good: "2,438&nbsp;% par an",
      explain: "L'€STR est publié chaque jour ouvré par la Banque centrale européenne. Le rendement d'un fonds monétaire s'en approche, avant ses frais&nbsp;: il monte et baisse avec les taux de la BCE.",
      fact: { label: "Taux €STR", value: "2,438&nbsp;%", src: "ecb" },
      ask: "Quel a été le rendement de ce fonds sur un an, frais déduits, comparé à l'€STR&nbsp;?" },
    { id: "m3", axis: "Risque", type: "tf",
      prompt: "La valeur d'un fonds monétaire ne peut jamais baisser.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "En France, tous les fonds monétaires sont à valeur liquidative variable&nbsp;: leurs titres sont évalués au prix du marché. Quand les taux étaient négatifs, leurs rendements l'ont été aussi&nbsp;: −0,62&nbsp;% pour les fonds court terme au premier trimestre 2022, selon l'AMF.",
      fact: { label: "Rendement des fonds court terme, 1er trimestre 2022", value: "−0,62&nbsp;%", src: "amfmmf" },
      ask: "Ce fonds a-t-il déjà eu un rendement négatif, et quand&nbsp;?" },
    { id: "m4", axis: "Frais", type: "choice",
      prompt: "Exemple fictif&nbsp;: les titres d'un fonds monétaire rapportent 2,4&nbsp;% par an et ses frais courants sont de 0,25&nbsp;%. Ce que vous touchez, à peu près&nbsp;:",
      options: ["2,65&nbsp;%", "2,4&nbsp;%", "2,15&nbsp;%"], correct: 2,
      good: "Environ 2,15&nbsp;%",
      explain: "Les frais courants sont déduits de la valeur du fonds&nbsp;: 2,4&nbsp;% − 0,25&nbsp;% ≈ 2,15&nbsp;%. Sur un placement qui rapporte peu, quelques dixièmes de frais comptent beaucoup.",
      fact: { label: "Prélèvement des frais courants", value: "Déduits de la valeur liquidative du fonds", src: "amf17", note: "Calcul Kompa sur un exemple fictif." },
      ask: "Quels sont les frais courants de ce fonds, et ceux de l'enveloppe qui le contient&nbsp;?" },
    { id: "m5", axis: "Rendement", type: "choice",
      prompt: "La BCE baisse ses taux. Le rendement de votre fonds monétaire&nbsp;:",
      options: ["Reste bloqué au niveau de votre achat", "Baisse assez vite, car ses titres très courts sont remplacés par de nouveaux, moins rémunérés", "Monte"], correct: 1,
      good: "Il baisse assez vite",
      explain: "Les titres arrivent vite à échéance et sont remplacés par de nouveaux, au taux du moment. L'AMF a ainsi observé une baisse progressive des rendements des fonds monétaires entre 2020 et début 2022, quand les liquidités abondaient.",
      fact: { label: "Lien avec les taux", value: "Les rendements suivent les taux de marché, avec peu de décalage", src: "amfmmf" },
      ask: "Comment le rendement de ce fonds a-t-il évolué depuis la dernière décision de la BCE&nbsp;?" },
    { id: "m6", axis: "Usage", type: "choice",
      prompt: "À quoi sert en général un fonds monétaire&nbsp;?",
      options: ["Faire fructifier fortement son épargne sur 20 ans", "Placer de l'argent à court terme, en visant la stabilité plutôt que la performance", "Remplacer un compte courant", "Spéculer sur les devises"], correct: 1,
      good: "Placer à court terme, en visant la stabilité",
      explain: "Il sert souvent de zone d'attente&nbsp;: de l'argent dont on pourrait avoir besoin bientôt, ou en attente d'être investi. Son rendement suit les taux courts&nbsp;; il n'est pas conçu pour faire grossir l'épargne sur le long terme.",
      fact: { label: "Usage", value: "Placement de court terme, orienté sécurité", src: "fiche" },
      ask: "Pourquoi me proposez-vous ce fonds plutôt qu'un livret, pour quelle durée&nbsp;?" },
    { id: "m7", axis: "Risque", type: "choice",
      prompt: "Fonds monétaire ou Livret A&nbsp;: lequel bénéficie d'une garantie totale de l'État&nbsp;?",
      options: ["Le fonds monétaire", "Le Livret A", "Les deux", "Aucun"], correct: 1,
      good: "Le Livret A",
      explain: "Le Livret A est garanti en totalité par l'État. Un fonds monétaire est un placement financier&nbsp;: sa valeur n'est pas garantie, même si elle varie en général très peu.",
      fact: { label: "Garantie de l'État", value: "Livret A, LDDS et LEP garantis en totalité par l'État", src: "eco" },
      ask: "Quelle est la différence de rendement net entre ce fonds et un livret réglementé, après fiscalité&nbsp;?" },
  ],
  notes: [
    "La fiche du Décodeur cite l'€STR « autour de 2,2 % fin août 2026 » : il est à 2,438 % au 5 octobre 2026 (BCE), après la hausse de taux de la BCE de septembre.",
  ],
};

export const cat: Bank = {
  id: "compte-a-terme",
  name: "Compte à terme (CAT)",
  sub: "Produit générique du Décodeur",
  short: "Compte à terme",
  family: "Produits monétaires",
  share: "Mon compte à terme, je le comprends",
  axes: ["Nature", "Disponibilité", "Sécurité", "Taux", "Rendement"],
  src: { eco: ECO_GARANTIE, fiche: FICHE },
  questions: [
    { id: "k1", axis: "Nature", type: "choice",
      prompt: "Un compte à terme, c'est&nbsp;:",
      options: ["Un livret disponible à tout moment", "Une somme bloquée pour une durée fixée à l'avance, contre un taux connu dès la souscription", "Un placement en bourse", "Un crédit"], correct: 1,
      good: "Une somme bloquée, à taux connu",
      explain: "Vous immobilisez une somme pour quelques mois ou quelques années. En échange, la banque vous garantit dès le départ le taux d'intérêt prévu au contrat.",
      fact: { label: "Définition", value: "Somme bloquée pour une durée fixée, taux connu à l'avance", src: "fiche" },
      ask: "Quelle est la durée exacte et le taux brut de ce compte à terme&nbsp;?" },
    { id: "k2", axis: "Disponibilité", type: "choice",
      prompt: "Vous avez besoin de l'argent avant l'échéance. En général&nbsp;:",
      options: ["Vous le récupérez avec tous les intérêts prévus", "Un retrait est souvent possible, mais vous perdez une partie des intérêts, voire payez une pénalité&nbsp;; certains contrats l'interdisent", "C'est toujours impossible"], correct: 1,
      good: "Possible, mais vous perdez des intérêts",
      explain: "C'est la contrepartie du taux garanti&nbsp;: l'argent est prévu pour rester jusqu'à l'échéance. Les conditions de sortie anticipée varient d'un contrat à l'autre&nbsp;: elles sont à lire avant de souscrire.",
      fact: { label: "Sortie anticipée", value: "Souvent pénalisée, parfois impossible selon le contrat", src: "fiche" },
      ask: "Que se passe-t-il exactement si je retire mon argent avant l'échéance&nbsp;?" },
    { id: "k3", axis: "Sécurité", type: "slider",
      min: 0, max: 250000, step: 10000, start: 30000, unit: "€", target: 100000, tol: [5000, 25000], dec: 0, gapUnit: "€", fem: false,
      real: "100&nbsp;000&nbsp;€", realLabel: "Réalité (plafond de la garantie des dépôts)",
      prompt: "Si votre banque faisait faillite, jusqu'à quel montant vos dépôts y seraient-ils couverts par la garantie des dépôts&nbsp;?",
      good: "100&nbsp;000&nbsp;€",
      explain: "La garantie couvre 100&nbsp;000&nbsp;€ par déposant et par établissement, comptes à terme compris. Au-delà, la somme n'est pas couverte par ce mécanisme.",
      fact: { label: "Plafond de la garantie des dépôts", value: "100&nbsp;000&nbsp;€ par déposant et par établissement", src: "eco" },
      ask: "Mes dépôts dans cette banque dépassent-ils le plafond de la garantie, tous comptes confondus&nbsp;?" },
    { id: "k4", axis: "Sécurité", type: "choice",
      prompt: "Vous avez 80&nbsp;000&nbsp;€ sur un compte à terme et 50&nbsp;000&nbsp;€ sur un livret bancaire non réglementé, dans la même banque. Quel montant est couvert par la garantie des dépôts&nbsp;?",
      options: ["130&nbsp;000&nbsp;€", "100&nbsp;000&nbsp;€", "80&nbsp;000&nbsp;€", "50&nbsp;000&nbsp;€"], correct: 1,
      good: "100&nbsp;000&nbsp;€",
      explain: "Le plafond s'applique par déposant et par établissement, quel que soit le nombre de comptes. Les 130&nbsp;000&nbsp;€ réunis ne sont couverts qu'à hauteur de 100&nbsp;000&nbsp;€.",
      fact: { label: "Calcul du plafond", value: "Tous comptes confondus, dans un même établissement", src: "eco" },
      ask: "Les différentes marques de votre groupe bancaire comptent-elles comme un seul établissement pour la garantie&nbsp;?" },
    { id: "k5", axis: "Taux", type: "choice",
      prompt: "Les taux du marché montent juste après votre souscription. Votre compte à terme&nbsp;:",
      options: ["S'aligne automatiquement sur les nouveaux taux", "Garde le taux prévu au contrat jusqu'à l'échéance", "Devient remboursable sans pénalité"], correct: 1,
      good: "Il garde son taux",
      explain: "Le taux est figé&nbsp;: c'est rassurant quand les taux baissent, frustrant quand ils montent. Pour profiter de taux plus élevés, il faudrait sortir avant l'échéance, avec les pénalités prévues.",
      fact: { label: "Taux", value: "Figé jusqu'à l'échéance", src: "fiche" },
      ask: "Le taux est-il fixe sur toute la durée, ou progressif&nbsp;?" },
    { id: "k6", axis: "Rendement", type: "choice",
      prompt: "Exemple fictif&nbsp;: 10&nbsp;000&nbsp;€ placés 6 mois à un taux annuel de 3&nbsp;%. Les intérêts bruts sont d'environ&nbsp;:",
      options: ["300&nbsp;€", "150&nbsp;€", "30&nbsp;€", "3&nbsp;€"], correct: 1,
      good: "Environ 150&nbsp;€",
      explain: "Un taux annuel s'applique à une année entière. Sur 6 mois, on touche environ la moitié&nbsp;: 3&nbsp;% × 10&nbsp;000&nbsp;€ × 6/12 = 150&nbsp;€, avant impôts et prélèvements sociaux.",
      fact: { label: "Taux annuel et durée", value: "Les intérêts dépendent du taux annuel et de la durée réelle du placement", src: "fiche", note: "Calcul Kompa sur un exemple fictif, avant fiscalité." },
      ask: "Le taux annoncé est-il annuel, et quel montant d'intérêts toucherai-je réellement à l'échéance, après impôts&nbsp;?" },
    { id: "k7", axis: "Sécurité", type: "tf",
      prompt: "Votre Livret A compte dans le plafond de 100&nbsp;000&nbsp;€ de la garantie des dépôts.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "Le Livret A, le LDDS et le LEP sont garantis en totalité par l'État, à part&nbsp;: ils ne comptent pas dans le plafond de 100&nbsp;000&nbsp;€.",
      fact: { label: "Livrets réglementés", value: "Garantis en totalité par l'État, hors plafond", src: "eco" },
      ask: "Comment se répartit mon épargne entre comptes couverts par la garantie et livrets réglementés&nbsp;?" },
  ],
  notes: [
    "La fiche du Décodeur indique une fiscalité « flat tax de 30 % en général ». Plusieurs sources indiquent que le prélèvement forfaitaire unique est passé à 31,4 % en 2026 ; je ne l'ai pas confirmé sur un site officiel. À vérifier avant toute mise à jour de la fiche.",
    "La fiche cite des taux « de 1,8 % à un peu plus de 3 % » en 2026, sans source.",
  ],
};

export const livret: Bank = {
  id: "livret-reglemente",
  name: "Livret bancaire réglementé (Livret A)",
  sub: "Produit générique du Décodeur",
  short: "Livret A",
  family: "Produits monétaires",
  share: "Mon Livret A, je le comprends",
  axes: ["Nature", "Rendement", "Fiscalité", "Plafond", "Usage"],
  src: {
    sp: { name: "Service-public.gouv.fr, fiche « Livret A »", date: "vérifiée le 1er août 2026", url: "https://www.service-public.gouv.fr/particuliers/vosdroits/F2365", refresh: "Revu à chaque révision du taux", watch: true },
    eco: { name: "Ministère de l'Économie, communiqué sur l'épargne réglementée", date: "15 juil. 2026", url: "https://presse.economie.gouv.fr/?p=181486", refresh: "Revu à chaque révision semestrielle", watch: true },
    fiche: FICHE,
  },
  questions: [
    { id: "a1", axis: "Nature", type: "choice",
      prompt: "Qui fixe le taux du Livret A&nbsp;?",
      options: ["Chaque banque, librement", "Les pouvoirs publics, qui le réexaminent tous les six mois", "La Banque centrale européenne, chaque mois", "Personne&nbsp;: il est fixé une fois pour toutes"], correct: 1,
      good: "Les pouvoirs publics, tous les six mois",
      explain: "Le taux est fixé par les pouvoirs publics et réexaminé tous les six mois. Il tient compte de l'inflation des douze derniers mois (hors tabac) et du niveau moyen des taux entre banques de la zone euro.",
      fact: { label: "Fixation du taux", value: "Réexaminé tous les six mois, selon l'inflation et les taux interbancaires", src: "eco" },
      ask: "Quand le taux de mon livret a-t-il changé pour la dernière fois&nbsp;?" },
    { id: "a2", axis: "Rendement", type: "slider",
      min: 0, max: 5, step: 0.1, start: 2.5, unit: "%", target: 1.7, tol: [0.1, 0.5], dec: 1, gapUnit: "point", fem: false,
      real: "1,7&nbsp;%", realLabel: "Taux en vigueur depuis le 1er août 2026",
      prompt: "Quel est le taux du Livret A depuis le 1er août 2026&nbsp;?",
      good: "1,7&nbsp;% par an",
      explain: "Le taux est passé de 1,5&nbsp;% à 1,7&nbsp;% le 1er août 2026. Sur 10&nbsp;000&nbsp;€ laissés toute une année, cela ferait environ 170&nbsp;€ d'intérêts si le taux ne changeait pas, sans impôt à payer.",
      fact: { label: "Taux du Livret A", value: "1,7&nbsp;% par an depuis le 1er août 2026", src: "eco", note: "Taux confirmé par service-public.gouv.fr, page vérifiée le 1er août 2026." },
      ask: "Le taux de mon livret a-t-il changé depuis son ouverture&nbsp;?" },
    { id: "a3", axis: "Fiscalité", type: "choice",
      prompt: "Sur les intérêts du Livret A, vous payez&nbsp;:",
      options: ["L'impôt sur le revenu et les prélèvements sociaux", "Seulement les prélèvements sociaux", "Rien&nbsp;: ils sont exonérés des deux", "Une taxe au moment du retrait"], correct: 2,
      good: "Rien, ils sont exonérés",
      explain: "Les intérêts du Livret A sont exonérés d'impôt sur le revenu et de prélèvements sociaux. Le taux affiché est donc aussi ce que vous touchez.",
      fact: { label: "Fiscalité des intérêts", value: "Exonérés d'impôt sur le revenu et de prélèvements sociaux", src: "sp" },
      ask: "Comment sont imposés les intérêts de mes autres placements d'épargne&nbsp;?" },
    { id: "a4", axis: "Rendement", type: "choice",
      prompt: "Vous déposez 1&nbsp;000&nbsp;€ le 3 mai. À partir de quand rapportent-ils des intérêts&nbsp;?",
      options: ["Dès le 3 mai", "À partir du 16 mai", "À partir du 1er juin", "Seulement au 31 décembre"], correct: 1,
      good: "À partir du 16 mai",
      explain: "Les intérêts se calculent par quinzaine entière. Un dépôt fait entre le 1er et le 15 du mois compte à partir du 16&nbsp;; un dépôt fait à partir du 16 compte le 1er du mois suivant. Les intérêts de l'année s'ajoutent au capital le 31 décembre.",
      fact: { label: "Calcul des intérêts", value: "Par quinzaine entière, ajoutés au capital le 31 décembre", src: "sp" },
      ask: "Comment les quinzaines s'appliquent-elles à mes dépôts et à mes retraits&nbsp;?" },
    { id: "a5", axis: "Plafond", type: "tf",
      prompt: "Votre Livret A a atteint son plafond de 22&nbsp;950&nbsp;€. Les intérêts cessent alors de s'ajouter.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "Le plafond limite les dépôts, pas les intérêts. Une fois le plafond atteint, vous ne pouvez plus déposer, mais les intérêts continuent de s'ajouter chaque année, même au-delà de 22&nbsp;950&nbsp;€.",
      fact: { label: "Plafond pour un particulier", value: "22&nbsp;950&nbsp;€ de dépôts, que les intérêts peuvent dépasser", src: "sp" },
      ask: "Quels sont les plafonds des autres livrets réglementés auxquels j'ai droit&nbsp;?" },
    { id: "a6", axis: "Usage", type: "choice",
      prompt: "À quoi sert l'argent déposé sur les Livrets A&nbsp;?",
      options: ["Il reste dans le coffre de votre banque", "Il finance notamment le logement social, des PME et la transition écologique", "Il est placé en bourse", "Il finance uniquement le budget de l'État"], correct: 1,
      good: "Le logement social, des PME, la transition écologique",
      explain: "Selon le ministère de l'Économie, cette épargne finance le logement social et la politique de la ville, mais aussi des PME françaises, la transition écologique, l'économie sociale et solidaire et le renouvellement du parc nucléaire.",
      fact: { label: "Usage de l'épargne réglementée", value: "Logement social, PME, transition écologique, nucléaire, entre autres", src: "eco" },
      ask: "Où va l'argent de mes livrets qui ne sont pas réglementés&nbsp;?" },
    { id: "a7", axis: "Rendement", type: "choice",
      prompt: "Si l'inflation dépasse le taux du Livret A pendant un an, votre pouvoir d'achat&nbsp;:",
      options: ["Augmente quand même, puisque vous touchez des intérêts", "Baisse, même si votre solde augmente", "Reste exactement le même"], correct: 1,
      good: "Il baisse, même si le solde augmente",
      explain: "Votre solde progresse, mais les prix montent plus vite&nbsp;: avec la même somme, vous achetez un peu moins qu'avant. Le solde en euros ne baisse pas, son pouvoir d'achat si.",
      fact: { label: "Taux et inflation", value: "Si l'inflation dépasse le taux, le pouvoir d'achat recule", src: "fiche" },
      ask: "Quel a été le rendement de mon livret une fois l'inflation déduite ces dernières années&nbsp;?" },
  ],
  notes: [
    "Meilleur exemple de « fait périssable » : le taux est réexaminé tous les six mois. Quand il change, mettre à jour la date de la source « eco » et « sp » fait repasser ces faits « à revoir » dans les cartes.",
  ],
};

export const MONETAIRES_BANKS: Bank[] = [monetaire, cat, livret];
