import type { Bank } from "../types";
import { FICHE, AMF_OBLIGATIONS } from "../sources";

const TREASURY_DIRECT = {
  name: "TreasuryDirect (Trésor américain), page « Treasury Notes »",
  date: "consultée le 7 oct. 2026",
  url: "https://www.treasurydirect.gov/marketable-securities/treasury-notes/",
  refresh: "Revu si le Trésor américain modifie ses règles",
};

export const oat: Bank = {
  id: "oat-france",
  name: "Obligation d'État française (OAT) à 10 ans",
  sub: "Produit générique du Décodeur",
  short: "OAT à 10 ans",
  family: "Obligations",
  share: "Mon OAT, je la comprends",
  axes: ["Nature", "Revenus", "Risque", "Horizon", "Accès"],
  src: { amfobl: AMF_OBLIGATIONS, fiche: FICHE },
  questions: [
    { id: "o1", axis: "Nature", type: "choice",
      prompt: "Acheter une OAT, c'est&nbsp;:",
      options: ["Devenir actionnaire de l'État", "Prêter de l'argent à l'État français, qui verse des intérêts et rembourse à l'échéance", "Ouvrir un livret garanti par l'État", "Acheter une part d'un fonds d'actions françaises"], correct: 1,
      good: "Prêter de l'argent à l'État",
      explain: "Une OAT (obligation assimilable du Trésor) est un titre de dette&nbsp;: vous prêtez à l'État pour une durée fixée, ici 10 ans, contre un intérêt annuel, le coupon, et le remboursement à l'échéance.",
      fact: { label: "Nature d'une OAT", value: "Un prêt à l'État français pour une durée fixée", src: "fiche" },
      ask: "Quelle est la date d'échéance exacte de cette OAT, et à quel prix l'achèterais-je&nbsp;?" },
    { id: "o2", axis: "Revenus", type: "choice",
      prompt: "Exemple fictif&nbsp;: une OAT de 1&nbsp;000&nbsp;€ verse un coupon de 3&nbsp;% par an. Vous recevez chaque année&nbsp;:",
      options: ["3&nbsp;€", "30&nbsp;€", "300&nbsp;€", "Un montant qui varie avec la bourse"], correct: 1,
      good: "30&nbsp;€",
      explain: "Le coupon est fixé à l'émission et calculé sur la valeur de remboursement&nbsp;: 3&nbsp;% de 1&nbsp;000&nbsp;€, soit 30&nbsp;€ par an, quel que soit ensuite le prix de l'OAT en bourse. C'est ce qui rend son revenu prévisible.",
      fact: { label: "Coupon d'une obligation classique", value: "Fixé à l'émission, il ne change plus ensuite", src: "amfobl", note: "Exemple fictif&nbsp;: 3&nbsp;% n'est pas le taux actuel des OAT." },
      ask: "Quel est le coupon de cette OAT, et à quelle date est-il versé&nbsp;?" },
    { id: "o3", axis: "Risque", type: "choice",
      prompt: "Vous avez acheté une OAT. Les taux d'intérêt montent ensuite. Si vous la revendez avant l'échéance, son prix&nbsp;:",
      options: ["Monte", "Baisse", "Ne bouge pas, puisque c'est l'État"], correct: 1,
      good: "Il baisse",
      explain: "Quand les taux montent, de nouvelles obligations sont émises avec des coupons plus élevés. Les anciennes, moins rémunératrices, intéressent moins&nbsp;: leur prix baisse. L'AMF précise que la perte ne se concrétise que si l'on revend avant l'échéance.",
      fact: { label: "Taux et prix des obligations", value: "Quand les taux montent, le prix des obligations déjà émises baisse", src: "amfobl" },
      ask: "Si je devais revendre avant l'échéance, à quel prix pourrais-je le faire aujourd'hui&nbsp;?" },
    { id: "o4", axis: "Horizon", type: "choice",
      prompt: "Vous gardez l'OAT jusqu'à son échéance. Vous récupérez&nbsp;:",
      options: ["Le prix du marché le jour de l'échéance", "La valeur de remboursement prévue, sauf défaut de l'État", "Votre mise augmentée de l'inflation des 10 ans", "Rien de prévu à l'avance"], correct: 1,
      good: "La valeur de remboursement prévue",
      explain: "À l'échéance, l'obligation est remboursée à sa valeur prévue&nbsp;: selon l'AMF, l'investisseur récupère sa mise de départ, sauf insolvabilité de l'émetteur. Les variations de prix entre-temps ne comptent que si vous revendez avant.",
      fact: { label: "Conservation jusqu'à l'échéance", value: "Remboursement de la mise de départ, sauf insolvabilité de l'émetteur", src: "amfobl", note: "Si l'OAT est achetée en cours de vie, le prix payé peut différer de sa valeur de remboursement." },
      ask: "Si j'achète cette OAT en cours de vie, quelle est sa valeur de remboursement&nbsp;?" },
    { id: "o5", axis: "Risque", type: "tf",
      prompt: "Une OAT ne présente absolument aucun risque, puisque c'est l'État qui emprunte.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "Le risque que l'État ne rembourse pas est généralement jugé faible, mais il n'est pas nul&nbsp;: l'AMF précise que le remboursement à l'échéance vaut sauf insolvabilité de l'émetteur. S'y ajoutent le risque de taux si vous revendez avant, et l'inflation.",
      fact: { label: "Risque de crédit", value: "Faible mais pas nul&nbsp;: le remboursement dépend de l'émetteur", src: "amfobl" },
      ask: "Quelle est la note actuelle de la dette française, et que changerait une baisse de cette note pour mon OAT&nbsp;?" },
    { id: "o6", axis: "Revenus", type: "choice",
      prompt: "L'inflation est plus forte que prévu pendant 10 ans. Le coupon de votre OAT classique&nbsp;:",
      options: ["Augmente automatiquement", "Reste le même, mais il permet d'acheter moins de choses", "Est suspendu"], correct: 1,
      good: "Il reste le même",
      explain: "Le coupon d'une OAT classique est fixe&nbsp;: il ne suit pas les prix. Si l'inflation grimpe, ces euros fixes perdent du pouvoir d'achat, année après année.",
      fact: { label: "Coupon fixe et inflation", value: "Le coupon ne suit pas l'inflation", src: "fiche" },
      ask: "Ce placement me protège-t-il contre l'inflation&nbsp;?" },
    { id: "o7", axis: "Accès", type: "choice",
      prompt: "Comment un particulier détient-il le plus souvent des obligations d'État&nbsp;?",
      options: ["Uniquement au guichet du Trésor public", "Via un fonds obligataire ou un fonds diversifié, par exemple en assurance-vie", "Sur un livret d'épargne", "C'est impossible pour un particulier"], correct: 1,
      good: "Via un fonds, souvent en assurance-vie",
      explain: "Le plus souvent, on y accède indirectement. L'AMF cite les fonds et Sicav obligataires, ainsi que les fonds diversifiés dits prudents, qui détiennent beaucoup d'obligations et sont accessibles notamment en assurance-vie.",
      fact: { label: "Accès pour un particulier", value: "Souvent via des fonds obligataires ou diversifiés", src: "amfobl" },
      ask: "Dans mon assurance-vie, quels supports détiennent des obligations d'État, et avec quels frais&nbsp;?" },
  ],
  notes: [
    "La fiche du Décodeur indique un rendement des OAT à 10 ans « autour de 4,5 % courant 2026 », sans source ni date précise. À sourcer (Banque de France, indice TEC 10) ou à retirer.",
    "Le test évite volontairement tout chiffre de marché : il reste juste même quand les taux bougent.",
  ],
};

export const treasury: Bank = {
  id: "treasury-us",
  name: "Obligation du Trésor américain (US Treasury) à 10 ans",
  sub: "Produit générique du Décodeur",
  short: "Obligation du Trésor américain",
  family: "Obligations",
  share: "Mon obligation du Trésor américain, je la comprends",
  axes: ["Nature", "Revenus", "Risque", "Change", "Accès"],
  src: { td: TREASURY_DIRECT, amfobl: AMF_OBLIGATIONS, fiche: FICHE },
  questions: [
    { id: "y1", axis: "Nature", type: "choice",
      prompt: "Une obligation du Trésor américain à 10 ans (une «&nbsp;Treasury note&nbsp;»), c'est&nbsp;:",
      options: ["Une action de l'État américain", "Un prêt à l'État américain pour 10 ans, rémunéré par des intérêts", "Un compte en dollars garanti", "Un fonds d'actions américaines"], correct: 1,
      good: "Un prêt à l'État américain",
      explain: "Le Trésor américain émet des «&nbsp;notes&nbsp;» de 2, 3, 5, 7 ou 10 ans. Vous lui prêtez de l'argent, il vous verse des intérêts puis vous rembourse à l'échéance.",
      fact: { label: "Durées des Treasury notes", value: "2, 3, 5, 7 ou 10 ans", src: "td" },
      ask: "Quelle est l'échéance exacte de l'obligation que l'on me propose&nbsp;?" },
    { id: "y2", axis: "Revenus", type: "choice",
      prompt: "À quel rythme le Trésor américain verse-t-il les intérêts de ces obligations&nbsp;?",
      options: ["Chaque mois", "Tous les six mois", "Une seule fois, à l'échéance", "Chaque année"], correct: 1,
      good: "Tous les six mois",
      explain: "Les intérêts sont versés tous les six mois jusqu'à l'échéance. Ils sont payés en dollars&nbsp;: leur montant en euros dépend aussi du taux de change au moment du versement.",
      fact: { label: "Versement des intérêts", value: "Tous les six mois jusqu'à l'échéance", src: "td" },
      ask: "Comment ces intérêts en dollars arrivent-ils sur mon compte, et à quel taux de change&nbsp;?" },
    { id: "y3", axis: "Revenus", type: "tf",
      prompt: "Le taux d'intérêt d'une Treasury note à 10 ans est revu chaque année.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "Le taux est fixé lors de l'adjudication, quand l'État emprunte, et ne change plus pendant toute la vie de l'obligation. C'est le prix de l'obligation sur le marché qui varie ensuite, pas son taux.",
      fact: { label: "Taux d'intérêt", value: "Fixé à l'adjudication, inchangé jusqu'à l'échéance", src: "td" },
      ask: "À quel prix, et donc à quel rendement réel, achèterais-je cette obligation aujourd'hui&nbsp;?" },
    { id: "y4", axis: "Risque", type: "choice",
      prompt: "Vous détenez une obligation du Trésor américain. Les taux américains montent. Si vous revendez avant l'échéance, son prix&nbsp;:",
      options: ["Monte", "Baisse", "Ne bouge pas, puisque c'est l'État américain"], correct: 1,
      good: "Il baisse",
      explain: "Comme pour toute obligation à taux fixe, de nouvelles émissions plus rémunératrices rendent les anciennes moins attractives&nbsp;: leur prix baisse. La perte ne se concrétise que si vous revendez avant l'échéance.",
      fact: { label: "Taux et prix des obligations", value: "Quand les taux montent, le prix des obligations déjà émises baisse", src: "amfobl" },
      ask: "Si je devais revendre avant l'échéance, à quel prix pourrais-je le faire aujourd'hui&nbsp;?" },
    { id: "y5", axis: "Change", type: "choice",
      prompt: "L'État américain vous rembourse comme prévu. Pour vous, épargnant en euros, le résultat final dépend aussi&nbsp;:",
      options: ["Du taux de change entre le dollar et l'euro", "Du CAC 40", "De rien d'autre"], correct: 0,
      good: "Du taux de change",
      explain: "Vous êtes remboursé en dollars. Si le dollar a baissé face à l'euro entre l'achat et le remboursement, vous récupérez moins d'euros que prévu, même sans aucun défaut de l'État américain. L'inverse est vrai si le dollar monte.",
      fact: { label: "Risque de change", value: "Coupons et remboursement en dollars", src: "fiche" },
      ask: "Existe-t-il des fonds d'obligations américaines couverts contre le risque de change, et à quel coût&nbsp;?" },
    { id: "y6", axis: "Accès", type: "choice",
      prompt: "Peut-on revendre une Treasury note avant son échéance&nbsp;?",
      options: ["Non, jamais", "Oui, sur le marché, à un prix qui peut être supérieur ou inférieur au prix d'achat", "Oui, au prix d'achat garanti"], correct: 1,
      good: "Oui, au prix du marché",
      explain: "Le Trésor américain l'indique&nbsp;: on peut garder l'obligation jusqu'à l'échéance ou la vendre avant. Dans ce cas, c'est le prix du marché qui s'applique, selon l'évolution des taux depuis l'achat.",
      fact: { label: "Revente avant l'échéance", value: "Possible, au prix du marché", src: "td" },
      ask: "Quels frais s'appliquent si je revends avant l'échéance&nbsp;?" },
    { id: "y7", axis: "Accès", type: "choice",
      prompt: "Comment un épargnant français s'expose-t-il le plus souvent à ces obligations&nbsp;?",
      options: ["En ouvrant un compte au Trésor américain", "Via un fonds ou un ETF obligataire", "Via un livret en dollars", "C'est impossible"], correct: 1,
      good: "Via un fonds ou un ETF",
      explain: "L'AMF le rappelle&nbsp;: on investit le plus souvent en obligations en achetant des parts de fonds et Sicav obligataires. Un tel fonds détient de nombreuses obligations, d'échéances différentes&nbsp;: son prix varie en continu, sans date de remboursement unique.",
      fact: { label: "Accès pour un particulier", value: "Le plus souvent via des fonds obligataires", src: "amfobl" },
      ask: "Quel fonds me proposez-vous pour m'exposer à ces obligations, et quelles sont ses échéances&nbsp;?" },
  ],
  notes: [
    "La fiche du Décodeur cite un rendement « autour de 4,5 % à 5 % courant 2026 » sans source ni date : à sourcer ou à retirer.",
  ],
};

export const entreprise: Bank = {
  id: "obligation-entreprise",
  name: "Obligation d'entreprise (investment grade)",
  sub: "Produit générique du Décodeur",
  short: "Obligation d'entreprise",
  family: "Obligations",
  share: "Mon obligation d'entreprise, je la comprends",
  axes: ["Nature", "Rendement", "Notation", "Risque", "Accès"],
  src: {
    bdf: { name: "Banque de France, fiche « Le financement obligataire »", date: "mai 2021", url: "https://www.banque-france.fr/system/files/2024-04/823415%20Fiche-321.pdf", refresh: "Revu si la Banque de France met à jour la fiche" },
    spgr: { name: "S&P Global Ratings, « Understanding Credit Ratings »", date: "consultée le 7 oct. 2026", url: "https://www.spglobal.com/ratings/en/about/understanding-credit-ratings", refresh: "Revu si l'échelle de notation change" },
    amfobl: AMF_OBLIGATIONS,
    fiche: FICHE,
  },
  questions: [
    { id: "b1", axis: "Nature", type: "choice",
      prompt: "Une obligation d'entreprise, c'est&nbsp;:",
      options: ["Une part du capital de l'entreprise", "Un prêt à l'entreprise, qui verse des intérêts et rembourse à une date prévue", "Un dépôt garanti par l'État", "Un engagement d'achat de ses produits"], correct: 1,
      good: "Un prêt à l'entreprise",
      explain: "La Banque de France la définit comme un titre de créance représentatif d'un emprunt. L'entreprise verse un intérêt, le coupon, puis rembourse, en général en une fois à l'échéance. Vous êtes créancier, pas actionnaire.",
      fact: { label: "Définition", value: "Titre de créance représentatif d'un emprunt", src: "bdf" },
      ask: "Quelle entreprise émet cette obligation, et quelle est son échéance&nbsp;?" },
    { id: "b2", axis: "Rendement", type: "choice",
      prompt: "Pourquoi une entreprise paie-t-elle en général un taux plus élevé qu'un État comparable&nbsp;?",
      options: ["Parce qu'elle est plus généreuse", "Parce que le risque qu'elle ne rembourse pas est jugé plus élevé&nbsp;: les prêteurs demandent une compensation", "Parce que la loi l'y oblige", "Ce n'est jamais le cas"], correct: 1,
      good: "Pour compenser un risque plus élevé",
      explain: "Plus l'émetteur est jugé risqué, plus le taux demandé par les investisseurs est élevé. Un rendement plus fort n'est donc pas un cadeau&nbsp;: c'est la rémunération d'un risque supplémentaire.",
      fact: { label: "Risque et taux", value: "Plus l'émetteur est risqué, plus le taux demandé est élevé", src: "bdf" },
      ask: "Quel écart de rendement cette obligation offre-t-elle par rapport à une obligation d'État de même durée, et pourquoi&nbsp;?" },
    { id: "b3", axis: "Notation", type: "choice",
      prompt: "Chez S&P Global Ratings, les obligations dites «&nbsp;investment grade&nbsp;» sont celles notées&nbsp;:",
      options: ["AAA uniquement", "De AAA à BBB-", "BB+ et en dessous", "Celles qui n'ont pas de note"], correct: 1,
      good: "De AAA à BBB-",
      explain: "Investment grade va de AAA à BBB-, la note la plus basse de cette catégorie. À partir de BB+, on parle de catégorie spéculative, ou «&nbsp;high yield&nbsp;»&nbsp;: un risque de non-remboursement nettement plus élevé.",
      fact: { label: "Catégorie investment grade (S&P)", value: "De AAA à BBB-", src: "spgr" },
      ask: "Quelle est la note de cette obligation, et chez quelle agence&nbsp;?" },
    { id: "b4", axis: "Notation", type: "tf",
      prompt: "Une bonne note de crédit garantit que l'entreprise remboursera.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "S&P Global Ratings le dit lui-même&nbsp;: une note est une opinion sur la probabilité qu'un émetteur rembourse à temps et en totalité, pas une garantie. Elle peut aussi être abaissée en cours de route.",
      fact: { label: "Ce qu'est une note", value: "Une opinion sur la probabilité de remboursement, pas une garantie", src: "spgr" },
      ask: "Cette note a-t-elle évolué récemment&nbsp;?" },
    { id: "b5", axis: "Risque", type: "choice",
      prompt: "La situation financière de l'entreprise se dégrade. Le prix de son obligation sur le marché&nbsp;:",
      options: ["Monte", "Baisse", "Ne bouge pas jusqu'à l'échéance"], correct: 1,
      good: "Il baisse",
      explain: "La Banque de France l'explique&nbsp;: la valeur des obligations diminue lorsque le risque de défaillance de l'émetteur augmente. Si vous devez revendre à ce moment-là, vous récupérez moins.",
      fact: { label: "Risque de l'émetteur et prix", value: "La valeur baisse quand le risque de défaillance augmente", src: "bdf" },
      ask: "Que se passerait-il pour mon placement si l'entreprise faisait défaut&nbsp;?" },
    { id: "b6", axis: "Risque", type: "choice",
      prompt: "Les taux d'intérêt montent sur les marchés. Le prix de votre obligation à taux fixe&nbsp;:",
      options: ["Monte", "Baisse", "Ne bouge pas"], correct: 1,
      good: "Il baisse",
      explain: "Les nouvelles obligations offrent des coupons plus élevés&nbsp;: les anciennes intéressent moins et leur prix baisse. Gardée jusqu'à l'échéance, l'obligation est remboursée comme prévu, si l'entreprise ne fait pas défaut.",
      fact: { label: "Taux et prix des obligations", value: "Quand les taux montent, le prix des obligations déjà émises baisse", src: "amfobl" },
      ask: "Quelle est la durée restante de cette obligation, et à quel point son prix réagit-il aux taux&nbsp;?" },
    { id: "b7", axis: "Accès", type: "choice",
      prompt: "Comment un particulier s'expose-t-il le plus souvent aux obligations d'entreprises&nbsp;?",
      options: ["En prêtant directement à l'entreprise", "Via un fonds obligataire, qui répartit l'argent entre de nombreuses obligations", "Via un livret", "C'est impossible"], correct: 1,
      good: "Via un fonds obligataire",
      explain: "L'AMF le rappelle&nbsp;: on investit le plus souvent en obligations par des fonds et Sicav obligataires. Un fonds répartit le risque de défaut entre de nombreux émetteurs, mais il a ses propres frais et n'a pas de date de remboursement unique.",
      fact: { label: "Accès pour un particulier", value: "Le plus souvent via des fonds obligataires", src: "amfobl" },
      ask: "Combien d'émetteurs ce fonds détient-il, et quelle part est notée en dessous de BBB-&nbsp;?" },
  ],
  notes: [
    "La fiche du Décodeur cite des rendements « autour de 5 % à 5,5 % courant 2026, soit environ 0,9 à 1 point de plus qu'une obligation d'État » sans source ni date : à sourcer ou à retirer.",
    "S&P Global Ratings n'est pas dans la liste des sources prioritaires : c'est l'agence de notation elle-même, qui définit sa propre échelle.",
  ],
};

export const OBLIGATIONS_BANKS: Bank[] = [oat, treasury, entreprise];
