import type { Bank } from "../types";
import { FICHE, AMF_STRUCTURES_NOTE, AMF_STRUCTURES_ETUDE } from "../sources";

export const garanti: Bank = {
  id: "produit-capital-garanti",
  name: "Produit structuré à capital garanti (exemple générique)",
  sub: "Produit générique du Décodeur",
  short: "Produit à capital garanti",
  family: "Produits structurés",
  share: "Mon produit à capital garanti, je le comprends",
  axes: ["Nature", "Garantie", "Disponibilité", "Émetteur", "Gains"],
  src: {
    amfnote: AMF_STRUCTURES_NOTE,
    amfetude: AMF_STRUCTURES_ETUDE,
    amf1312: { name: "AMF, position DOC-2013-12 sur la garantie des produits structurés", date: "mise à jour le 8 déc. 2025", url: "https://www.amf-france.org/en/regulation/policy/doc-2013-12", refresh: "Revu à chaque mise à jour de la position" },
    fiche: FICHE,
  },
  questions: [
    { id: "g1", axis: "Nature", type: "choice",
      prompt: "Un produit à capital garanti combine en général&nbsp;:",
      options: ["Une partie qui vise à rendre votre capital à l'échéance, et une partie liée à un indice qui détermine le gain", "Uniquement des actions", "Un livret et un compte courant", "Un crédit immobilier"], correct: 0,
      good: "Une partie sécurisée et une partie liée à un indice",
      explain: "La banque assemble deux briques&nbsp;: l'une vise à restituer le capital à l'échéance, l'autre, liée à un indice ou à un panier de valeurs, détermine le gain selon une formule écrite à l'avance.",
      fact: { label: "Fonctionnement", value: "Partie sécurisée + partie liée à un indice, selon une formule", src: "fiche" },
      ask: "Quelle est exactement la formule de gain de ce produit, et sur quel indice&nbsp;?" },
    { id: "g2", axis: "Garantie", type: "choice",
      prompt: "La garantie du capital joue&nbsp;:",
      options: ["À tout moment", "À l'échéance prévue, si vous conservez le produit jusqu'au bout", "Seulement si l'indice monte", "Seulement la première année"], correct: 1,
      good: "À l'échéance prévue",
      explain: "La protection vaut à la date d'échéance fixée au contrat. Si vous sortez avant, vous récupérez la valeur de marché du produit ce jour-là, qui peut être inférieure à votre mise&nbsp;: l'AMF rappelle ce risque de perte en cas de revente avant l'échéance.",
      fact: { label: "Sortie avant l'échéance", value: "Risque de perte en capital en cas de revente avant l'échéance", src: "amfetude" },
      ask: "À quelle date exacte la garantie s'applique-t-elle&nbsp;?" },
    { id: "g3", axis: "Disponibilité", type: "choice",
      prompt: "Vous devez récupérer votre argent avant l'échéance. Vous recevez&nbsp;:",
      options: ["Votre capital, garanti", "Le prix du marché du produit ce jour-là, qui peut être inférieur à votre mise", "Rien, c'est interdit"], correct: 1,
      good: "Le prix du marché, parfois inférieur",
      explain: "Avant l'échéance, le produit se revend à sa valeur du moment, qui dépend des marchés et des taux. L'étude de l'AMF de janvier 2026 recommande d'avertir clairement l'épargnant de ce risque de perte.",
      fact: { label: "Revente anticipée", value: "Au prix du marché, avec un risque de perte", src: "amfetude" },
      ask: "Comment est calculé le prix de rachat si je sors avant l'échéance, et quels frais s'appliquent&nbsp;?" },
    { id: "g4", axis: "Émetteur", type: "choice",
      prompt: "Qui garantit votre capital&nbsp;?",
      options: ["L'État", "Un établissement financier, souvent la banque qui a conçu le produit", "Le fonds de garantie des dépôts", "Personne"], correct: 1,
      good: "Un établissement financier",
      explain: "La garantie est apportée par un établissement financier, pas par l'État. Pour certains produits structurés vendus au grand public, l'AMF demande que la garantie soit apportée par une entité habilitée. Mais si cet établissement fait défaut, la garantie peut ne pas jouer&nbsp;: d'où l'intérêt de connaître son nom et sa notation.",
      fact: { label: "Garant", value: "Un établissement habilité, pas l'État", src: "amf1312" },
      ask: "Quel établissement garantit ce produit, et quelle est sa notation&nbsp;?" },
    { id: "g5", axis: "Gains", type: "choice",
      prompt: "L'indice de référence monte de 50&nbsp;% pendant la vie du produit. Vous gagnez&nbsp;:",
      options: ["50&nbsp;%, comme l'indice", "Ce que prévoit la formule, souvent plafonné, et parfois bien moins que la hausse de l'indice", "Le double de la hausse"], correct: 1,
      good: "Ce que prévoit la formule, souvent plafonné",
      explain: "La protection a un prix&nbsp;: le gain est en général limité par la formule. L'AMF souligne que, dans les produits structurés, les gains sont souvent plafonnés. Ici, en contrepartie, le capital est protégé à l'échéance.",
      fact: { label: "Gains", value: "Fixés par la formule, souvent plafonnés", src: "amfnote" },
      ask: "Quel est le gain maximum possible, et dans quel scénario&nbsp;?" },
    { id: "g6", axis: "Garantie", type: "slider",
      min: 5000, max: 10000, step: 50, start: 9800, unit: "€", target: 8535, tol: [150, 500], dec: 0, gapUnit: "€", fem: false,
      real: "≈ 8&nbsp;535&nbsp;€", realLabel: "Réponse (calcul Kompa)",
      prompt: "Exemple fictif&nbsp;: vous récupérez exactement vos 10&nbsp;000&nbsp;€ au bout de 8 ans. Avec une inflation de 2&nbsp;% par an, combien valent-ils en euros d'aujourd'hui&nbsp;?",
      good: "Environ 8&nbsp;535&nbsp;€",
      explain: "10&nbsp;000&nbsp;€ divisés par 1,02 huit fois, cela donne environ 8&nbsp;535&nbsp;€. Le capital est rendu en euros, pas en pouvoir d'achat&nbsp;: sans gain, la garantie ne protège pas de l'inflation.",
      fact: { label: "Capital garanti et inflation", value: "Le capital est garanti en euros, pas en pouvoir d'achat", src: "fiche", note: "Calcul Kompa&nbsp;: 10&nbsp;000 ÷ 1,02⁸ ≈ 8&nbsp;535. Exemple fictif, pas une prévision de l'inflation." },
      ask: "Quel gain minimum ce produit prévoit-il, et que vaudra mon capital une fois l'inflation déduite&nbsp;?" },
    { id: "g7", axis: "Disponibilité", type: "choice",
      prompt: "Selon l'AMF, sur quelle durée ces produits sont-ils souvent proposés&nbsp;?",
      options: ["Quelques semaines", "1 an", "Entre 8 et 12 ans", "Sans limite"], correct: 2,
      good: "Entre 8 et 12 ans",
      explain: "L'étude de l'AMF évoque des durées généralement comprises entre 8 et 12 ans. C'est long&nbsp;: la garantie suppose d'être sûr de ne pas avoir besoin de cet argent d'ici là.",
      fact: { label: "Durée des produits", value: "Souvent entre 8 et 12 ans", src: "amfetude" },
      ask: "Quelle est la durée exacte de ce produit, et existe-t-il des dates de sortie anticipée&nbsp;?" },
  ],
  notes: [
    "Chaque produit à capital garanti a son propre document d'informations clés : pour un produit précis, le Clarity Test personnel est le bon outil.",
  ],
};

export const autocall: Bank = {
  id: "autocall",
  name: "Autocall (produit structuré à remboursement anticipé conditionnel)",
  sub: "Produit générique du Décodeur",
  short: "Autocall",
  family: "Produits structurés",
  share: "Mon autocall, je le comprends",
  axes: ["Nature", "Gains", "Risque", "Émetteur", "Horizon"],
  src: { amfnote: AMF_STRUCTURES_NOTE, amfetude: AMF_STRUCTURES_ETUDE, fiche: FICHE },
  questions: [
    { id: "c1", axis: "Nature", type: "choice",
      prompt: "Qui décide si un autocall est remboursé par anticipation&nbsp;?",
      options: ["Vous, quand vous le souhaitez", "La banque, à sa discrétion", "La formule du produit&nbsp;: c'est automatique si l'indice atteint un certain niveau à une date d'observation", "Personne, il n'y a jamais de remboursement anticipé"], correct: 2,
      good: "La formule, automatiquement",
      explain: "Le rappel est automatique&nbsp;: à chaque date d'observation, si l'indice de référence est au-dessus du seuil prévu, le produit s'arrête et vous êtes remboursé. Vous ne choisissez ni la date de sortie, ni la durée réelle.",
      fact: { label: "Remboursement anticipé", value: "Automatique, selon la formule, à des dates fixées", src: "amfnote" },
      ask: "À quelles dates l'indice est-il observé, et à quel niveau le produit est-il rappelé&nbsp;?" },
    { id: "c2", axis: "Gains", type: "tf",
      prompt: "Le coupon d'un autocall est versé quoi qu'il arrive.",
      options: ["Vrai", "Faux"], correct: 1,
      good: "Faux",
      explain: "Le coupon est conditionnel&nbsp;: il n'est versé que si la condition prévue par la formule est remplie, en général un niveau de l'indice à la date d'observation.",
      fact: { label: "Coupon", value: "Conditionnel, lié au niveau de l'indice", src: "amfnote" },
      ask: "Que deviennent les coupons les années où la condition n'est pas remplie&nbsp;?" },
    { id: "c3", axis: "Gains", type: "choice",
      prompt: "L'indice de référence monte de 40&nbsp;% pendant la vie du produit. Vous gagnez&nbsp;:",
      options: ["Environ 40&nbsp;%, comme l'indice", "Le coupon prévu, pas plus", "Le double de la hausse", "Rien du tout"], correct: 1,
      good: "Le coupon prévu, pas plus",
      explain: "Vos gains sont limités au coupon prévu par la formule, même si l'indice s'envole. L'AMF résume ce profil ainsi&nbsp;: des gains plafonnés, alors que les pertes peuvent être totales.",
      fact: { label: "Profil de gains", value: "Gains plafonnés, pertes pouvant être totales", src: "amfnote" },
      ask: "Quel est le gain maximum possible sur ce produit, et dans quelles conditions&nbsp;?" },
    { id: "c4", axis: "Risque", type: "slider",
      min: 0, max: 100, step: 1, start: 20, unit: "%", target: 45, tol: [3, 10], dec: 0, gapUnit: "point",
      real: "45&nbsp;%", realLabel: "Perte dans cet exemple",
      prompt: "Exemple fictif&nbsp;: barrière de protection à 60&nbsp;%. À l'échéance finale, l'indice a perdu 45&nbsp;% (il vaut 55&nbsp;% de son niveau de départ). Quelle part de votre capital perdez-vous&nbsp;?",
      good: "45&nbsp;% du capital",
      explain: "La barrière ne protège que tant que l'indice reste au-dessus d'elle. Ici, il est passé dessous&nbsp;: dans le mécanisme le plus courant, la perte suit alors toute la baisse de l'indice, soit 45&nbsp;%, et pas seulement les 5 points situés sous la barrière.",
      fact: { label: "Barrière de protection", value: "Sous la barrière, la protection disparaît&nbsp;: la perte suit la baisse de l'indice", src: "amfnote", note: "Mécanisme le plus courant&nbsp;; la formule exacte figure dans la documentation de chaque produit." },
      ask: "Si l'indice termine sous la barrière, comment ma perte est-elle calculée exactement&nbsp;?" },
    { id: "c5", axis: "Émetteur", type: "choice",
      prompt: "La banque qui a émis votre autocall fait faillite. Que risquez-vous&nbsp;?",
      options: ["Rien, l'indice garantit le remboursement", "De perdre tout ou partie de votre argent, même si l'indice va bien", "Seulement les coupons, jamais le capital"], correct: 1,
      good: "Perdre tout ou partie de votre argent",
      explain: "Un autocall est un engagement de la banque émettrice. Si elle ne peut plus payer, l'AMF souligne que vous pourriez perdre votre argent, quelle que soit l'évolution de l'indice. D'où l'intérêt de connaître le nom de l'émetteur et sa notation.",
      fact: { label: "Risque de crédit de l'émetteur", value: "En cas de défaut de la banque, perte possible de tout le capital", src: "amfetude" },
      ask: "Quelle banque émet ce produit, et quelle est sa notation&nbsp;?" },
    { id: "c6", axis: "Risque", type: "choice",
      prompt: "Certains autocalls s'appuient sur un indice «&nbsp;à décrément&nbsp;». Cela veut dire&nbsp;:",
      options: ["Un indice qui ne peut pas baisser", "Un indice dividendes réinvestis, duquel on retire chaque année un montant fixe", "Un indice limité aux entreprises françaises", "Un indice garanti par l'État"], correct: 1,
      good: "On retire chaque année un montant fixe de l'indice",
      explain: "On part d'un indice qui réinvestit les dividendes, puis on lui retire chaque année un montant fixe. Le risque lié aux dividendes passe à l'investisseur, et l'effet pénalise davantage l'indice quand les marchés baissent, surtout avec un décrément en points. L'AMF relève que ces indices concernaient environ 38&nbsp;% des encours commercialisés en 2023.",
      fact: { label: "Indices à décrément", value: "Environ 38&nbsp;% des encours commercialisés en 2023", src: "amfetude" },
      ask: "L'indice de ce produit est-il à décrément, et de combien&nbsp;?" },
    { id: "c7", axis: "Horizon", type: "choice",
      prompt: "Pour quelle durée maximale un autocall est-il souvent proposé&nbsp;?",
      options: ["1 an", "3 ans", "8 à 12 ans", "Sans limite"], correct: 2,
      good: "8 à 12 ans",
      explain: "L'AMF indique des durées généralement comprises entre 8 et 12 ans, même si beaucoup de produits sont rappelés bien plus tôt. Si vous devez sortir avant le rappel ou l'échéance, la revente peut entraîner une perte en capital importante.",
      fact: { label: "Durée de vie", value: "Souvent 8 à 12 ans au maximum", src: "amfetude" },
      ask: "Si je dois récupérer mon argent avant l'échéance, à quel prix pourrais-je revendre&nbsp;?" },
  ],
  notes: [
    "Fiche du Décodeur réécrite le 7 octobre 2026 en langage simple : les chiffres sans source (coupons « 6 % à 10 % », barrière « autour de 60 % ») ont été retirés ; la fiche et le test utilisent le même exemple fictif (barrière à 60 %, baisse de 45 %).",
    "Chaque autocall a son propre DIC : pour un produit précis, le Clarity Test personnel est le bon outil.",
  ],
};

export const STRUCTURES_BANKS: Bank[] = [garanti, autocall];
